### ISSUE TITLE
Provide more pointed use-case based codesandbox examples for issue template

### ISSUE THREAD

**Issue by rosskevin** [apollographql/react-apollo#2699] opened 2018-12-28 23:52 UTC
## Problems

- many issues are filed without reproductions
- the existing codesandbox template suggested in the issue template uses the `graphql` hoc and does a very simple query.  
- most documentation and issues filed are related to the components themselves - `Query`, `Mutation`, and `Subscription`.  
- it is difficult to communicate with the community when even the good reproductions are based on wildly different code bases.  
- the issue template also points to a template repo, but I believe this is a less collaborative approach to understanding and resolving issues

## Proposed solution

Ideally, I think it would be most beneficial to provide the following samples (minimally) in a react/typescript/react-apollo sandbox and place them prominently in the issue template:

- Query
- Mutation
- Subscription

Having them in typescript yields much additional benefit - knowing types are met is a good indicator of a quality reproduction.  More cases with the hoc etc are also welcome, but I suggest the above as a priority.

## Benefits

- It is much faster to collaborate via codesandbox than a repository (in most cases)
- Given the ease of running - more people will put their eyes on an issue and fork/attempt fixes
- Dependency versions can be updated quickly for old issues
- Further, unit tests can be added and results are provided in browser 
- Codesandboxes will provide pristine examples and a source for learning effectively avoiding new issues that are solved in the attempt to reproduce

I believe this tool to be far and away a huge productivity leap to collaborate better with the community.  Integrating codesandbox links directly in the docs on material-ui.com has been a huge benefit to us as maintainers, and I think we should learn from that and bring it here as well.

## Some samples
Here are some I've bumped into (not typescript but you get the gist):
- `Mutation` with `MockedProvider` https://codesandbox.io/s/6zqvyy0zjr
- Reduced unit test case (breaking) of react-test-renderer and `MockedProvider` https://codesandbox.io/s/p9lo49mz50 from https://github.com/apollographql/react-apollo/issues/2603#issuecomment-450178604

I'm not saying the above should be used necessarily, but they are examples that have been submitted already.

## Proposed Implementation
- Is there already a set of good apollo samples that we should refine to codesandbox templates?
- We can maintain these pristine examples in a subdirectory here and the codesanbox will always stay up to date with commits.  https://codesandbox.io/docs/importing#import-from-github
- Perhaps `/examples` should be refined for these cases?  Or should we have a `/sandboxes` dir with targeted examples?

## Conclusion 

After having spent quite some time cleaning up issues this week, it would be my preference to:
- implement these codesandboxes swiftly
- place the codesandboxes prominently in the issue template 
- with exception to proposals or feature requests, require a codesandbox - otherwise the issue gets closed

Maintaining a quality set of issues is important to project health, and I see no better way than to introduce these templates and be diligent with closing issues that cannot be reproduced.  We do our part by providing simple, quality codesandboxes and I think the community will do their part and provide good reproductions.

@hwillson @benjamn @danilobuerger @JoviDeCroock @excitement-engineer @jbaxleyiii @peggyrayzis - thoughts?

**Comment by danilobuerger** [comment] 2018-12-29 07:15
Great idea!

**Comment by JoviDeCroock** [comment] 2018-12-29 10:54
This looks super and would decrease the time to live on issues, a reproduction helps so much :)

**Comment by arist0tl3** [comment] 2018-12-29 17:09
I'm excited to see this issue, as coding up a reproduction repo is pretty painful. I would advocate for component and hoc-based versions of Query, Mutation and Subscription and am willing to help contribute to the hoc side.

**Comment by lamflam** [comment] 2019-01-07 18:46
@rosskevin I filed an issue today with a codesandbox reproduction for both [client](https://codesandbox.io/s/jnrv4ykkzv) and [server](https://codesandbox.io/s/6yvq7p39kk) as separate sandboxes. This was very quick and easy to do and would be even easier with a decent client template.

I imagine a single server sandbox could be setup that supports the majority of query/mutation features and client templates could all just point at its' graphql endpoint. If the reproduction required a more complicated server, there would still be the ability to fork and expand on it.

**Comment by rosskevin** [comment] 2019-01-07 19:24
Thanks @lamflam, that is a great example!  

I'm thinking a single universal (forkable) server sandbox/schema that serves for all client sandboxes is probably the best.  We really just need to settle on the server sandbox schema etc then writing the client sandboxes should be quick and easy.

What should we use for the server schema?

**Comment by hwillson** [comment] 2019-01-17 19:45
First off @rosskevin, thanks very much for looking into this! We've talked about improving all of this internally for quite some time, but haven't had a chance to get to it yet. We definitely agree that having great reproduction apps available are essential! I've attempted to answer all questions/comments from this thread - let me know if I've missed anything. 

- Having a repro starter app that uses queries, mutations and subscriptions would be perfect. While it could make sense to have these as separate apps, I think from a maintenance point of view it might be better if everything was in one app. We could setup a pretty simple app that does one query, one mutation, and has one subscription, and includes comments/notes showing people how to disable the parts of the repro they don't need.
- Typescript all the way. It's easy enough to take a Typescript based repro and convert it to a plain JS repro, but it's more challenging to go the other way. Let's just provide a TS based repro.
- I'm all for having the repro app show examples of using both Apollo Components and a HOC approach.
- Codesanbox sounds great! We're slowly migrating a lot of our sample apps over to it, for both client and server (replacing our use of Glitch or Launchpad for the server side).
- I definitely think we should leverage the approach and data model of the [fullstack tutorial](https://github.com/apollographql/fullstack-tutorial), when coming up with the Query, Mutation and Subscription examples in the repro.
- Yes, housing the source for the repro in this repository, under `/examples/reproduction` or equivalent, then synching with codesandbox, sounds great to me.
- We should definitely push issue reporters towards supplying a reproduction (when needed). If they don't supply one, let's give them a heads up that we need one to be able to help them, label the issue with `reproduction-needed`, then give them a chance to supply one. If they don't within a certain time frame, like 2 weeks, we'll close the issue.

When it comes to handling the server side of things (the graphql endpoint), I'm a bit torn on this one. I really like how the current [React Apollo error template](https://github.com/apollographql/react-apollo-error-template) keeps the repro focused on Apollo Client / React Apollo. By faking the server side of things, we don't have to worry about reproductions potentially leading down a rabbit hole, caused by the introduction of issues on the server side. Instead, the reproduction can still use a schema (based on examples from the `fullstack-tutorial`), along with a dummy data set, and use a custom Apollo Link to fake out all server interactions (just like the `react-apollo-error-template` does). Sure, there could be complex interactions between Apollo Client / React Apollo and the server side, which will need a full environment to reproduce, but those cases are definitely the exception. I think we can cover most cases with a mocked out backend.

One last thing - right now the `react-apollo-error-template` we're using for reproductions is being used for both Apollo Client and React Apollo. We should consider splitting this up, so we have a reproduction template/app that is Apollo Client specific, and one that is React Apollo specific. That doesn't really impact the work here, it's just more of an FYI. When we tackle the repro work in this repo, we should also tackle similar work in the Apollo Client repo (note to self).

Does that help answer the outstanding questions? If anyone wants to work on this, that would be awesome! Definitely `help-wanted`. Thanks!

**Comment by hwillson** [comment] 2019-06-15 11:14
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, React Apollo feature requests are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Provide%20more%20pointed%20use-case%20based%20codesandbox%20examples%20for%20issue%20template&body=Migrated%20from:%20apollographql/react-apollo%232699) to start the feature request migration process. This manual migration process is intended to help identify which of the outstanding feature requests are still considered to be of value to the community. Thanks!

**Closed by hwillson** 2019-06-15 11:14 UTC
Labels: discussion, help-wanted, high-priority
