### ISSUE TITLE
SSR: error render props do not be passed into <Query /> as expected (errorPolicy: 'all')

### ISSUE THREAD

**Issue by chentsulin** [apollographql/react-apollo#2134] opened 2018-06-24 09:38 UTC
I built a codesandbox app (https://codesandbox.io/s/r7mxnx486q) and a next ssr app(https://github.com/chentsulin/react-apollo-issue) to confirm that they have totally different behavior when rendering the error. 

For demo, I use following code exmaple

```js
function App() {
  return (
    <div className="App">
      <ApolloProvider client={client}>
        <Query query={Hello}>
          {({ data, error, loading }) => {
            console.log({ data, error, loading });
            if (loading) return "loading..";
            if (error) return error.message;
            return data.hello;
          }}
        </Query>
      </ApolloProvider>
    </div>
  );
}
```

And a launchpad to throw a error in Hello query:

https://launchpad.graphql.com/kqrn1n1qj7

### Client Side Rendering

(example: https://codesandbox.io/s/r7mxnx486q)

It works as expected in client side rendering. 

Props were logged twice with following format (got error in second time rendering):

```js
{ data: {}, error: undefined, loading: true }
{ data: undefined, error: ApolloError, loading: false }
```

### Server Side Rendering

(example: https://github.com/chentsulin/react-apollo-issue)

Props were logged twice with no error:

{ data: { hello: null }, error: undefined, loading: false }
{ data: { hello: null }, error: undefined, loading: false }

### Relevant Issues

https://github.com/apollographql/apollo-link/issues/437
https://github.com/apollographql/apollo-client/issues/2880
https://github.com/apollographql/react-apollo/issues/2124
https://github.com/apollographql/react-apollo/issues/2087
https://github.com/apollographql/react-apollo/issues/1389

I dived into source of `<Query />`, and logged some details. I found that it call `watchQuery` twice and create two different queryIds.

```
initializeQueryObservable watchQuery - queryId { queryId: '1' }
fetchData watchQuery - queryId { queryId: '2' }
```

Then it save errors into queryId: 2

```js
queryStore.markQueryResult { queryId: '2',
  result:
   { data: { hello: null },
     errors: [ [Object] ] }
```

And finally it found `queryStoreValue` from queryId: 1 but store only have value for queryId: 2, so it pass undefined as result to render props:

```js
queryId { queryId: '1' }
getStore { '2':
   { document: { kind: 'Document', definitions: [Array], loc: [Object] },
     previousVariables: null,
     networkError: null,
     graphQLErrors: [ [Object] ],
     networkStatus: 7,
     metadata: null } }
{ queryStoreValue: undefined }
```

what is the purpose of those two queryObservable? It is a little confusing.

https://github.com/apollographql/react-apollo/blob/3985b47f086f38f891099732842ca2f16c7966c4/src/Query.tsx#L183-L189

**Comment by kasbah** [comment] 2018-07-03 03:00
Dupe of #1972 (and #1781?)

**Comment by tobobo** [comment] 2018-12-14 18:56
I've opened a PR to fix the docs with respect to this issue https://github.com/apollographql/apollo-client/pull/4237

**Closed** 2019-01-28 19:32 UTC
