### ISSUE TITLE
No matter what useMutation trows errors...

### ISSUE THREAD

**Issue by isopterix** [apollographql/react-apollo#3375] opened 2019-08-16 10:17 UTC
It is normal that useMutation is throwing errors rather than gracefully catching them and returning the result to the "error" result variable?

I get "Uncaught (in promise) Error:..." if there is a GraphQL error or a Network error related to a mutation that I want to execute with "useMutation" hook.

How can I catch this error and prevent it from showing in the console?

The error result variables seem to work. I can influence the UI with those variables... but no matter what, Apollo still throws the error as well.

"react-dom": "^16.9.0",
"@apollo/react-hooks": "^3.0.0",
"apollo-boost": "^0.4.4",

**Comment by wendelfreitas** [comment] 2019-08-17 18:59
@isopterix i have the same problem, in specific this: **Error: Network error: null is not an object (evaluating '_ref2.token)**

**Comment by hwillson** [comment] 2019-08-19 13:03
@isopterix @wendelfreitas Any chance one of you could provide a small runnable reproduction?

**Comment by wendelfreitas** [comment] 2019-08-19 13:15
@hwillson and @isopterix after delving deeper, I found that it was the apollo configuration, the configuration changes slightly if you are using apollo-boost ApolloClient, and the problem was just that.

**Comment by isopterix** [comment] 2019-08-19 16:39
In my case I guess it was not really understanding the concept of the errorPolicy settings. And if I am honest, I still have not really understood the difference between the 3 possible options.

If I change it from the default `none` to something else the red JS errors in the console disappear and error are only logged as text if I explicitly request the to via the `error` handler.

But otherwise it will always be both, the red error and the text from the error handler.

Is this how it is supposed to be?

**Comment by hwillson** [comment] 2019-09-06 12:10
It sounds like this has been resolved, so closing. For questions head on over to [Apollo’s Spectrum community](https://spectrum.chat/apollo). Thanks!

**Closed by hwillson** 2019-09-06 12:10 UTC
Labels: reproduction-needed
