### ISSUE TITLE
useQuery: on using refetch, 'loading' keeps true when same error returned twice or more

### ISSUE THREAD

**Issue by jet2jet** [apollographql/react-apollo#3395] opened 2019-08-20 14:13 UTC
When using `refetch` method on the return value of `useQuery`, and an error returned with the same `name` and `message` for the previous error, `loading` value of the return value keeps `true` (not changes to `false`), even if `notifyOnNetworkStatusChange` option is `true`.

**Intended outcome:**

`loading` changes to `false` whenever an error returned

**Actual outcome:**

`loading` keeps `true` when the same error returned (though it changes to `false` on the _first_ error)

**How to reproduce the issue:**

I created an repository with the reproduction code here:
https://github.com/jet2jet/react-apollo-test

After build and open `dist/index.html`, when clicking 'Refetch' at first, an error data will be shown. But when clicking 'Refetch' on the third time (`callCount = 4` on the log), 'Loading...' will be shown (an error data should be shown on this time).

**Version**

Note: I think this problem might not occur with react-apollo: 3.0.0

  npmPackages:
    apollo-cache-inmemory: ^1.6.3 => 1.6.3
    apollo-client: 2.6.4 => 2.6.4
    react-apollo: 3.0.1 => 3.0.1

**Comment by jet2jet** [comment] 2019-08-20 14:17
I think the following code is not working as expected...
https://github.com/apollographql/react-apollo/blob/be122f036c54892cc0632ed21f41fff9574ea096/packages/hooks/src/data/QueryData.ts#L288
(it seems that `equal` from `@wry/equality` does only compares `name` and `message` for Error object: https://github.com/benjamn/wryware/blob/master/packages/equality/src/equality.ts#L72 )

**Comment by Kreozot** [comment] 2019-08-21 09:26
I confirm the issue.
I've created the sandbox for this issue: https://codesandbox.io/s/quirky-dhawan-csdxw
First time error handled correctly, but when the query is updating, error is disappears and loading is forever true.

**Comment by Kreozot** [comment] 2019-08-21 09:35
❗️  Important notice: When I change version of @apollo/react-hooks from 3.0.1 to 3.0.0 the issue is not reproducing. So maybe we should find the error in changes in 3.0.1 version.

**Comment by Kreozot** [comment] 2019-08-21 09:38
So, for original issue I recommend to change version of react-apollo to 3.0.0 and try to reproduce.

**Comment by hinok** [comment] 2019-08-21 11:38
I struggle with the same issue.

I made codesandbox that shows this issue: https://codesandbox.io/s/react-apollo-3x-and-loading-true-i7ub1

This issue doesn't exist when `react-apollo@3.0.0` is used.

**Comment by dylanwulf** [comment] 2019-08-23 17:37
@jet2jet That code was recently added in PR #3339. The purpose of that PR was to set `loading` properly when `refetch` is called, but it seems like it's still not working correctly

**Comment by Kreozot** [comment] 2019-08-26 14:01
Looks like a blocker for me.

**Comment by hwillson** [comment] 2019-09-06 12:36
Could someone here re-test using React Apollo 3.1.0 and let us know if this is still an issue? Thanks!

**Comment by jet2jet** [comment] 2019-09-06 13:01
> Could someone here re-test using React Apollo 3.1.0 and let us know if this is still an issue?

@hwillson I tried with react-apollo@3.1.0, but (unfortunately) the problem still occurs.  
(reproduction: `npm install --save-exact react-apollo@3.1.0` on the repository https://github.com/jet2jet/react-apollo-test , build with `npm run build`, and view `dist/index.html`)  
Thanks!

**Comment by hinok** [comment] 2019-09-06 15:32
@hwillson This issue still exists https://codesandbox.io/s/react-apollo-310-and-loading-true-tl1x0

**Comment by diazdell91** [comment] 2019-09-06 19:49
https://github.com/apollographql/react-apollo/issues/3270#issuecomment-528300510

**Comment by jet2jet** [comment] 2019-09-08 12:15
@hwillson I created PR #3477 to fix the problem, so please review it. Thanks.

**Comment by hwillson** [comment] 2019-09-11 12:58
https://github.com/apollographql/react-apollo/pull/3477 has been merged (thanks @jet2jet!), and will be coming shortly in a patch release.

**Closed by hwillson** 2019-09-11 12:58 UTC
