### ISSUE TITLE
Multiple times mutation update

### ISSUE THREAD

**Issue by ArronHsiao** [apollographql/react-apollo#3183] opened 2019-06-26 03:43 UTC
When I trying to do some update after Mutation, it runs **several times more than once** (expect to run just once)

ex.

**update**: (dataProxy, { data: { someMutation } }) => {
const data = dataProxy.readQuery({ query, variables });
**data.someMutation.items = [ newItem, ...oldItems]**
dataProxy.writeQuery({ query, variables, data })
}

and the concat of items runs multiple times...

 System:
    OS: macOS 10.14.4
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.6.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 66.0.5
    Safari: 12.1
  npmPackages:
    apollo-link: ^1.2.2 => 1.2.2 
    apollo-link-state: ^0.4.1 => 0.4.1 
    react-apollo: ^2.5.8 => 2.5.8 
    react: 16.5.0

**Comment by jasonpaulos** [comment] 2019-06-26 18:08
This appears similar to #3172

**Comment by jasonpaulos** [comment] 2019-06-27 18:47
@ArronHsiao Thanks for reporting this. Could you provide a small runnable reproduction as a github issue or codesandbox that demonstrates this issue?

**Comment by ArronHsiao** [comment] 2019-06-28 01:47
ok, I'll try later~~ thank you ^^

**Comment by lensbart** [comment] 2019-08-13 18:33
It’s normal for the `update` function to run twice if you specified an `optimisticResponse`: in this case it will run immediately with the optimistic response, and a second time once data is returned from the server.

**Comment by hwillson** [comment] 2019-09-06 12:05
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!

**Closed by hwillson** 2019-09-06 12:05 UTC
Labels: reproduction-needed
