### ISSUE TITLE
Compose function not working as expected

### ISSUE THREAD

**Issue by ryannealmes** [apollographql/react-apollo#315] opened 2016-11-07 07:45 UTC
Using the compose function I ran into a problem where props were not being passed to my connected component state changes.

I was using the compose function below

```javascript
const mapStateToProps = (state) => ({
  filtering: state.filtering,
  sorting: state.sorting
});

export default compose(
  graphql(query, config),
  connect(mapStateToProps, mapDispatchToProps)
)(PeopleContainer);
```

after changing to 

I was using the compose function below

```javascript
const mapStateToProps = (state) => ({
  filtering: state.filtering,
  sorting: state.sorting
});

export default compose(
  connect(mapStateToProps, mapDispatchToProps),
  graphql(query, config)
)(PeopleContainer);
```
I think some things required to reproduce might be related to my setup.
- I am using redux
- it's integrated with the apollo client

"apollo-client": "0.5.0",
"react-apollo": "0.5.16",
"graphql-tag": "0.1.15",

This might not be a bug, but I thought I would mention it since the documentation connects the redux store after the graphql query and mutations. If this intended, it may be worth mentioning in the docs that order matters.

http://dev.apollodata.com/react/higher-order-components.html#

**Comment by stubailo** [comment] 2016-11-08 07:13
This is surprising, I would have expected it to work both ways. I wonder if perhaps it's something to do with `react-redux`. Can you create a reproduction app or failing test we can try out?

**Comment by ryannealmes** [comment] 2016-11-08 07:19
I don't have time right now, have a long flight today, but I will see what I can do in the next couple of days.

**Comment by stefanorg** [comment] 2016-11-10 10:06
I had the same issue, a very simple component with a search input text and a tabular data filtered by the search input.

```
// @flow
import React, { Component } from 'react';
import Home from '../components/Home';
import { graphql, compose } from 'react-apollo';
import { connect } from 'react-redux';
import gql from 'graphql-tag';

const TestQuery = gql`
  query test($query: String) {
    dispositivi (search: {q:$query}){
      id,
      nome,
      seriale
    }
  }
`;

const queryOptions = {
  props: ({ ownProps, data }) => ({
    loading: data.loading,
    dispositivi: data.dispositivi
  }),
  options(props) {
    console.log("queryOptions props", props);
    return {
      variables: {
        query: props.searchQuery
      }
    };
  },
};

const HomePageWithDataAndState = compose(
  graphql(TestQuery, queryOptions), //<--THIS IS WRONG
  connect(
    // stateToProps
    (state) => ({
      searchQuery: state.search.query
    })
  ),
)(Home);

export default HomePageWithDataAndState;
```

I had to put **graphql(TestQuery, queryOptions)** at the bottom as pointed by @ryannealmes 

```
const HomePageWithDataAndState = compose(
  connect(
    // stateToProps
    (state) => ({
      searchQuery: state.search.query
    })
  ),
graphql(TestQuery, queryOptions), //<--THIS IS GOOD
)(Home);
```

At this point the client is aware of the changed `searchQuery` prop once the redux action is dispatched and the apollo middleware take care of re run the query.

**Comment by abhiaiyer91** [comment] 2017-01-25 15:22
https://github.com/reactjs/redux/blob/master/docs/api/compose.md

Compose is just like lodash flowRight. So functions will read right to left or top to bottom however visually you write your HOC.

I think we can close this issue

**Comment by advance512** [comment] 2017-03-16 08:27
Why does the order being left to right or right to left matter?
According to the [documentation](http://dev.apollodata.com/react/redux.html#using-connect):

> You can connect before or after (or both!) attaching GraphQL data to your component with graphql

This is obviously not true if what is reported above occurs. 

In fact I'm having the same issue the previous posters reported - only worse. I can't get react-apollo and react-redux to work together with the same component.

```
import { graphql } from 'react-apollo';
import { connect, compose } from 'react-redux';

...
...

const enhance = compose(
  graphql(ViewerAccountsQuery, {
    props: mapViewerAccountsQueryResultsToProps,
  }),
  graphql(IdentityDetailsQuery, {
    props: mapIdentityDetailsQueryResultsToProps,
  }),
  connect(mapStateToProps, mapDispatchToProps),
);

export const AccountVerifier = enhance(AccountVerifierControl);
```

This doesn't work. Nor does putting connect() as the first item in the compose() list. Following mapStateToProps (even an empty one, that just returns {}), the other HOC functions aren't called.

Not sure what the issue is, to be honest, but it seems like it is indeed with react-redux and not react-apollo.

**Comment by advance512** [comment] 2017-03-16 08:28
I am thinking [this](https://github.com/reactjs/react-redux/issues/210) might be relevant somehow.

**Comment by helfer** [comment] 2017-03-21 07:40
Could one of you provide a reproduction of this with https://github.com/apollographql/react-apollo-error-template please? Thanks! 🙂

**Closed** 2017-05-03 04:09 UTC

**Comment by advance512** [comment] 2017-06-04 14:32
I think the issue I encountered was having multiple versions of redux or react-redux installed. Non deterministic NPM FTW.

**Comment by Deilv** [comment] 2017-08-02 16:22
This issue still exists in react-apollo 1.4.10.

The code below fails.
`export const viewerQuery = gql`
    query viewer($token: String) {
        viewer(token: $token) {
            username
        }
    }
`;

export const viewerQueryOptions = {
    options: ({ token }) => ({
        variables: { token },
        fetchPolicy: 'network-only'
    })
};

export default compose(
    graphql(viewerQuery, viewerQueryOptions),
    connect(mapStateToProps, mapDispatchToProps)
)(MainMenu);
`

The code works as intended if I make this change:
`
export default compose(
    connect(mapStateToProps, mapDispatchToProps),
    graphql(viewerQuery, viewerQueryOptions)
)(MainMenu);
`
However, according to the documentation this shouldn't be the case. connect() should be called first (to map state to props) and then be available to graphql(). I will investigate further, but perhaps this should be reopened.

**Comment by advance512** [comment] 2017-08-03 14:00
Did you 
`yarn list | grep redux`
?

**Comment by advance512** [comment] 2017-08-05 12:35
Compose is a really simple function, and its implementation (whether from react-apollo, redux or recompose) I doubt is faulty. But you can try all 3. Does any of them work while the others does not?

I am nearly certain the issue is multiple co-existing versions of Redux. Can you try:
```
yarn install --flat
```
and tell us what happens? Does it solve the issue?

**Comment by Deilv** [comment] 2017-08-09 21:01
At this point I am quite certain that this is not an issue with compose, at least not in my case. `yarn install -flat` makes no difference. However, I did notice that in the documentation example (http://dev.apollodata.com/react/redux.html#using-connect) connect() wraps graphql(). I firmly believe that connect() should be before graphql() in compose() when the later relies on data from the former.

**Comment by Andruschenko** [comment] 2017-10-12 16:10
@Deilv Could you please elaborate on the variable scopes. I'm still confused with the order and would believe that `graphql` call should wrap the `connect` call..

**Comment by Deilv** [comment] 2017-10-12 17:10
@Andruschenko The thing you need to understand is that both functions inside compose are actually factory functions and return a function which is then called. The outside function can provide context to the inside function. This means that connect() **provides** state and dispatch methods to graphql().

Note, however, that **this only matters if graphql requires connect data for its parameters** (store state) to initialize, like in my example. If it does not, then you can call them in any order you want, because all functions within compose will always be available to the original component, which is provided as raw material to the factory.

**Comment by Andruschenko** [comment] 2017-10-13 06:29
@Deilv Thanks for your reply! So does it work like this?: `connect()` and `graphql()` are both called independently with their respective arguments (e.g. `mapStateToProps` and `mapDispatchToProps` in the case of redux). So then when `connect(graphql(MyComponent))` is called with `MyComponent` the selected state is provided to the component returned by `graphql(MyComponent)` via props. 

Is that somewhat correct?

**Comment by TSMMark** [comment] 2017-10-13 23:33
Hey compose experts, anyone know how to annotate a compose block with flow type? I found a simple example [here](http://dev.apollodata.com/react/using-with-types.html#props) and it works but it wouldn't be nearly as concise as `compose`.

We do happen to import `compose` at the top of the [react-apollo flow test](https://github.com/apollographql/react-apollo/blob/master/test/flow.js#L16), but it's unused.

Much appreciated!

**Comment by SpencerCDixon** [comment] 2017-12-07 20:56
@TSMMark I don't see any examples using flow + compose.  Any chance you have a link you could point me to?

**Comment by TSMMark** [comment] 2017-12-07 21:58
@SpencerCDixon the best I could do was 

 1. type as many of the HOCs as possible.
 1. type the variable that gets returned from compose.

```js
type OwnProps = {
  foo: string
}

type StateProps = {
  somethingFromRedux: string
}
const withQuery: OperationComponent<myQuery, OptionDescription<StateProps>, Props> = graphql(query, queryOptions)

const connected: React$ComponentType<OwnProps> = compose(
  connect(mapStateToProps, mapDispatchToProps),
  withQuery,
  injectSheet(styles),
  withWhateverElse,
)(MyComponent)
```

**Comment by SpencerCDixon** [comment] 2017-12-08 00:43
ahhh, I see. Thank you so much for the snippet!! 😄

**Comment by Madgeniusblink** [comment] 2019-11-03 19:59
Hi, 

I keep getting a similar issue: "undefined is not a function (near '...(0, _reactApollo.compose)...')"
the difference is that I am not using redux. I am only using Apollo and react Native.

The issue keeps telling me to look at:
```
export default compose(
    graphql(signinUser, { name: "signinUser"}),
    graphql(createUser, { name: "createUser"})
)(CreateUser);
```
has anyone encounter similar issue?

**Comment by dylanwulf** [comment] 2019-11-03 20:57
@Madgeniusblink The compose utility was recently removed from react-apollo (check the [changelog for v3.0.0](https://github.com/apollographql/react-apollo/blob/master/Changelog.md#300-2019-08-06)
