### ISSUE TITLE
Refetch does not toggle loading

### ISSUE THREAD

**Issue by cannibal** [apollographql/react-apollo#1529] opened 2018-01-08 12:40 UTC
https://github.com/apollographql/react-apollo/issues/321

I am still experiencing this issue and so are some others in the thread. If someone could take a look that would be great :)

It would be nice if there was perhaps a differentiation between loading (the initial fetch) and loading a refetch? - as sometimes - different display logic is used.

I guess you could add a prop - maybe 'loading context' for this quite easily that would not break BC.

**Comment by mbaranovski** [comment] 2018-01-31 09:59
I have the same issue. I thought I can find out about refetch in progress from networkStatus regarding to: [https://www.apollographql.com/docs/react/basics/queries.html#graphql-query-data-networkStatus](url) but networkStatus is not being updated to 4 at all.

**Comment by n1ru4l** [comment] 2018-02-18 23:26
This is how I handle the reloading state:

```js
import { graphql } from "react-apollo";
import { withState, mapProps } from "recompose";
import { flowRight } from "lodash";

const withQuery = graphql(yourQuery, yourQueryOptions);

const withReloadingState = withState("reloading", "setReloading", false);
const withEnhancedRefetch = mapProps(
  ({
    setReloading,
    reloading,
    data: { refetch, ...dataRest },
    ...remainingProps
  }) => ({
    data: {
      reloading,
      refetch: (...args) => {
        if (reloading) {
          return Promise.reject(new Error("Reload already in progress."));
        }
        setReloading(true);
        return reloading(...args)
          .then(result => {
            setReloading(false);
            return result;
          })
          .catch(err => {
            setReloading(false);
            return Promise.reject(err);
          });
      },
      ...dataRest
    },
    ...remainingProps
  })
);

const withReloadingProp = flowRight(withReloadingState, withEnhancedRefetch);

const MyEnhancedComponent = flowRight(withQuery, withReloadingProp)(
  MyComponent
);

```

**Comment by drFabio** [comment] 2018-02-26 19:51
I have the same issue but my biggest problem is that it seems it does not even trigger the props transformation if it was already made

**Comment by n1ru4l** [comment] 2018-02-26 19:57
Can you check out [2.1.0-beta.3](https://github.com/apollographql/react-apollo/releases/tag/v2.1.0-beta.3)? AFAIK this should be fixed there.

**Comment by drFabio** [comment] 2018-03-01 14:40
I tried to build it and couldn't . I'm using a node:9.3.0 image and ran:
```javascript
yarn install
yarn run compile
```
Do I need to do anything fancier?

**Comment by n1ru4l** [comment] 2018-03-01 18:37
You can install it via `yarn add react-apollo@2.1.0-beta.3`

**Comment by drFabio** [comment] 2018-03-11 18:41
@n1ru4l  sorry for the awfully late response. Yes the beta solves it  and make the need for the "@skip" directive does work.

**Comment by bxt** [comment] 2018-12-17 19:38
Is this supposed to be working again? I'm using `react-apollo@2.1.11` and it does not seem to work for me. I can not see which commit was supposed to fix this or which code is supposed to do that. I have a component like this:

```
<Query query={QUERY} notifyOnNetworkStatusChange>
  {({error, loading, data, refetch}) =>
    loading ? (
      <div>loading...</div>
    ) : error ? (<div>
      Sorry, there was an error!
      <button onClick={() => {refetch();}} loading={loading}>
        retry
      </button>
    </div>) : (
      <div>{data.foo}</div>
    )
  }
</Query>
```

And the problem ist, the retry button is not hidden after you clicked it, so it looks as if nothing happens at all and you'd click the button again and again.

The way I test this is I switch Chrome to offline in the dev tools, then load the page, then switch it to slow 3G. I tried downgrading to `2.1.0-beta.3` but then other things in the app break.

**Comment by n1ru4l** [comment] 2018-12-18 08:09
@bxt You could convert the example that I provided to the Render-Prop-API (https://reactjs.org/docs/render-props.html). I have no time to provide an example for you. But the Higher-Order-Component (https://reactjs.org/docs/higher-order-components.html) approach I provided in https://github.com/apollographql/react-apollo/issues/1529#issuecomment-366558023 does still work on the newest apollo-client version.

**Comment by bxt** [comment] 2018-12-18 17:15
Hmmm okay. I tried the versions mentioned in https://github.com/apollographql/apollo-client/issues/1622#issuecomment-418175001 seem like `networkStatus` is never updated to `4` (`console.log` in `render`) for me. So your solution will probably work, but I'd like to avoid it, I'll just remove the retry button :P Maybe I'll find the time later to provide an actual minimal repro for that. For now I'd just wait wether other people even have the problem.

**Comment by hwillson** [comment] 2019-06-15 14:05
This should no longer be an issue with current day `react-apollo`. Let us know otherwise - thanks!

**Closed by hwillson** 2019-06-15 14:05 UTC
