### ISSUE TITLE
[0.4.7] Weird problem with react-hot-loader@3.0.0-beta.2

### ISSUE THREAD

**Issue by HriBB** [apollographql/react-apollo#174] opened 2016-08-28 16:49 UTC
I am seeing some really weird behavior with `react-hot-loader@3.0.0-beta.2` and `react-apollo@0.4.7`.

To make things easier to explain, this is my component hierarchy:
`Admin > Modal > AddAlbum > [Title, Content, Footer]`

`Admin` is my `react-router` `Route`.

If I enhance `AddAlbum` with `graphql()` and put it inside `Modal`, first hot reload does not work. When I change `Title` for example, nothing is updated. However, when I change `Title` again, or change `Content`, hot reload works and components are updated.

If I put `AddAlbum` directly in `Admin`, hot reload works all the time.
If I do not enhance `AddAlbum` with `graphql()`, hot reload works all the time.

I tried to create a reproducible example with `react-hot-boilerplate@next`, but I could not do it. Hot reloading always worked. I suspect that this problem has got something to do with my project setup, but I was not able to pinpoint it. It's really frustrating to work like this, when hot reload works for everything but graphql components.

Is anyone else seeing this issue?

**Comment by HriBB** [comment] 2016-08-28 16:57
I understand that this is a very low-priority bug, if it can even be considered a bug. You can close it if you wish, just wanted to get some feedback from the community.

**Comment by stubailo** [comment] 2016-08-29 06:06
I think it's a pretty good bug to fix, but it's definitely hard to know what's going on without a concrete reproduction.

**Comment by HriBB** [comment] 2016-08-29 08:44
I will try to create a reproducible example, but it might take some time, because I'm pretty busy these days.

**Comment by nickpisacane** [comment] 2016-09-12 02:44
After upgrading from 0.3.x to 0.4.7 (now 0.5.4) I am noticing issues with hot-reloading as well (since the upgrade to 0.4.7). I will look more into this, but it seems to be something odd with the graphql higher order component. The project I am working on is using redux, and react-router. When Components are decorated with `connect`, or `withRouter` from redux, and react-router respectively on top of `graphql`, hot-reloading works. Yet, by itself, hot-reloading doesn't seem to work with graphql.

**Comment by jbaxleyiii** [comment] 2016-09-12 11:09
@HriBB @nickpisacane any chance you could set up a sample repo with the issue? If love to fix this but don't use HMR myself

**Comment by HriBB** [comment] 2016-09-13 05:32
> but it seems to be something odd with the graphql higher order component
@nickpisacane my thoughts as well.

@jbaxleyiii here you go https://github.com/HriBB/react-apollo-rhl-problem Let me know if you need any assistance.

This was a bit of a twilight zone for me :) Really hard to reproduce. Had to keep the folder and route structure for the bug to "work". Please keep in mind that this could be a bug in RHL3 or more likely in my code.

**Comment by zdne** [comment] 2016-10-14 06:26
Hi, 
 I've ran into the HMR problems as well. For me, a component "with data" never hot reloads. See https://github.com/apollostack/apollo-client/issues/764 for detailed description.

**Comment by koz** [comment] 2016-11-03 20:52
Hi,
I'm having this problem with `react-hot-loader@1.3.0` as well. Hot reload doesn't work with any components with `graphql` HOC except if they are decorated with `react-redux` `connect`.

**Comment by HriBB** [comment] 2016-11-04 13:29
@jbaxleyiii maybe it has got something to do with [reassigning components](https://github.com/gaearon/react-hot-loader/blob/next-docs/docs/Known%20Limitations.md#reassigning-components).

**Comment by brunoabreu** [comment] 2017-03-03 16:37
@stubailo @jbaxleyiii can you take a look at my PR?

**Comment by calebmer** [comment] 2017-03-07 22:24
Fixed in `0.13.3` with @brunoabreu’s PR 🎉

**Closed** 2017-03-07 22:24 UTC
Labels: enhancement, help wanted
