### ISSUE TITLE
Query onCompleted not invoked

### ISSUE THREAD

**Issue by johnreynoldsventure** [apollographql/react-apollo#2293] opened 2018-08-18 18:16 UTC
I want a function invoked when the Query completes. The callback function passed to my Query onCompleted should be invoked
 

The onCompleted callback was not invoked (I used a simple console.log function)...
The Query works, the data is available, just not seeing onCompleted

Create a simple Query component - just a graphql query - no Subscription
Set a simple onCompleted={()=>console.log('onCompleted')}

<Query
        query={MEMBER_WITH_EMAIL}
        variables={{ email: `${email}` }} 
        onCompleted={()=>console.log('The Query onCompleted callback was invoked')}>

        {({ loading, error, ...result }) => (
          <div>
            <MemberWithEmailResults
              {...result}
              loading = {loading}
              error = {error}
              email = {email}
            />
          </div>
        )}
      </Query>
 

**Version**

* apollo-client@2.4.0
* react-apollo@2.1.4

**Comment by johnreynoldsventure** [comment] 2018-08-18 20:28
I was able to get this to work using https://codesandbox.io/s/xr6vxpw9xo - so obviously this is just something that I am doing wrong.

Closing the issue

**Comment by yantakus** [comment] 2018-09-03 06:43
I think we should reopen the ticket, because the issue still exists. I'm having it with react-apollo v2.1.11 and in @johnreynoldsventure's example above nothing is logged to the console, so `onCompleted` is not fired.

**Comment by johnreynoldsventure** [comment] 2018-09-03 10:40
I'm reopening this issue in response to yantakus' request... My installation is working fine, but I never really did track down why.

I'm guessing that it's a dependency issue of some sort based on how wonky it seems to be.

**Comment by depiction** [comment] 2018-09-19 15:26
I'm also having this problem using react-apollo ^2.0.1. Using the following code, neither the onCompleted or onError callback functions fire.

`export default compose(
  connect(mapStateToProps, propsMapping),
  graphql(query, {
    options: ({ changeId, currentPage }) => ({
      variables: {
        changeId: changeId,
        pageNumber: currentPage
      },
      onCompleted: (data) => {
        console.log('test')
        console.log(data)
      },
      onError: (error) => {
        console.log(error)
      }
    })
  }),
  networkWrapper,
)(MyComponet)`

**Comment by escapiststupor** [comment] 2018-09-27 05:33
Same here for `"apollo-client": "^2.0.2"` 😢

**Comment by johnreynoldsventure** [comment] 2018-10-03 18:41
I believe that my problem has to do with the react lifecycle of my Query components. onCompleted is not called unless I explicitly use client.resetStore in componentWillUnmount.

I'd like advice from the moderator on whether to close this issue - since it may in fact be react rather than apollo.

**Comment by mattdamon108** [comment] 2018-10-10 00:41
@escapiststupor Exactly same issue. Do you have any progress for this issue?

**Comment by riccoski** [comment] 2018-10-11 12:37
setting notifyOnNetworkStatusChange={true} has worked for me

**Comment by mattdamon108** [comment] 2018-10-12 01:37
Just for information, I resolve my case with using update props. My problem was that it seems <Mutation> component with refetchQueries does not trigger onCompleted callback, So I use update props to callback instead of onCompleted. It does works fine to me. I hope this can help you guys.

**Comment by yantakus** [comment] 2018-10-12 06:39
@mattdamon108 could you please provide an example?

**Comment by mattdamon108** [comment] 2018-10-12 06:52
@yantakus here the code snippets is as below

```
           <Mutation
              mutation={SET_RATE}
              variables={{
                newRate: JSON.stringify(this.state.newRate),
                handler: "add"
              }}
              refetchQueries={[
                {
                  query: GET_RATES,
                  variables: {
                    uid: this.props.USER_ID,
                    queryParams: JSON.stringify({
                      something: here
                    })
                  }
                }
              ]}
              update={() => this._notify("SAVED!", "success")}
            >
              {cudRate => <button onClick={() => cudRate()}>SAVE</button>}
          </Mutation>
```

**Comment by yantakus** [comment] 2018-10-12 08:05
@mattdamon108 The topic is about `Query` component, it doesn't have `update` method. But it has `updateQuery`: https://www.apollographql.com/docs/react/essentials/queries.html#render-prop, maybe we can use it for this purpose. Have to try.

**Comment by mattdamon108** [comment] 2018-10-12 13:56
@yantakus Yes, I knew that this is about Query component issues. But @escapiststupor 's issues is exactly same problem that I had. Like you said, for Query component, `updateQuery` could be a solution.

**Comment by riccoski** [comment] 2018-11-26 18:46
> notifyOnNetworkStatusChange={true}

This actually calls it twice when you visit it a second time (reading from the cache)

**Comment by rosskevin** [comment] 2018-12-28 03:31
I'm not seeing a clear case here or reproduction. If I have it wrong please point me to a codesandbox and I'll reopen.

**Comment by RobiFerentz** [comment] 2019-01-02 15:51
I can definitely add that onCompleted does NOT work on Query component or composed components. I've tried updating all possible dependencies and still nothing.

**Comment by SET001** [comment] 2019-01-03 16:56
same here. It does not work

**Comment by wsmd** [comment] 2019-01-06 22:17
For those following this issue, if the `<Mutation>` component is unmounted as a result of `refetchQueries`, the `onCompleted` prop will never be called.

This is by design, or at least it's intentional:

https://github.com/apollographql/react-apollo/blob/cce02a346643a2cea5547304d56f2e2f05b74fcd/src/Mutation.tsx#L244-L247

The early return above is there to prevent calling `this.setState` when `Mutation` unmounts. In which case, `onComplete` will never be called.

Unless I'm missing something here, by changing the logic of [`onMutationCompleted`](https://github.com/apollographql/react-apollo/blob/cce02a346643a2cea5547304d56f2e2f05b74fcd/src/Mutation.tsx#L244-L261) a little bit, it looks like it's possible to invoke the user-provided `onComplete` even when the `Mutation` unmounts.

**The question really is**: should `onComplete` be called at all after a Mutation unmounts?

> I'm not seeing a clear case here or reproduction.

@rosskevin one example/use-case I have is a logout button that invokes a mutation, which re-fetches a query to propagate this change to the rest of the app (e.g. removing references to the currently logged-in user). On that mutation, we have an `onComplete` to redirect to the login page after both _a successful logout mutation_ AND _a successful refetch_ . With the current implementation, this is not possible because as soon as `refetchQueries` is finished, the logout button will unmount and the redirect will never happen.

I managed to get this to work on a fork, so I'm happy to open a PR!

**Comment by rosskevin** [comment] 2019-01-06 23:02
@wsmd happy to look at a PR - if nothing more than to further the discussion and have a better understanding of the use case.

It is hard to think that an unmounted component would have callbacks called, but I'm open to understanding arguments against that expectation.  PR will help flesh this out.

**Comment by dennishansen** [comment] 2019-01-08 15:45
FYI, a workaround is to use the `mutate` function coming into the render prop, which returns a promise which can then be reacted to with then/finally or doing async/await style. Instead of depending on `onCompleted` to be called for an unmounted component, the promise result can be used.
`mutate({...variables}).then(result => onCompleted(result))`

**Comment by yantakus** [comment] 2019-01-08 15:52
@dennishansen if you see carefully at the title of the thread, it is about `Query` component, not about `Mutation`. Your solution seems to be very useful for `Mutation`, but unfortunately it doesn't help with `Query`.

**Comment by rosskevin** [comment] 2019-01-08 21:54
Accidently closed by merging the PR.

**Comment by wsmd** [comment] 2019-01-08 22:01
For the record, #2710 was addressing https://github.com/apollographql/react-apollo/issues/2293#issuecomment-424964210, https://github.com/apollographql/react-apollo/issues/2293#issuecomment-428593113, https://github.com/apollographql/react-apollo/issues/2293#issuecomment-451780184, and https://github.com/apollographql/react-apollo/issues/2293#issuecomment-429175263...

I'll update the PR description.

**Comment by mcmar** [comment] 2019-04-02 03:02
`onCompleted` is not called when the query is resolved from the cache rather than from network

**Comment by johnreynoldsventure** [comment] 2019-04-02 15:27
Thanks Mike... that makes sense, but I'd suggest that it's somewhat counter intuitive.

I'd expected the method to be invoked whenever the query completes, regardless of where the data is retrieved from and regardless of whether or not the retrieved data matches the previous result.

I haven't looked carefully at the documentation, but suspect that this behavior is not made clear.

**Comment by mschipperheyn** [comment] 2019-04-03 16:16
@mcmar I figured as much. But that makes it a bug, not just counter intuitive.

**Comment by johnreynoldsventure** [comment] 2019-04-03 16:20
@mschipperheyn How about "counter intuitive to the point of being a bug" ;-)

**Comment by mcmar** [comment] 2019-04-03 18:20
@johnreynoldsventure @mschipperheyn I agree 100%. I agree that this is undocumented behavior/bug. I'm not justifying it. Just explaining that's the way it works today and we should open a PR to fix it. The code's in this file for anyone smart/brave/gutsy enough to fix it:
https://github.com/apollographql/react-apollo/blob/master/src/Query.tsx

I implemented a temporary hack/workaround in my own code where I check something 1 time only in the render method. Definitely not ideal, but it did technically fix the issue, so my users are happy

**Comment by mschipperheyn** [comment] 2019-04-03 20:30
you say potato... ;-)

**Comment by ssuvorov** [comment] 2019-05-15 14:35
apollo-client: **2.5.1**
```
<Query 1 fetchPolicy="network-only">
   <Query 2 fetchPolicy="network-only">
     <Query 3 fetchPolicy="network-only">
```
**onComplete** dosn't work on the 2nd and the 3rd queries.
If I replace network policy in 2 and 3 to `fetchPolicy={"cache-and-network"}` - works

**Comment by hwillson** [comment] 2019-06-15 13:08
A lot of the `onCompleted` issues mentioned here have been addressed as of `react-apollo` 2.5.3. If anyone is still encountering issues, please report them in a new issue (ideally with a small runnable reproduction). Thanks!

**Closed by hwillson** 2019-06-15 13:08 UTC

**Comment by FezVrasta** [comment] 2019-10-04 18:10
Having the same issue with `@apollo/react-hooks` :-(

**Comment by mario-jerkovic** [comment] 2019-10-14 17:12
> Having the same issue with `@apollo/react-hooks` :-(

Also facing this issue with `@apollo/react-hooks@^3.1.2`. Did you find any workaround?

**Comment by perevezencev** [comment] 2019-10-17 11:44
Same issue, please reopen this

**Comment by perojas3** [comment] 2019-10-18 12:47
Same issue here.

**Comment by michaeltrim** [comment] 2019-10-22 10:12
Same issue with hooks reopen or new issue?

**Comment by dylanwulf** [comment] 2019-10-22 14:01
@michaeltrim If you can create a runnable reproduction (saved in a github repo or codesandbox) then it might be better to open a new issue. The Apollo team is currently hard at work on apollo-client v3 and probably won't have much time to respond to issues until next month. Your problem will be more likely to be seen if it's in an open issue.

**Comment by Stesm** [comment] 2019-10-29 12:24
`"react-apollo": "^2.5.8"` not work on SSR

**Comment by manish-nx** [comment] 2019-11-16 08:24
I am also facing the same issue for both onError and onCompleted with `@apollo/react-hooks`.
Please reopen the issue.

**Comment by destpat** [comment] 2019-12-09 22:13
I think @apollo/react-hooks call onCompleted only if you provide id for update your localstate
Let me explain with a exemple using  [useLazyQuery](https://www.apollographql.com/docs/react/data/queries/#executing-queries-manually)

#### In this exemple onCompleted is never trigger
```
const GET_MY_FIRSTNAME = gql`
  {
    me {
      firstname
    }
  }
`;
const [getFirstname] = useLazyQuery(GET_MY_FIRST_NAME, {
    onCompleted(data) {
       /* Never call  👎 */
}
```
#### In this exemple onCompleted is trigger

```
const GET_MY_FIRSTNAME = gql`
  {
    me {
      id
      firstname
    }
  }
`;

const [getFirstname] = useLazyQuery(GET_MY_FIRST_NAME, {
    onCompleted(data) {
      console.log(`Hey my name is ${data.me.firstname}  👍` )
}
```

**Comment by mumarm45** [comment] 2020-01-15 10:00
I do not what happing here. Everyone is reporting, it's not working but still, the issue is resolved.  I am also facing the same issue my  "react-apollo": "^3.1.3", and  "react": "^16.12.0",. I'm not using hooks becuase it was old code.

**Comment by github0013** [comment] 2020-03-04 03:36
@mumarm45 

as @destpat explaining
> I think @apollo/react-hooks call onCompleted only if you provide id for update your localstate

if you are missing `id` field in your query, adding `id` will fix the problem. (fixed mine)

**Comment by Jbur43** [comment] 2020-05-28 22:57
What I had to do was install regenerator-runtime and waait and give my component time to update

```
  import regeneratorRuntime from "regenerator-runtime";
  import wait from "waait";

  it("renders component with construct", async () => {
    const root = create(<MockedProvider addTypename={false} mocks={mocks}><Component /></MockedProvider>);

    await wait(500);

    expect(root.toJSON()).toMatchSnapshot();
  })
```
