### ISSUE TITLE
`awaitFetchQueries` does not obey `mutate`'s `defaultOptions`

### ISSUE THREAD

**Issue by justinanastos** [apollographql/react-apollo#2643] opened 2018-12-05 22:22 UTC
The default value set for `awaitFetchQueries` in [`react-apollo`'s `src/Mutation.tsx`](https://github.com/apollographql/react-apollo/blob/master/src/Mutation.tsx#L187-L194) will always override spreading in of `defaultOptions` [`apollo-client`'s `src/ApolloClient.ts`](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/ApolloClient.ts#L305-L310).

Caused by https://github.com/apollographql/react-apollo/commit/924c80e29683d29d7e7b97f95993ad2b33e64273?w=1#diff-bc5fe8407816a086fbe0a9890a115403R202

**Comment by Piwaii** [comment] 2019-04-26 15:35
nothing new here ?

**Comment by Piwaii** [comment] 2019-04-26 15:43
you mean `awaitRefetchQueries` instead of `awaitFetchQueries` ?

**Comment by hwillson** [comment] 2019-09-06 11:48
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!

**Closed by hwillson** 2019-09-06 11:48 UTC
Labels: bug, confirmed, help-wanted

**Comment by tutok** [comment] 2019-12-11 12:43
looks like the issue is still valid

https://github.com/apollographql/react-apollo/blob/91cbdcba17413db3e19ae909c35723e71cd57c38/packages/hooks/src/data/MutationData.ts#L87

**Comment by Borales** [comment] 2019-12-12 09:23
@hwillson even though a lot has changed - the bug is still alive in `3.1.3`.

The reason is that you call `ApolloClient.mutate` function with a predefined value for `awaitRefetchQueries = false` here (lines 87 and 104):

https://github.com/apollographql/react-apollo/blob/b2a0a2528c44610f41d38f59c39970fa52899532/packages/hooks/src/data/MutationData.ts#L78-L111

but when ApolloClient merges the provided `options` param with the `defaultOptions` here:

https://github.com/apollographql/apollo-client/blob/f0c571597c6019e79ba81a81723ad398d4ea16ad/packages/apollo-client/src/ApolloClient.ts#L344

It's too late, it'll always remain `awaitRefetchQueries = false`. And you do this for `query` method the same thing.

I really hope you can fix this, as we use Apollo packages pretty intensively in our project ✌️
