### ISSUE TITLE
[react-apollo] Part of object data is not [re]fetched (or cached) when ID is provided

### ISSUE THREAD

**Issue by DethAriel** [apollographql/react-apollo#1091] opened 2017-09-12 19:38 UTC
This issue has hit me recently, and I tried to come up with the best possible description of a problem, but please update it if you feel that it's misleading.

**Intended outcome:**

I'm trying to get object details through a client network interface. The schema I use is this:
```ts
import { makeExecutableSchema } from 'graphql-tools';

export const typeDefs = `
  type Query {
    currentThing: Thing!
  }

  type Thing {
    id: String!
    thingData: ThingData!
  }

  type ThingData {
    foo: String!
    bar: String!
  }
`;

const resolvers = {
  Query: {
    currentThing: () => ({ id: 'dummy-id' }),
  },
  Thing: {
    thingData: (thing) => {
      return {
        foo: `thing_foo-${thing.id}`,
        bar: `thing_bar-${thing.id}`,
      };
    },
  },
};

export const schema = makeExecutableSchema({ typeDefs, resolvers });
```

As you can see, my resolver returns all the properties of an object at once, but React Components query different properties of an object. The code is quite long, but here's a link to [root component](https://github.com/DethAriel/react-apollo-error-template/blob/not-getting-info-fix/src/App.js) and [sub components](https://github.com/DethAriel/react-apollo-error-template/blob/not-getting-info-fix/src/Thing.js). As you can see, the properties of `"Thing"` are queried at different times, which is controlled by a [`setTimeout` here](https://github.com/DethAriel/react-apollo-error-template/blob/not-getting-info-fix/src/App.js#L12). If I remove this `setTimeout` - both properties are displayed correctly.

When you run the app and wait for 3 seconds for the timeout to run, you'll see that the `foo` property was resolved correctly, whereas the `bar` one was not:
<img width="400" alt="screen shot 2017-09-12 at 12 36 08 pm" src="https://user-images.githubusercontent.com/1497789/30344667-17a29262-97b7-11e7-8a67-3efaf589d665.png">

**Actual outcome:**

I found out that if I rename the object's `id` property to something else - this behavior stops happening, see below for the "fix".

**How to reproduce the issue:**

Reproduction scenario is located [here](https://github.com/DethAriel/react-apollo-error-template/tree/not-getting-info), the "fix" is described [here](https://github.com/DethAriel/react-apollo-error-template/pull/1/files).

**Version**
- react-apollo@1.2.0

**Comment by DethAriel** [comment] 2017-09-12 19:45
Forgot to mention - there's also an error in the console:

```
graphql.js:344 Unhandled (in react-apollo) Error: Network error: Error writing result to store for query query {
    currentThing {
      thingData {
        bar
      }
    }
  }/nStore error: the application attempted to write an object with no provided id but the store already contains an id of Thing:dummy-id for this object.
    at new ApolloError (http://localhost:3000/static/js/bundle.js:37950:29)
    at ObservableQuery.currentResult (http://localhost:3000/static/js/bundle.js:38073:26)
    at GraphQL.dataForChild (http://localhost:3000/static/js/bundle.js:34170:63)
    at GraphQL.render (http://localhost:3000/static/js/bundle.js:34208:34)
    at http://localhost:3000/static/js/bundle.js:27787:22
    at measureLifeCyclePerf (http://localhost:3000/static/js/bundle.js:27067:13)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (http://localhost:3000/static/js/bundle.js:27786:26)
    at ReactCompositeComponentWrapper._renderValidatedComponent (http://localhost:3000/static/js/bundle.js:27813:33)
    at ReactCompositeComponentWrapper._updateRenderedComponent (http://localhost:3000/static/js/bundle.js:27737:37)
    at ReactCompositeComponentWrapper._performComponentUpdate (http://localhost:3000/static/js/bundle.js:27715:11)
```

**Comment by DethAriel** [comment] 2017-10-03 20:26
@jbaxleyiii pinging per bot's suggestion since the issue hasn't been resolved yet

**Comment by DethAriel** [comment] 2017-10-24 22:29
Still valid, @jbaxleyiii

**Comment by DethAriel** [comment] 2017-11-15 18:26
@jbaxleyiii , still an issue

**Comment by rosskevin** [comment] 2018-12-28 20:03
@DethAriel I believe this is more of a question and not a bug or issue with react-apollo.  I see in your reproduction that you have added graphql-tools, which is not this repository.  If you still need help with react-apollo or apollo libraries in general, please checkout the relevant slack channels or post on stackoverflow.

I'm going to close this as it is not a bug with or proposal for react-apollo.

**Closed by rosskevin** 2018-12-28 20:03 UTC
