### ISSUE TITLE
`data.refetch()` has no effect when called from `componentWillMount()`

### ISSUE THREAD

**Issue by bessey** [apollographql/react-apollo#478] opened 2017-02-23 21:34 UTC
## Steps to Reproduce

This is an odd one. To begin, I basically have an iframe component wrapped with a query whose result is a one time use URL, so every time the component gets mounted its surrounding query (which also gets mounted) should fetch a fresh URL. 

Here's my code, reduced to important parts:

```jsx
// COMPONENT
export default class Report extends Component {
  componentWillMount() {
    if(!this.props.data.loading) {
      console.log("REFETCH RAN")
      this.props.data.refetch()
    }
  }

  render() {
    const { lookerDashboard, loading } = this.props.data

    if (loading) {
      return (
        <Loading/>
      )
    }
    console.log(lookerDashboard.url)
    return(
      <Row>
        <Col xs={12}>
          <iframe src={lookerDashboard.url} />
        </Col>
      </Row>
    )
  }
}


// CONTAINER
const query = gql`
  query Report($id: ID!) {
    lookerDashboard(id: $id) {
      id
      url
    }
  }
`
export default compose(
  graphql(query, {
    options: (props) => ({ variables: { id: props.params.id } })
  }),
)(Report)
```

### Buggy Behavior

My intent for this code was that on first rendering of this component, the query will run, the guard in `componentWillMount` will be false, so the refetch won't be executed.
On a subsequent mount of the component, the query has been cached so the guard is true. **This works.** I can see in console "REFETCH RAN" every time i cause the component to unmount / mount (i.e. navigate to / from the page in my React Router app). 

However, the second console.log in `render` does not get a new value. If I look in Redux devtools I can see the new value in the `APOLLO_QUERY_RESULT` action, but **the state remains unchanged**.

Whats more, if I move the `this.props.data.refetch()` to `render()`, or execute it manually in console, things work as expected; the action results in the state changing as expected. Unfortunately if the code is in `render()`, the component mutates its props infinitely, so that's a no go.

### Expected Behavior

I would expect using `refetch()` in `componentWillMount()` to work exactly the same as anywhere else in a components lifecycle. I don't understand why this affects Apollo at all really.

### Version
- apollo-client@0.8.7
- react-apollo@0.11.2

**Comment by bessey** [comment] 2017-02-23 21:36
Just to add, on my server `lookerDashboard.url` is currently set to generate a random hex string on every resolve, so this is 100% a client side issue.

**Comment by jbaxleyiii** [comment] 2017-02-23 21:44
Previously, we didn't create the observable for the query until componentDidMount and just did a sync look up in the store on will mount. With some of the refactoring, this isn't the case anymore so I'm surprised if doesn't work. Would you be able to create a failing test for this?

**Comment by tmeasday** [comment] 2017-02-23 22:20
FTR, I think you can just use `forceFetch` to achieve what you are trying to do here.

---

The react container does:

1. Creates the observable (i.e. calls `client.watchQuery()` returning a `ObservableQuery`) in the constructor

2. [At this point] `componentWillMount` fires (here you are calling `refetch` on the `ObservableQuery`).

3. Subscribes in `componentDidMount` (calls `subscribe` on the observable).

I guess what you are seeing here is a result of: https://github.com/apollographql/apollo-client/pull/1154 -- we don't fire network requests when there are no subscribers. 

I'm not sure if it's an issue or not that a refetch w/ no subscribers is silently dropped; I guess assumptions are made that queries are idempotent. If you want to talk about this more perhaps we can open an issue on `apollo-client` about it?

**Comment by bessey** [comment] 2017-02-24 03:06
Cunningham's Law strikes again. I had a feeling there should be a much easier way to get what I wanted, thanks @tmeasday, that's exactly what I was trying to do, and I forgot about `forceFetch`.

**Comment by tmeasday** [comment] 2017-02-24 03:11
@jbaxleyiii do you think we should still consider this a bug?

**Comment by bessey** [comment] 2017-02-24 03:13
I don't know how feasible it is, but a console warning detecting a refetch being called in `componentWillMount` would have saved me a lot of confusion. That said, I was doing something dumb in the first place!

**Comment by tmeasday** [comment] 2017-02-24 03:17
Hmm, well actually the PR I linked to was about `setVariables`, rather than `refetch`, so I'm no longer sure my explanation makes sense. Refetch simply calls `fetchQuery` a second time: https://github.com/apollographql/apollo-client/blob/master/src/core/ObservableQuery.ts#L197

**Comment by calebmer** [comment] 2017-02-24 15:18
I thought this was fixed in https://github.com/apollographql/apollo-client/pull/1264…

Just as a rule of thumb, in React you should _not_ use `componentWillMount` for network side effects. You should use `componentDidMount`. From the React documentation:

> `componentWillMount()` is invoked immediately before mounting occurs. It is called before `render()`, therefore setting state in this method will not trigger a re-rendering. Avoid introducing any side-effects or subscriptions in this method.
>
> This is the only lifecycle hook called on server rendering. Generally, we recommend using the `constructor()` instead.
>
> …
>
> `componentDidMount()` is invoked immediately after a component is mounted. Initialization that requires DOM nodes should go here. If you need to load data from a remote endpoint, this is a good place to instantiate the network request. Setting state in this method will trigger a re-rendering.
>
> [(source)](https://facebook.github.io/react/docs/react-component.html#componentwillmount)

That said, I do think this is a bug. `refetch` should definitely always trigger a request, and as of `react-apollo@0.11.x` we try to keep an observer around even after the component has been unmounted.

If you have found a solution to your error then go ahead and close this issue. If not it would be excellent if you could reproduce your error with [`react-apollo-error-template`](https://github.com/apollographql/react-apollo-error-template). It would go a long way in helping us find and fix your bug 😊

**Comment by helfer** [comment] 2017-03-21 07:27
Going to close this since it's been a while and a workaround for this particular issue has been found, but a reproduction would still be appreciated!

**Closed by helfer** 2017-03-21 07:27 UTC

**Comment by vaibhav-systango** [comment] 2017-06-19 13:39
@tmeasday 
How to you use forceFetch while using this.props.data.refetch() ?
My store doesn't gets updated

**Comment by tmeasday** [comment] 2017-06-20 04:03
@vaibhav-systango I was suggesting he uses `forceFetch` on the query in the first place, given that it was a match to what he was trying to do.

**Comment by japrogramer** [comment] 2017-12-05 02:27
hello Im trying to get the id from a route but when I try params.id i get an error that it is undefined .. here is what im trying now but I get an undefined returned
http://dpaste.com/08HZ7Q4#line-65

**Comment by zxydaisy** [comment] 2018-02-28 02:18
i use 
```
componentDidMount() {
    const { data } = this.props;
    data.refetch();
  }
```
it works
