### ISSUE TITLE
loading is always True in Query render prop

### ISSUE THREAD

**Issue by Jinnified** [apollographql/react-apollo#1931] opened 2018-04-17 10:59 UTC
I am using query render prop, which been wrapped by a redux render prop, which provides a new query for a new fetch. But when the new fetch been triggered, the loading is always true in the Query render prop.

expected: the loading state should be false once data has been returned
actual: the loading state is always true

It seems that the loading is always true if data is the same? but it's not consistant

apollo-client: 2.2.8
react-apollo: 2.1.3

Code:
```
<WithRedux id={id}>
          {
            ({ d }) => {
              return (
                <Query query={getQuery(d)}>
                  {({ loading, error, data, refetch, networkStatus }) => {
                    console.log('.....networkStatus', networkStatus);
                    console.log('.....loading', loading);
                    console.log('.....data', data);
                    if (error) return <CompPlaceholder cnt={1} template={0} />;
                    if (loading) return <CompPlaceholder cnt={1} template={1} />;
                    if (data && Object.keys(data).length > 0) {
                      if (data.flightInfo && data.flightInfo.length > 0) {
                        return (
                          <DetailFlightInfoCard id={id} data={data.flightInfo} />
                        );
                      }
                      return null;
                    }
                    return null;
                  }}
                </Query>
              );
            }
          }
        </WithRedux>
```

apollo client with batchLink and cache
```
new ApolloClient({
    link: batchLink,
    cache: new InMemoryCache(),
    connectToDevTools: true,
  });
```

**Comment by lucasfeliciano** [comment] 2018-04-17 15:26
Having the same issue here

**Comment by ju5td0m7m1nd** [comment] 2018-04-19 15:48
Facing same problem.
When response data exceeded certain size, it didn't catch the response with data.

**Comment by caseywebdev** [comment] 2018-04-24 12:44
I’m seeing `loading === true` And `networkStatus === 1` when using `skip={true}` which I certainly didn’t expect. No request is actually being sent (which is correct) but the props passed to the render function would suggest one is.

**Comment by powerdefy** [comment] 2018-05-08 11:55
same problems please fix it.

**Comment by nfantone** [comment] 2018-11-30 20:47
Experiencing the same thing here.

![image](https://user-images.githubusercontent.com/476069/49313959-d187f500-f4e0-11e8-9e53-9435f3277951.png)

Above you can see two consecutive queries, both returning an empty array as `data`. First one works fine, switching `loading` flag to `true` and then back to `false. Second one, freezes at `true` and never flips back.

![image](https://user-images.githubusercontent.com/476069/49314023-0eec8280-f4e1-11e8-8ef3-c7add21b81c2.png)

*Network* tab shows both `/graphql` requests completed successfully.

**Comment by nfantone** [comment] 2018-12-01 12:41
Ok, finally discovered the underlying issue. It's [this line](https://github.com/apollographql/apollo-client/blob/86a5824772eb9bbcfdefa40a857efd2fad9d4680/packages/apollo-client/src/core/QueryManager.ts#L613) on `apollo-client` preventing consecutive, identical results from being propagated to the observer. The actual fetched data is [compared here](https://github.com/apollographql/apollo-client/blob/905001e40cfadf841aa5a78aa428ab09f8cdf108/packages/apollo-client/src/core/ObservableQuery.ts#L234).

```
js
          if (observer.next) {
            if (
              previouslyHadError ||
              !observableQuery ||
              observableQuery.isDifferentFromLastResult(resultFromStore) // <- This is causing the issue
            ) {
              try {
                observer.next(resultFromStore);
              } catch (e) {
                // Throw error outside this control flow to avoid breaking Apollo's state
                setTimeout(() => {
                  throw e;
                }, 0);
              }
            }
          }
```

Replacing `observableQuery.isDifferentFromLastResult(resultFromStore)` with just `true` makes the problem go away and `<Query>` re-renders properly.

**Comment by the83** [comment] 2018-12-21 23:57
I'm not using the `<Query />` component, but I'm also having this problem with the `graphql` function if I use `skip()` and have two queries that result in the same data. Remove `skip()`, or remove one of the components that tries to fetch, and it works fine.

**Comment by anied** [comment] 2019-02-20 21:59
I seem to be encountering this same issue even without any cache in place.  Using a `<Query />` with the prop `fetchPolicy="network-only"` passed, if I make a query that is functionally the same as the previous query (for instance, the fields are the same but in a different order) and the response is the same the `loading` argument will come back true after the request has successfully completed.

`apollo-client`: `"2.4.2"`
`react-apollo`: `"2.1.11"`

**Comment by anied** [comment] 2019-02-20 22:09
For what it's worth, [this comment](https://github.com/apollographql/apollo-client/issues/1186#issuecomment-323513354) from [#1186](https://github.com/apollographql/apollo-client/issues/1186) recommends passing the `notifyOnNetworkStatusChange` props, which worked for me.

**Comment by mac-s-g** [comment] 2019-03-10 02:56
same issue
```
react-apollo @ 2.5.2
apollo-client @ 2.5.1
```

`notifyOnNetworkStatusChange` did not work

**Comment by baleeds** [comment] 2019-03-13 19:00
@nfantone you say that changing the line `observableQuery.isDifferentFromLastResult(resultFromStore)` to `true` solves the problem.  How did you end up determining that `apollo-cache-hemes` was the actual source of your issues?

If we know the solution to the problem, could we make a pull request to fix it?

**Comment by city41** [comment] 2019-03-20 19:59
The `notifyOnNetworkStatusChange: true` workaround worked well for us using apollo-client 2.4.8 and earlier. But this workaround no longer works with apollo-client 2.5.1

Using apollo-client 2.5.1, the original issue of the second identical data not causing loading to be set to false returns.

**Comment by nfantone** [comment] 2019-03-20 20:46
@baleeds It's been some time now and I don't really remember details, but yours is a good question. Both approaches worked: replacing `apollo-cache-hermes` and forfeiting `isDifferentFromLastResult` validation. So my guess is that `resultFromStore` ends up being different in each cache implementation, somehow.

**Comment by hwillson** [comment] 2019-03-20 21:39
https://github.com/apollographql/react-apollo/pull/2840 should help address the issues mentioned here, starting from https://github.com/apollographql/react-apollo/issues/1931#issuecomment-471242011. We're hoping to have a new `react-apollo` release published either later today / tomorrow.

**Comment by mac-s-g** [comment] 2019-04-08 05:38
@city41 rolling back to 2.4.1 fixed the issue for now

**Comment by willisplummer** [comment] 2019-05-03 20:39
We just ran into this.. Any updates on a fix?

**Comment by ciulic** [comment] 2019-05-08 17:19
> We just ran into this.. Any updates on a fix?

Could this be the fix for you: notifyOnNetworkStatusChange: true ? I works for me.

**Comment by willisplummer** [comment] 2019-05-08 17:38
@ciulic nope - that didn't fix. ended up having to expose the requestTime on the api so that i could make the responses distinct, which.. is very hacky

**Comment by joeyparis** [comment] 2019-05-10 21:47
Setting `notifyOnNetworkStatusChange` to true worked for me, but I personally wouldn't consider this a solution, just a bandaid

**Comment by escapiststupor** [comment] 2019-05-15 10:52
Confirm setting `notifyOnNetworkStatusChange` to true worked for me.
```
"apollo-client": "^2.5.1"
"react-apollo": "^2.5.5"
```

**Comment by nickhudkins** [comment] 2019-05-15 17:21
Hi @hwillson I saw that (#2840) landed. From your above comment, it seems that maybe this was intended to fix the "infinite loading" when data from the network matched data in the cache. I am currently on `react-apollo: 2.5.5` and `apollo-client: 2.5.1` and still experiencing this behavior. I am able to ensure the re-render by providing `notifyOnNetworkStatusChange = true` to the `<Query>` component.

I am curious what you think about setting that property to true by default when `fetchPolicy="network-only"`. It would seem to me that it would be a rare case to request `network-only` but also not want to be notified about the result of that network call (even if it is the same data in cache).

This is a pretty obscure bug to track down if not for this long standing issue being open, so I wonder if we can have some more sensible defaults.

**Comment by danyhiol** [comment] 2019-05-28 19:40
I'm still facing this problem. But this only occurs when performing 2 queries on the same component using `compose`. This is very annoying.

```
"apollo-client": "^2.6.0"
"react-apollo": "^2.5.6"
```

**Comment by wzard** [comment] 2019-06-14 10:56
I had the same issue with giving skip directive if the variable `$noSessionExists` is true. I accidentally was providing `$sessionExists` variable instead causing the query to be in the loading state forever.

Anyone facing the issue might also want to check if the variable they are passing is okay. I wasted a couple of good minutes trying to think it was a bug. Turns it was me all along. Damn ! 


```
export const GET_COURSE_GLOSSARY = gql`
	query getCourseGlossary(
		$sessionId: String!
		$glossarySkip: Int!
		$limit: Int!
		$uniqueChapterId: String!
		$uniqueTopicId: String!
		$noSessionExists: Boolean!
	) {
		getCourseGlossary(
			sessionId: $sessionId
			skip: $glossarySkip
			limit: $limit
			uniqueChapterId: $uniqueChapterId
			uniqueTopicId: $uniqueTopicId
		) @skip(if: $noSessionExists) {
			total
			glossary {
				id
				term
				definition
				definitionHtml
				summary
				notes
			}
		}
	}
`;
```

**Comment by renanccastro** [comment] 2019-06-14 19:55
I can confirm the issue is hapenning for us too.
"apollo-client": "2.5.1"
"react-apollo": "2.5.5"
and notifyOnNetworkStatusChange works

**Comment by jasonpaulos** [comment] 2019-06-24 20:53
Hi everyone! It seems like some of you are having the same issue as #2899, which was fixed in the most recent versions of react-apollo 2 and 3. Please let me know if your issue has been fixed by this update, and if not, it would be very helpful to us if you could provide a modern reproduction of the issue. Thanks!

**Comment by baleeds** [comment] 2019-07-08 18:01
Updating to `"react-apollo": "^2.5.8"` and `"apollo-client": "^2.6.3"` fixed the issue for me.  Thanks for your help.

**Comment by manoj2166** [comment] 2019-07-12 10:44
> Confirm setting `notifyOnNetworkStatusChange` to true worked for me.
> 
> ```
> "apollo-client": "2.5.1"
> "react-apollo": "2.5.5"
> ```

Work for me on 
"apollo-client": "^2.4.2"
"react-apollo": "^2.1.11"

Thanks @escapiststupor

**Comment by mikevercoelen** [comment] 2019-08-02 10:49
We're having the same problem. Multiple components on our pages are not updating `loading` to true, and it's really annoying.

We're using the latest (2.6.3) version, and our app is built with `@apollo/react-hooks` we now have to revert all our components to non-hooks and use the old version as a workaround to fix it.

Anybody out there that has another solution?

Big problem here...

**Comment by Dalejan** [comment] 2019-08-08 22:43
"apollo-client": "^2.6.3",
    "react-apollo": "^2.5.8"
Still with this issue

`  const { loading, error, data } = useQuery(GET_EVENTS, {
    client: new ApolloClient({
      link: new HttpLink({ uri: `${env.graph}/events` }),
      cache: new InMemoryCache({}),
      name: "Events"
    }),
    notifyOnNetworkStatusChange: true,
    fetchPolicy: "network-only"
  });
  if (loading) return <Aux>"Loading..."</Aux>;
  if (error) return <Aux>Error! {error.message}</Aux>;`

Keeps fetching data and loading is always true

**Comment by hwillson** [comment] 2019-08-09 00:15
The problem outlined in https://github.com/apollographql/react-apollo/issues/1931#issuecomment-517656612 was fixed just before the release of React Apollo 3, in https://github.com/apollographql/react-apollo/pull/3313. I don't think the problems outlined in this issue thread are still an issue in React Apollo 3, but if anyone notices otherwise, and can supply a small runnable reproduction, we'll definitely take a look.

@Dalejan You say you're using `useQuery`, but also that you're using `react-apollo@2` which doesn't have `useQuery`. instead of a code snippet, would you be able to supply a reproduction?

**Comment by Dalejan** [comment] 2019-08-13 17:00
I have updated to "react-apollo": "^3.0.0" but still stuck in loading state when using useQuery. Note: this is not happening whe using <Query> Component, only with hooks. 
![Screenshot from 2019-08-13 11-58-42](https://user-images.githubusercontent.com/20076843/62961121-c7cdc580-bdc1-11e9-8793-1f5e58f76412.png)
In the console, data is empty and loading is always true. But the network response return the expected results in data.

**Comment by hwillson** [comment] 2019-08-17 10:53
@Dalejan any chance you can put together a small runnable reproduction of this?

**Comment by flieks** [comment] 2019-08-18 23:58
@Dalejan i think you mean loading is always true when loading the same query again even when the data is in cache ? (when using cache-and-network). This is normal

**Comment by rbeers** [comment] 2019-09-05 19:17
Same issue as @Dalejan "@apollo/react-hooks": "^3.0.1",

**Comment by hwillson** [comment] 2019-09-06 12:56
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!

**Closed by hwillson** 2019-09-06 12:56 UTC
Labels: reproduction-needed

**Comment by kibray** [comment] 2019-10-15 13:05
Same issue, I had to roolback to version 2.5.8 (from 3.1.2). This fix it for me!

**Comment by abelosorio** [comment] 2020-03-12 17:12
Having the same issue with @apollo/react-hooks version 3.1.3.

cc @RRicardotj
