### ISSUE TITLE
'cache-and-network' fetch policy on loading stage shows unrelated data (w/ testcase)

### ISSUE THREAD

**Issue by lebedev** [apollographql/react-apollo#1342] opened 2017-11-17 13:53 UTC
I made a simple React app with pagination with `cache-and-network` fetch policy. Not a lot of data, 3 pages total. Different pages use the same GraphQL query, but with different variables (offset-based pagination). The issue is that on loading stage it's impossible to determine whether the data in props is a cached version from current `(query-variables)` pair or is it from previous `(query-variables)` pair (same query, different variables).

**Test case.**
[Here.](https://angly-cat.github.io/bug-in-cache-and-network-fetch-policy-in-react-apollo/)

**Intended outcome:**
App starts. Props change over time:
`{ loading: true, data: undefined, variables: varsForPage1 }` ->
`{ loading: false, data: dataForPage1, variables: varsForPage1 }`
Switch to page 2. ->
`{ loading: true, data: undefined, variables: varsForPage2 }` ->
`{ loading: false, data: dataForPage2, variables: varsForPage2 }`
Switch to page 3. ->
`{ loading: true, data: undefined, variables: varsForPage3 }` ->
`{ loading: false, data: dataForPage3, variables: varsForPage3 }`
Switch back to page 2. ->
`{ loading: true, data: dataForPage2, variables: varsForPage2 }` ->
`{ loading: false, data: dataForPage2_updated, variables: varsForPage2 }`

**Actual outcome:**
`{ loading: true, data: undefined, variables: varsForPage1 }` ->
`{ loading: false, data: dataForPage1, variables: varsForPage1 }`
Switch to page 2. ->
`{ loading: true, data: dataForPage1, variables: varsForPage2 }` ->
`{ loading: false, data: dataForPage2, variables: varsForPage2 }`
Switch to page 3. ->
`{ loading: true, data: dataForPage2, variables: varsForPage3 }` ->
`{ loading: false, data: dataForPage3, variables: varsForPage3 }`
Switch back to page 2. ->
`{ loading: true, data: dataForPage2, variables: varsForPage2 }` ->
`{ loading: false, data: dataForPage2_updated, variables: varsForPage2 }`

**How to reproduce the issue:**
[Here's the repo](https://github.com/angly-cat/bug-in-cache-and-network-fetch-policy-in-react-apollo), forked from `react-apollo-error-template`.

**Version**
- apollo-client@2.0.2
- react-apollo@2.0.1

**Comment by yrypka** [comment] 2018-03-13 10:47
I have encountered the same issue. It is reproducible with default fetch policy `cache-first` as well.

Executing a query with a new set of props results in `loading: true` and list of items for a previous set of props until new data arrives.

**Version**

"apollo-client": "^2.2.2"
"react-apollo": "^2.0.4"

The same situation with:

"apollo-client": "2.2.5"
"react-apollo": "2.1.0-beta.3"

**Comment by jason-shen** [comment] 2018-03-17 16:10
I have the same issue with login token did you guys manage to sort this out?

**Comment by yrypka** [comment] 2018-03-20 14:04
@jason-shen No, unfortunately.

**Comment by jason-shen** [comment] 2018-03-20 19:56
@yrypka if you on react-native, have a look at a package call react-native-restart which refresh the whole app clears all the cache on logout, that's what i am doing for now until some solution comes up, its kinda bad of this library, as this is just a simple task, just don't believe there isn't seem to be a way around it, i have try so many ways to solve this but no luck, i have wasted a week of trying to sort this out, in the end i kinda give up

**Comment by yrypka** [comment] 2018-03-20 22:48
@jason-shen It looks like using `data.networkStatus` is a way out.

From docs:

[`data.loading`](https://www.apollographql.com/docs/react/basics/queries.html#graphql-query-data-loading)
> However, just because `data.loading` is true it does not mean that you won’t have data. For instance, if you already have `data.todos`, but you want to get the latest todos from your API `data.loading` might be true, but you will still have the todos from your previous request.

[`data.networkStatus`](https://www.apollographql.com/docs/react/basics/queries.html#graphql-query-data-networkStatus)

> `data.networkStatus` is useful if you want to display a different loading indicator (or no indicator at all) depending on your network status as it provides a more detailed view into the state of a network request on your component than `data.loading` does.

> 2. `setVariables`: If a query’s variables change and a network request was fired then the network status will be `setVariables` until the result of that query comes back. React users will see this when `options.variables` changes on their queries.

So it appears to be intended behavior and the current issue is not a bug.

Taking above into account something like so should be possible to do:
```
graphql('query', {
  options: {
    variables: { ... },
    // Workaround for https://github.com/apollographql/react-apollo/issues/727
    notifyOnNetworkStatusChange: true,
  },
  props: ({
    data: { loading, networkStatus, feed = [], fetchMore },
  }) => ({
    loading,
    feed: networkStatus !== 2 ? feed : [],
    fetchMore: () =>
      fetchMore({
        variables: { ... },
        updateQuery: (prev, { fetchMoreResult }) => {
        },
      }),
  }),
})
```

**Comment by jason-shen** [comment] 2018-03-23 21:25
@yrypka this looks fancy for a simple logout clear the cache haha

**Comment by jason-shen** [comment] 2018-03-23 22:27
@yrypka i had a good look, this would be ideal but, the token is going with the header tag, so that would be another problem to solve

**Comment by jason-shen** [comment] 2018-03-23 22:28
because i have try the updateQuery, before, that still takes the old token, that doesn't access, only in the cache

**Comment by yrypka** [comment] 2018-03-25 16:32
@jason-shen I believe you are looking in the wrong direction. Check this link: https://www.apollographql.com/docs/react/recipes/authentication.html#login-logout

**Comment by jason-shen** [comment] 2018-03-25 17:03
I have follow that but no go, it gives unauth when reserstore

**Comment by hwillson** [comment] 2019-06-15 09:58
It doesn't sound like there is still an issue here, so I'll close this for now. Happy to re-open if needed. Thanks!

**Closed by hwillson** 2019-06-15 09:58 UTC
