### ISSUE TITLE
error state is preserved after prop change

### ISSUE THREAD

**Issue by kdong007** [apollographql/react-apollo#1509] opened 2018-01-03 12:25 UTC
Versions:
"react": "^16.2.0",
"react-native": "^0.51.0",
"react-apollo": "^2.0.4",
 "apollo-client": "^2.0.4",

iOS + iPhone 6

```
const GetVal = graphql(
    gql` {} /* what ever query*/`,
)(
    ({ data }) => <Text>{JSON.stringify(data)}</Text>
)


export class TestPage extends PureComponent {
    state = {
        val: 0
    };

    componentDidMount() {
        SplashScreen.hide();
    }

    render() {

        return (
            <View style={{ flex: 1, backgroundColor: "white", paddingTop: 20 }}>
                <GetVal val={this.state.val} />
                <Button title="xxx" onPress={() => this.setState({ val: this.state.val + 1 })} />
            </View>
        );
    }
}
```

run this code with a apollo client to whatever server and get the initial error. You will get something like 
`{error: xx, loading:false ...}`

Then you tap the button, which changes prop for Graphql component, the data prop becomes 
`{error:null, loading:true. ..}`

I can understand it makes another attempt to fetch data, but the fetch after prop change should also get error state.

**Comment by dbelchev** [comment] 2018-01-11 09:29
@kdong007 Are you sure that it makes a server request at all? In my case it doesn't.

**Comment by AndrewHenderson** [comment] 2018-01-17 23:16
@dbelchev @kdong007 I am finding that the second attempt at fetching does not result in a server request. Essentially, if a component gets an error from a particular resolver, react-apollo will not attempt to reach that resolver again 😕

**Comment by Dremora** [comment] 2018-01-18 18:34
I can confirm I observe the same behaviour in our app.

**Comment by Dremora** [comment] 2018-01-19 12:00
Likely a duplicate of #2687.

**Comment by nfantone** [comment] 2018-02-03 22:09
Yes, it seems to be the same case. 

I'm surprise at the number of issues reporting this very serious problem, people coming out with very detailed reports, replicable test cases and workarounds vs. the total lack of response from the maintainers.

**Comment by hwillson** [comment] 2018-09-18 09:14
Closing as a duplicate of https://github.com/apollographql/react-apollo/issues/1385. Thanks!

**Closed by hwillson** 2018-09-18 09:14 UTC
