### ISSUE TITLE
0.12.0: unmet peer dependency for apollo-client

### ISSUE THREAD

**Issue by nbushak** [apollographql/react-apollo#489] opened 2017-02-27 01:06 UTC
## Steps to Reproduce

npm install latest version

### Buggy Behavior

`npm WARN react-apollo@0.12.0 requires a peer of apollo-client^0.8.0 but none was installed.`

### Expected Behavior

No WARN. 

Need to update https://github.com/apollographql/react-apollo/blob/d52b24787b6716d661e378a93a4a7eed20e67437/package.json#L68 to 0.9.0.

### Version
- apollo-client@0.9.0
- react-apollo@0.12.0

**Comment by helfer** [comment] 2017-02-27 04:36
Thanks @nbushak! It appears that I forgot to update the peer dependency when updating the devDependency. Strictly speaking that's not a bug per se, but I'm fixing it for the next minor version which should come out shortly.

**Comment by calebmer** [comment] 2017-03-01 15:38
Should be fixed in [`0.13.0`](https://github.com/apollographql/react-apollo/blob/master/Changelog.md#0130) 🎉😊

**Closed by calebmer** 2017-03-01 15:38 UTC
