### ISSUE TITLE
Query component unmounts / remounts children on variable update

### ISSUE THREAD

**Issue by brandonmp** [apollographql/react-apollo#1700] opened 2018-02-21 20:07 UTC
**Intended outcome:**
When setting `variables` on the `<Query>` component via props or state, updating those variables should just update the props of the children.

eg if i keep variables in parent state and pass a handler down to `Query`'s children:
```
<Query query={QUERY} variables={this.state.someVariables}>
  {({loading, data, error}) => (<SomeStatefulComponent 
        changeParentStateVar={
                   (newVars) => this.setState(() => ({someVariables: newVars}) )
        }
        data={data} />
)
}
</Query>
```

**Actual outcome:**
The children of `Query` are unmounted and re-mounted, erasing any internally held state and even triggering `willUnmount` / `willMount` lifecycle methods.

It looks like this only happens on a cache miss, though--ie only when `apollo` has to hit the network for a query / var combination.

**How to reproduce the issue:**
set `Query`'s variables to parent state, then update that state. 

add this to render children if you like
```
  componentWillUnmount() {
        console.log('Unmounting');
    }
    componentWillMount() {
        console.log('Mounting');
    }
```
**Version**

* apollo-client@2.0.3
* react-apollo@2.1.0-beta.2

also:
* "next": "5.0.1-canary.2",

**Comment by brandonmp** [comment] 2018-02-25 21:01
reverting to the `graphql HOC` pattern & calling `data.refetch()` works fine

**Comment by brandonmp** [comment] 2018-04-12 01:10
> HOC now uses Query under the hood, so it is broken
oh wow, thanks for pointing that out. i recently upgraded `react-apollo` and somehow didn't notice that

i haven't dug into `react-apollo` src yet but is there any obvious reason why this works this way? no other  renderProp components I use share this behavior

**Comment by jpstrikesback** [comment] 2018-05-04 13:05
This also means refs are destroyed AFAIK

**Comment by bradstiff** [comment] 2018-06-22 16:53
Issue exists even after updating to 2.1.6.

I have a table of paged data with filters at the top. When the filter is changed, the query variables are updated. Everything below the Query component gets remounted / reconstructed. 

Pretty serious, IMO.

**Comment by cranberyxl** [comment] 2018-06-22 17:18
Can you paste your component? If you switch out the parents based on `loading`, then it will change the whole tree downstream.

**Comment by bradstiff** [comment] 2018-06-22 17:41
> If you switch out the parents based on loading, then it will change the whole tree downstream.

That was precisely the issue. Thanks!

**Comment by RxAssim** [comment] 2018-07-19 13:57
Anyone found a fix for this ?

**Comment by gastonmorixe** [comment] 2018-07-31 22:03
One day tracing this issue... any fix?

**Comment by JanMlcoch** [comment] 2018-10-02 14:00
I have same problem. Now i save data from graphql response into component state if data has changed. 
It is terrible solution, but it works. Waiting for fix.

```
renderQuery = () => (
<Query query={QUERY} variables={this.state.someVariables}>
  {({loading, data, error}) => {
    if (data == this.state.data) return <View />;
    setTimeout(() => {
      this.setState({
        myData: data,
      });
    };
    return <View />
  }
}
</Query>
)

renderChildren = () => (
 <SomeStatefulComponent data={this.state.data} />
)

render() {
 return (
  {this.renderQuery}
  {this.renderChildren}
 )
}
```

**Comment by rosskevin** [comment] 2018-12-26 23:37
Ideally, if you would PR a breaking test this would be fantastic - it is most likely to bring attention to the issue.

**Comment by rosskevin** [comment] 2018-12-28 20:17
I think @cranberyxl has this right already - missed that on the first pass:

> If you switch out the parents based on loading, then it will change the whole tree downstream.

**Closed by rosskevin** 2018-12-28 20:17 UTC

**Comment by jdolinski1** [comment] 2019-02-22 11:18
I think this is still an issue, or am i missing something?
```
If you switch out the parents based on loading, then it will change the whole tree downstream.
```
Do you see any logic based on loading in [brandonmp] example up there? This is occuring even if the Query render logic is simple - like always returning some dummy component without any props. The remounting occurs right in the moment when Query variables changes.

**Comment by joshuajhun** [comment] 2019-03-19 20:17
I'm still running into this issue. Is there any reason why the issue is closed?
I have a Filter component that I've built that is working around this issue by using `withApollo` to query the cache and then writing the response to the cache. On reset, we recall the query with a `network-only` fetch policy. 

I'd ideally like for Apollo to do this for me **_without_** remounting my components because of prop changes...

I feel like I'm missing something ¯\_(ツ)_/¯

**Comment by jdgreenberger** [comment] 2019-05-14 18:17
Any update on this?

**Comment by ryantomaselli** [comment] 2019-09-17 04:21
I'm also seeing this behavior...under certain situations the child component is re-instantiated and thus all previously held local state blown away. I can try mitigate this by passing state in as props from the parent component but I still get a flash (which I think is the dom for the child being rebuilt)
