### ISSUE TITLE
Query component use cached data even if no-cache fetchPolicy is set

### ISSUE THREAD

**Issue by JanMlcoch** [apollographql/react-apollo#2841] opened 2019-03-05 16:37 UTC
**Intended outcome:**

Query component should fire new request if it has set fetchPolicy to "no-cache" even if it has same variables. 

**Actual outcome:**

If Query component has set fetchPolicy to "no-cache" but it has same variables like with last render, then this component use cached data.

**How to reproduce the issue:**

https://github.com/JanMlcoch/expo-typescript-graphql-boilerplate/tree/same-variables-query

1. Clone this repo with branch "same-variables-query"
2. Run `$ npm i`
3. Run `$ npm run start`
4. Open in simulator and click on "Graphql" button

Problem is in this file:
https://github.com/JanMlcoch/expo-typescript-graphql-boilerplate/blob/same-variables-query/screens/graphqlScreen/GraphqlScreen.tsx
On line 52 I got cached data in "data" variable.

**Version**

- apollo-client@2.5.1
- react-apollo@2.5.1

**Comment by afenton90** [comment] 2019-04-04 15:56
I've also come across this issue, but came to the conclusion that it was my (and maybe others) misunderstanding of the `fetchPolicy` prop.
For the desired behaviour I think I used [`client.refetch`](https://www.apollographql.com/docs/react/api/apollo-client#ObservableQuery.refetch) instead.
If felt like I shouldn't need to do that at first, but that's where I ended up.

**Comment by escapiststupor** [comment] 2019-06-08 06:10
@afenton90  Would love to hear more about the misunderstanding part. Is there some docs regarding the cache invalidation in `react-apollo` site? I too expect what @JanMlcoch described in intended outcome and wonder if there is a fix other than using `refetch`.

**Comment by afenton90** [comment] 2019-06-09 21:09
@escapiststupor I used this as a reference https://www.apollographql.com/docs/react/api/react-apollo/#optionsfetchpolicy . But my main misunderstanding was that the `Query` component re-fetches at all on a prop change. Whereas the actual behaviour is that it will only fetch on initial mount of the component.

**Comment by jasonpaulos** [comment] 2019-06-27 00:46
Hi everyone. Let me see if I can clear up what's happening here. The Query component with `no-cache` **will** send a request to your server every time it needs to fetch data. This happens if the Query options are changed, you explicitly call `refetch`, or if you specify `pollInterval`.

However, sometimes React events will trigger a re-render of the Query component for a completely different reason, like `this.state.randomNumber` changing in @JanMlcoch's example. This causes the `Query` component to re-render and to call its render proper function, but not poll for new data, since it detects that nothing has changed. This is why you see this line being invoked without a network request: https://github.com/JanMlcoch/expo-typescript-graphql-boilerplate/blob/same-variables-query/screens/graphqlScreen/GraphqlScreen.tsx#L52

So how can you make this example actually refetch data? The simplest way is to have the refresh button live inside of the Query's render prop, like this:
```javascript
renderQueryResult = ({data, loading, refetch}: QueryResult) => {
    // HERE: I got cached data here! You can see there is no request in reactotron
    console.log('New result', data && data.pokemon);
    if (loading) {
      return <Text>Pikachu maxHP: loading</Text>;
    }
    if (data && data.pokemon) {
      return (
        <>
          <Text>Pikachu maxHP: {data.pokemon.maxHP}</Text>
          <TouchableHighlight style={styles.button} onPress={() => refetch()}>
            <Text>Refesh</Text>
          </TouchableHighlight>
        </>
      );
    }
    return null;
};
```

Hopefully this helps clear up any misunderstandings. I'm going to close this issue since I believe everything is behaving as intended. Let me know if there's anything else I can help with.

**Closed by jasonpaulos** 2019-06-27 00:46 UTC

**Comment by JanMlcoch** [comment] 2019-06-27 05:51
Hi @jasonpaulos , thanks for your answer. I am convinced that when i re-render query component with no-cache fetchPolicy component should poll for new data, but I understand, that it is not a problem with cache, but with rendering strategy of react component. And it is true, that bypassing this render strategy according fetchPolicy is not conceptual. 
I will resolve my problem like you did in the example and i consider this issue closed.
