### ISSUE TITLE
What is the good practice to save queries results inside redux store ?

### ISSUE THREAD

**Issue by falkin** [apollographql/react-apollo#803] opened 2017-06-28 11:07 UTC
I'm currently trying to use apollo with redux. Results saved inside the Redux store seems to me to be incorrect. May be my way to of doing things is wrong. 

On my layout component, i have two Queries called inside compose :

```
export default compose(getAuthors, getMasterActions)(Layout);
```

```
const getMasterActions = graphql(MASTER_ACTION_QUERY, {name: 'masterActions'});
const getAuthors = graphql(MASTER_ACTION_QUERY_TEST, {name: 'authors'});
```

My result is correct inside props from Layout component. But now if i m trying to access data  from redux on another component with the state on mapStateToProps. Both results are merged together (masterAction length: 10, author length: 3): 

![sadfadsfasdfasdfasdfasdf](https://user-images.githubusercontent.com/1089835/27632087-f6da1e26-5bfa-11e7-84c8-08a9c7057be9.png)

Inside ROOT_QUERY i have just a list with ids. I understand that Apollo does result caching based on id and here ids are the same but not the __typename.

Why apollo make an union between results ? 

If i remove dataIdFromObject it's better but on data i have one object for each object on Array.  Why i don't find directly two objects (masterAction and author) with full result inside with same struct like i find inside props ?

```
const Client = new ApolloClient({
  reduxRootSelector: state => state.apollo,
  networkInterface: networkInterface,
  dataIdFromObject: o => o.id
});
```

- apollo-client@1.6.0
- react-apollo@1.4.2

**Comment by helfer** [comment] 2017-06-28 18:14
Hi @falkin, the problem is with your `dataIdFromObject` function. If two objects have the same id, they will be merged and written to the same place in the store. You should just remove your declaration of `dataIdFromObject` and Apollo Client will do the right thing (it will use `id` and `__typename`). Because the store is normalized it isn't straightforward to read the results out yourself with Redux. We generally recommend reading them out with the `graphql` HOC again, but if you want something slightly different, you can also use `client.readQuery`, which you can find in the Apollo docs. I hope this helps! 🙂

**Closed by helfer** 2017-06-28 18:14 UTC

**Comment by falkin** [comment] 2017-06-28 21:42
Perfect thank you very much, it was the piece of the puzzle that I didn't understand "how i can interact directly with the cache". I didn't care that Vanilla  JS was different than react section. It's very clear now :)
