### ISSUE TITLE
useSubscription: onSubscriptionData not called on error

### ISSUE THREAD

**Issue by ArnaudBarre** [apollographql/react-apollo#3177] opened 2019-06-25 18:24 UTC
**Intended outcome:**

Display errors using onSubscriptionData option of useSubscription

**Actual outcome:**

onSubscriptionData is never called when an error occurs. (But the return error is populated)

```ts
const { error } = useSubscription<UserInteraction>(
  SUBSCRIBE_USER_INTERACTIONS,
  {
    onSubscriptionData: ({ subscriptionData, client }) => {
      if (subscriptionData.error) notify.error(subscriptionData.error); // never called
      if (!subscriptionData.data) return;
      const event = subscriptionData.data.userInteraction;
      ...
    },
  }
);
console.log(error); // works
```

**Versions**

- System:
    OS: macOS 10.14.5
- Binaries:
    Node: 11.13.0
    Yarn: 1.16.0
- Browsers:
    Chrome: 75.0.3770.100
- npmPackages:
    apollo: ^2.14.0 => 2.14.0 
    apollo-cache-inmemory: ^1.6.0 => 1.6.0 
    apollo-client: ^2.6.3 => 2.6.3 
    apollo-link-http: ^1.5.15 => 1.5.15 
    apollo-link-schema: ^1.2.3 => 1.2.3 
    apollo-link-ws: ^1.0.18 => 1.0.18 
    react-apollo: ^3.0.0-beta.3 => 3.0.0-beta.3
    graphql 14.2.1 (because 14.3.1 fail for codegen)

**Comment by hwillson** [comment] 2019-06-28 14:39
Thanks for reporting this @ArnaudBarre. This is currently by design (and is a carry over from React Apollo 2). `onSubscriptionData` isn't called when an error occurs as we didn't receive any data - we received an error. Is there any reason why using the `error` returned by the `useSubscription` Hook isn't enough?

I'll close this for now since this isn't a bug, but I'm happy to discuss a feature request for this over in https://github.com/apollographql/apollo-feature-requests. Thanks!

**Closed by hwillson** 2019-06-28 14:39 UTC

**Comment by ArnaudBarre** [comment] 2019-06-29 07:59
Thanks for your answer. I think the type of subscriptionData with an optional ApolloError misleading (and maybe the fact that data can be null). 

I would like to have a side effect on error. I could do it simply with useEffect just above the useSubscription, but I think having a onError option will be more consistent with the onSubscriptionData option.

I can create a feature request if it sounds a possible design for you!

**Comment by hwillson** [comment] 2019-06-29 09:26
Please do create a feature request @ArnaudBarre, and we'll continue the discussion there. Thanks!
