### ISSUE TITLE
Best practices for heavy subscriptions react (native) app performance

### ISSUE THREAD

**Issue by Rusfighter** [apollographql/react-apollo#1535] opened 2018-01-09 11:41 UTC
**Intended outcome:**
Non laggy UI with many subscriptions aka apollo cache writes, lets say several incoming subscriptions (5+) per second. Quick summary of my proposal: create graphql HOC that only fetches data but not subscribes to it (like react-graphql) and then have another hoc which is similar to react-redux connect HOC, which subscribes only to the store thus giving more control to connect deeper components to data.

**Actual outcome:**
On react native, the performance is terrible. And because everything runs on one thread (UI + logic), the app stucks and becomes unusable. One of the problems with apollo client (and may be any deep nested data structure) is that a lot of re-renders need to happen when there is a data structure that higher than one level, so if there is a graphql hoc which has several levels, for example in my chat application:

```
const channelTypeQuery = type => gql`
  query GroupChannels  {
    chat{
      id
      channels:{
          ...ChannelFragment
      }
    }
  }
  ${channelFragment}
`;
```
```
export const channelFragment = gql`
  fragment ChannelFragment on Channel {
    id
    topic
    type
    channelEvents(limit: 1) @connection(key: "channelEvents") {
      ...ChannelEventFragment
    }
  }
  ${ChannelEventFragment}
`;
```
Now assume there is a subscription per channel (which is fine i guess in a chat application), The component that executes the `channelTypeQuery` has a list of channels with each channel item in the list the most recent channelEvent. 

Assume some people are typing in several channels which triggers many subscriptions, thus the `channelTypeQuery ` query will be updated and the graphql hoc will trigger re-render on the whole tree. Now you can do some shouldUpdateComponent checks or use pure components but still on a react native app this will cause large performance spikes. My idea: create graphql HOC that only fetches data but not subscribes (aka prefetching and filling the store) and then have another hoc which is similar to react-redux connect HOC, which is listening only to the apollo store thus giving more control to connect deeper components to data thus avoid many unnecessary re-rerenders and checks. And if data is not available just returns an error or null. The idea is similar to readFragment but I cannot find out how to have a sort of 'watchableFragment'.

I don't know if this is currently possible or someone has any good examples/use cases for this scenario.

I hope someone can make sense of this and give some feedback.

Ilija

**Version**
- apollo-client@2.1.0
- react-apollo@2.0.4

**Comment by Rusfighter** [comment] 2018-01-18 10:43
Anyone who comes across the same problem?

**Comment by Evanion** [comment] 2018-01-22 13:11
Just before christmas I wrote a GraphQL server + react client for monitoring live casino tables .. it handled ~50 events/second.

In the beginning I had issues with the browser becoming unresponsive and crashing after a few minutes.

As you alude to, the main issue is the number of DOM updates. The JS thread can actually handle quite many socket events without problem.

My recommendation is that you debounce the UI updates.
I used [react-debunce-render](https://github.com/podefr/react-debounce-render) to debounce the state update up to 0.5 seconds:

```JS
import React from 'react';
import debounceRender from 'react-debounce-render';
import Table from '../../components/Table';

const Tables = ({ tables, loading, error }) => {
  if (loading) {
    return <div>Loading tables</div>;
  }

  if (error) {
    return <div>{error.message}</div>;
  }

  if (!tables) {
    return <div>no tables</div>;
  }
  let players = 0;
  tables.forEach(table => (players = players + table.players));
  return (
    <div>
      <p className="App-intro">
        {players} players online, with {tables.filter(table => table.open).length} tables
      </p>
      <ul className="table-grid">
        {tables &&
          tables
            .filter(table => table.open)
            .sort((a, b) => {
              if (a.name < b.name) return -1;
              return 1;
            })
            .sort((a, b) => a.players - b.players)
            .reverse()
            .map(table => (
              <li key={table.tableId}>
                <Table table={table} />
              </li>
            ))}
      </ul>
    </div>
  );
};

// .filter(table => table.gameType === 'Roulette')
export default debounceRender(Tables, 100, { leading: false, maxWait: 500, trailing: true });

```

**Comment by Rusfighter** [comment] 2018-01-22 22:12
This won't help however in cases with the graphql subscriptions that apollo clients provides, since even if you dont render anything, it still has the same impact. This is duo the fact that the subscriptions are somehow stored/diffed against the current state of the apollo store. On mobile this causes a long ui freezes. However I managed to solve this issue by creating own redux store and use the link interface (so no apollo client in between) to subscribe to my subscriptions. I also use a debounce lodash function to batch the incoming subscriptions to a larger array which is dispatched all at once.

**Comment by clayne11** [comment] 2018-02-15 17:47
I think that part of this is related to a complete lack of query invalidation at the moment in `apollo-client`. See https://github.com/apollographql/apollo-client/issues/2895.

**Comment by Rusfighter** [comment] 2018-02-15 20:50
I have read your issue but in my case the problem is not because the views get re-rendered on new subscription. In my case, the store gets really slow receiving and processing new data when it gets really big and since all the subs are stored in the store (why?) the store can explode in matter of seconds (eg chat app). At the end I just ended up using a normalized redux store with just using the ws link interface to subscribe and process the data.

**Comment by 7ynk3r** [comment] 2018-02-16 19:17
@Rusfighter i'm having the same problem. i think it has to do with caching. i tried both `InMemoryCache` and `HermesCache` with a similar result. my guess is that the normalization process requires a lot of processing.

can you expand a more about your solution using redux & link?

**Comment by Rusfighter** [comment] 2018-02-17 08:53
```
let buffer = [];
      const writeToStore = debounce(() => { // debounce is from lodash
        handlePublishEvent(getCursor(), buffer, resubscribe); // resubscribe is a function which resubscribe if the order of events doesnt match (just for my case)
        buffer = [];
      }, 250);

execute(App.wsLink, {
        query: SUBSCRIPTION_DOC,
        variables: { cursor },
      }).subscribe({
        next: (result) => {
          console.log('subscription result', result);
          if (result && result.data && isArray(result.data.chatEvents)) {
            buffer = buffer.concat(result.data.chatEvents); // I use buffer to cache several updates and write once to store
            writeToStore();
          }
        },
      });
```

**Comment by JBustin** [comment] 2018-03-22 12:55
Not only for native app.
We have a webapp with heavy subscriptions and we have the same problems.

Even if subscription doesn't render anything, sometimes, the interface freezes because a lot of data is pushed at the same time.

**Comment by Rusfighter** [comment] 2018-03-22 14:22
I think the only solution for now is using own data store and use wsLink interface to subscribe to graphql subscriptions. Perhaps use some debounce/throttle functions to avoid performance drops

**Comment by farzd** [comment] 2018-11-15 00:04
Sorry to drag this up. But @Rusfighter have you had any difficulties in keeping the subscription connection alive ? KeepAlive config option seems to ping but fails to hault the disconnect. 

I’m using Apollo subscriptions and the client disconnects when idle after 6 or so minutes. It automatically reconnects when the app comes to the foreground. 

Client also disconnects immediately once app goes to the background

**Comment by lekoaf** [comment] 2019-02-12 09:52
This "crashes" an Electron app as well.

Right now we have a Query that uses `subscribeToMore` to `refetch` the Query on new data. We can get hundreds of updates in a matter of seconds and it totally freezes the UI.

Is there no built in throttling / debounce?

Before we implemented subscription we used `pollingInterval` on the Query every 1 second and that worked fine. We wanted to implement subscription to not do unneeded polling though.

**Comment by lekoaf** [comment] 2019-02-12 15:18
Solved it by debouncing `updateQuery`.
May not be pretty, but it seems to work.

**Comment by SebT** [comment] 2019-02-25 12:00
I did something similar to @Rusfighter's buffer solution and it works fine. But I think Apollo should provide a native way of throttling / debouncing subscription handlers.

Because with the buffer solution, I don't see how we can debounce updateQuery as it's the return value that is important. How did you debounce `updateQuery` in subscribeToMore @lekoaf ?

**Comment by booboothefool** [comment] 2019-05-16 14:21
Also having these problems with React Native + Apollo GraphQL Subscriptions. I am also building a chat application.

1. Websocket connection randomly terminates. Tried all sorts of `keepAlive ` but it is very intermittent and hard to reproduce. Sometimes my messages never come through when clicking a new message notification from lock screen. It seems to always work the first few seconds the app is open, but then does not persist/reconnect later after some user inactivity. @farzd 
2. The main issue in the thread where it seems as if more chatrooms opened and more messages received ends up grinding the app to a halt rather quickly. I checked my render methods and nothing there seems out of the ordinary, so it is probably an issue to how the subscriptions are stored as @Rusfighter said.

I will give @Rusfighter solution of separate Redux store a try.

**Comment by farzd** [comment] 2019-05-17 08:12
@booboothefool so apparently the phones disconnect your subscription connection when idle/locked to conserve battery. Theres no way around this. I have resorted to using polling. You could potentially reconnect when phone comes to foreground. Another alternative would be background tasks - this is available in expo, however its quite hacky and i had to resolve to background location and using that to fire my task

**Comment by booboothefool** [comment] 2019-05-19 04:22
@farzd Thank you for the insight. I am not a fan of polling due to the extra resource usage and unexpected behavior, so I was able to get a solution working for my use case by using the following:

```
    handleAppStateChange = nextAppState => {
            // CONNECTING = 0, OPEN = 1, CLOSING = 2, CLOSED = 3
            if (wsClient.status !== wsClient.wsImpl.OPEN) {
                // To force a reconnect without losing current subscriptions, you need to pass both arguments to close. 
                // .close(false, false) is treated like the connection dropped and a reconnect attempt is made. 
                const isForced = false;
                const closedByUser = false;
                wsClient.close(isForced, closedByUser);
            }
        }
    }

    async componentDidMount() {
        AppState.addEventListener('change', this.handleAppStateChange);
    }

    componentWillUnmount() {
        AppState.removeEventListener('change', this.handleAppStateChange);
    }
```
then
```
wsLink.subscriptionClient.on('reconnected', () => {
  if (__DEV__) {
    console.log('ws reconnected');
    alert('ws reconnected');
  }

  refetchChatQueries();  // here I just stored the refetch() from the relevant queries and call them again
});
```

Now the connection seems reliable, so this solves #2 for me. 👍

But I am still having the issue where when a few new messages are received from a subscription that the app lags out and freezes, so I will continue to try out the separate store method.

**Comment by booboothefool** [comment] 2019-05-19 04:57
I was just able to solve my issue 1) with the app grinding to a halt. Turns out in my case, I did not need a separate store.

I was doing (as seen in the official documentation...):
```
render() {
  ...
  subscribeToMore()
  return <FlatList /> 
}
```

I changed to:
```
class FlatListWithSubscription extends FlatList {
  componentDidMount() {
    this.props.subscribeToMore(...)
  }
}
```
```
render() {
  ...
  subscribeToMore(...)
  return <FlatListWithSubscription subscribeToMore={subscribeToMore} /> 
}
```

Lag and freezing = gone. 👍

**Comment by darrenfurr** [comment] 2019-06-14 17:07
For what it's worth: Ideally the rate throttling & filtering would happen at the server level. For now, I just used lodash/debounce on the updateQuery to apply rate throttling on the client to prevent even the CPU on the tab from just going crazy.

**Comment by hwillson** [comment] 2019-06-15 14:01
We're moving towards only using GH issues in this repo for bugs. There doesn't really seem to be a bug here, so if anyone is interested in opening a feature request for anything in this issue thread, you can do that over in https://github.com/apollographql/apollo-feature-requests. Thanks!

**Closed by hwillson** 2019-06-15 14:01 UTC

**Comment by kaikun213** [comment] 2019-11-18 19:27
I think this is still an issue and would consider this a bug as it has serious performance implications.

I receiving just a couple of messages e.g. 6 in 2-3 seconds each with a high payload (95613 length) and it causes the UI and whole browser to lag and the CPU to go crazy.

This should not happen, I tried both documented ways from Apollo, but neither worked.
Following the example of @Rusfighter , I can at least use the subscriptions. But going around the apollo client does e.g. require me to rewrite my queries and fragments to not have any @client annotations.

I think this should be addressed. If it is considered a feature, then at least a flag which allows to disable normalization or any cache interactions.

**Comment by amirmab** [comment] 2020-01-09 22:20
Can someone clarify how many subscriptions you are talking about, we have a working solution that can handle 100 subscriptions per second as the display will refresh every N seconds.
But I am concern about production and 2,000 burst subscription per second for 10 seconds.
Does anybody deal with that much data?
