### ISSUE TITLE
`skip` as a function is preventing requests from being made

### ISSUE THREAD

**Issue by stephenkao** [apollographql/react-apollo#603] opened 2017-04-06 15:43 UTC
Hey, everyone!  I'm using react-apollo, and I've run into an issue with using the `skip` configuration option as a function -- as opposed to a plain boolean.

## Steps to Reproduce

I can reproduce this by just changing `skip` to a function instead of a boolean.  Also, I'm not sure if this is relevant, but I'm using server-side rendering and using an `IS_BROWSER` variable to force a query to be called **only on the client**.

```js
// works!
export default graphql(whateverQuery, {
  name: 'whateverData',
  skip: !IS_BROWSER;
})(WhateverComponent);

// doesn't work!
export default graphql(whateverQuery, {
  name: 'whateverData',
  skip: () => { 
    console.log(!IS_BROWSER);
    return !IS_BROWSER; 
  }
})(WhateverComponent);
```

### Buggy Behavior
The `skip` function is called, and the `console.log` is called appropriately and prints the correct value of `IS_BROWSER` on both client and server, but there's no request made on the client side.

### Expected Behavior
The `skip` function is called, and the `console.log` is called appropriately and prints the correct value of `IS_BROWSER` on both client and server, but there should be a request made on the client side and `whateverData` should be defined when rendering WhateverComponent.

### Version
- apollo-client@0.8.4
- react-apollo@0.10.0

Any help or guidance would be greatly appreciated! :)

**Comment by helfer** [comment] 2017-04-07 05:07
Hi @stephenkao! Thanks for filing an issue. Would you be able to provide a reproduction using the [error template](https://github.com/apollographql/react-apollo-error-template)? That could help find and fix the issue a lot faster.

**Comment by allpwrfulroot** [comment] 2017-04-17 22:29
I'm seeing something similar with react-apollo 1.0.1, using skip kills the query forever. If I comment out the skip line, the query works (although I can't filter b/c don't have current user ID yet). Skip without any filters does not work either, fairly sure the issue is with skip and not my filter arguments (they work in graphiQL). And using the below sanity check, I find that skip isn't really receiving props or anything at all (returns empty { }):

```
  graphql(GetRecordsQuery, {
    skip: props => console.log('skip received props: ', props),
    .
    .
    .
```

Tried several variations on skip, all fail unless I remove skip entirely. This also hasn't happened to me in previous releases of react-apollo, so I might just use an older release for now?

**Comment by jbaxleyiii** [comment] 2017-05-03 04:59
@allpwrfulroot can you create a reproduction for us to debug?

**Comment by jbaxleyiii** [comment] 2017-05-03 04:59
Since this has been longer than 2 weeks, I'm going to close it but feel free to reopen if its still an issue!

**Closed by jbaxleyiii** 2017-05-03 04:59 UTC
Labels: reproduction needed

**Comment by serranoarevalo** [comment] 2018-06-13 11:52
@stephenkao  Did you solve this?
