### ISSUE TITLE
refetchQueries by name gets cancelled

### ISSUE THREAD

**Issue by sandorvasas** [apollographql/react-apollo#2352] opened 2018-09-05 12:10 UTC
[*] bug

React-Apollo 2.1.11, using the graphql hoc both for mutation and query.

Issue: after running `updateUser()` mutation with `refetchQueries: () => [ 'getUser' ]`, getUser is executed, but gets cancelled immediately (like after ~130ms). 

It was working fine with 2.0.4.

**Comment by ciekawy** [comment] 2018-10-08 23:12
I observed same behaviour with `apollo-angular` 1.1.0 /   `apollo-client` ^2.4.2 / `apollo-link` ^1.2.2

**Comment by JoviDeCroock** [comment] 2018-12-29 11:47
Hey, sorry for the late reply does this issue still persist? I'd like to look into it if it's still relevant.

**Comment by arist0tl3** [comment] 2019-05-31 17:36
@JoviDeCroock 

Hey, sorry for the late response. I can easily reproduce this, although it's pretty deep in my app. I'm on 2.3.2 currently.

The repro steps are basically:

1. Have existing queries by name
2. Run a mutation that refetches by name
3. Run a new query with the same name before the refetches resolve
4. All refetches are cancelled

In my app:

1. Have a current user, with existing queries looking at different properties `CurrentUser`
2. Run a mutation that grants additional permissions to the user
3. Refetch `CurrentUser` queries to update UI
4. Redirect to a permission-based route
5. Route also depends on `CurrentUser` query
6. Route component triggers query
7. Refetches are cancelled midflight

The workaround:

3. Refetch `CurrentUser` queries to update UI
4. Listen for change to `CurrentUser` query or set a timeout, then fire the redirect

Not really sure what the expected behavior is here, but if those initial refetches are asking for different data than the query that cancels them, I'd expect them to resolve?

**Comment by hwillson** [comment] 2019-09-06 11:47
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!

**Closed by hwillson** 2019-09-06 11:47 UTC
