### ISSUE TITLE
Type error in hoistNonReactStatics on react-native Android after upgrade to 1.4.3

### ISSUE THREAD

**Issue by Strayer** [apollographql/react-apollo#832] opened 2017-07-10 12:28 UTC
Since upgrading to 1.4.3 I always get this error when trying to run the app on Android devices and emulators, it doesn't happen with iOS:

<img width="320" alt="grafik" src="https://user-images.githubusercontent.com/310624/28017656-81cedcfa-657a-11e7-89a8-655ee701db8a.png">

I'm doing a simple graphql(mutation)(Component) call that causes this stacktrace.

**Intended outcome:**

No type error.

**Actual outcome:**

Completely broken app with above error message on Android.

**How to reproduce the issue:**

See https://github.com/Strayer/ReactApolloTypeError for an example react-native app that shows this problem. The component itself doesn't really make sense, but the error happens before it even renders, so this shouldn't affect the issue itself.

To reproduce, clone the repo, then:
1. install dependencies with yarn
2. attach an Android device or emulator
3. run `react-native run-android`

The error happens after the JS bundle has been transferred to the device/emulator.

**Version**
- apollo-client@1.7.0
- react-apollo@1.4.3

**Comment by wmcbain** [comment] 2017-07-10 19:54
I'm able to reproduce this using the iOS simulator as well.

**Comment by leethree** [comment] 2017-07-11 10:42
Just got the same error on Android.

**Comment by OscarYuen** [comment] 2017-07-11 15:25
I also got this error 1 hour ago

**Comment by yellowspaceboots** [comment] 2017-07-12 02:21
I have this error as well on android

**Comment by rad182** [comment] 2017-07-12 05:04
getting this error only when using release variant

**Comment by sebas5384** [comment] 2017-07-12 06:42
Similar issue and in iOS 10.1 using the Expo.
Strange thing is that when the "Debug Remote JS" is enabled, the error disappear!

![screen shot 2017-07-12 at 3 37 44 am](https://user-images.githubusercontent.com/97021/28104949-d8de99ba-66b3-11e7-86ff-d4fa68badc9d.png)

**Comment by sebas5384** [comment] 2017-07-12 08:59
Seems like is an incompatibility when in "strict mode", so I added a patch and resolved the issue and it seems that the `hoistNonReactStatics` expects that you pass a blacklist of properties to not access or copy.

I leave here a possible solution:
https://github.com/apollographql/react-apollo/compare/master...sebas5384:fix-strict-mode-error#diff-13fb06b5ebd9e4360f97cefd84b8c762R665

**Comment by vspedr** [comment] 2017-07-12 14:26
I ran into the same error on android yesterday, but somehow my coworkers did not. Not sure if it's related, but I'm on node version 8.1.4 and theirs is on 7.x

**Comment by jbaxleyiii** [comment] 2017-07-12 15:11
hmmm, I wonder what could have caused this with 1.4.3! I'll take a look! Thank you all for the bug report! I'm so sorry this is causing issues! We will get it fixed ASAP!

**Comment by sebas5384** [comment] 2017-07-12 15:31
@jbaxleyiii I think this was caused by this change in the `hoistNonReactStatics`
https://github.com/mridgway/hoist-non-react-statics/pull/24/files#diff-168726dbe96b3ce427e7fedce31bb0bcL18

**Comment by sebas5384** [comment] 2017-07-12 17:17
@jbaxleyiii this appears to be fixed now by @mridgway in the version v2.1.1 of the hoistNonReactStatics
See https://github.com/mridgway/hoist-non-react-statics/issues/32

**Comment by vspedr** [comment] 2017-07-12 20:47
Everything working fine after a clean install. `npm ls hoist-non-react-statics` returns `hoist-non-react-statics@2.1.1` which fixes the issue as stated above

**Comment by nerdmed** [comment] 2017-07-13 09:59
@vspedr  i dont really get what you mean. Even after a clean install v1.4.3 is crashing for us on iOS 9 devices in production. @helfer any chance to hotfix this new bug?

**Comment by vspedr** [comment] 2017-07-13 11:32
@nerdmed the actual issue was fixed in a dependency of `react-apollo`.  If you run `npm ls hoist-non-react-statics` to check which version of that dependency is installed and it's at least 2.1.1, you should be fine. If the error persists, downgrading `react-apollo` to 1.4.2 also worked for me

**Comment by nerdmed** [comment] 2017-07-13 12:09
@vspedr ah ok thanks for your response, will check on that

**Comment by jbaxleyiii** [comment] 2017-07-17 15:51
I will update the dep today and cut a release that will pin that lib to a working point!

**Closed by jbaxleyiii** 2017-07-17 15:51 UTC

**Comment by nerdmed** [comment] 2017-07-17 22:23
great! @vspedr thanks again for your early response worked fine.
