### ISSUE TITLE
SyntaxError: Unexpected end of JSON input with React Native

### ISSUE THREAD

**Issue by lyquocnam** [apollographql/react-apollo#599] opened 2017-04-05 15:35 UTC
here my code
```
import React, { Component } from 'react';
import {
  StyleSheet,
  Text,
  View
} from 'react-native';

import { 
    createNetworkInterface,
    ApolloClient,
    ApolloProvider,
    gql,
    graphql
} from 'react-apollo';

//import { createNetworkInterface } from 'apollo-client';
const networkInterface = createNetworkInterface({
  uri: 'http://localhost:3000/graphql'
});

var client = new ApolloClient({ networkInterface });


class Main extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native! 3
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.android.js
        </Text>
        <Text style={styles.instructions}>
          Double tap R on your keyboard to reload,{'\n'}
          Shake or press menu button for dev menu
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

const query = gql`query {
    danhSachDichVu {
        Name
    }
}`;

const Container = graphql(query)(Main);

const App = () => (
  <ApolloProvider client={client}>
    <Container />
  </ApolloProvider>
)

export default App;
```

and error Stack
```
SyntaxError: Unexpected end of JSON input
    at parse (native)
    at process._tickCallback (internal/process/next_tick.js:109:7)
{ Error: write EPIPE
    at exports._errnoException (util.js:1018:11)
    at Socket._writeGeneric (net.js:715:26)
    at Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at Socket.Writable.write (_stream_writable.js:247:11)
    at Socket.write (net.js:661:40)
    at Socket.Writable.end (_stream_writable.js:480:10)
    at Socket.end (net.js:431:31)
    at Promise.resolve.then.then.then.catch.then.message (D:\dev\react-native\myApp\node_modules\react-native\packager\src\Server\symbolicate\worker.js:35:33) code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
```

More info
![image](https://cloud.githubusercontent.com/assets/8347826/24762315/311acae6-1b18-11e7-8f95-4b3750967512.png)

this only happen on android, ios this not happen

MY PROJECT
https://github.com/lyquocnam/react-native-demo

**Comment by timkendall** [comment] 2017-04-07 04:10
Happening on iOS too for me :/

**Comment by helfer** [comment] 2017-04-07 04:54
Thanks for reporting the issue @lyquocnam. Could you provide more information on when it happens, or maybe even provide a reproduction?

**Comment by lyquocnam** [comment] 2017-04-08 04:02
@helfer it happen when try to load data from graphql server
my project: https://github.com/lyquocnam/react-native-demo/blob/master/src/App.js

**Comment by tudor2it** [comment] 2017-04-17 18:53
It happened to me too. I had to recheck my code and to pay  much attention to the components names used in my application. Instead of  writing the correct name **StackNavigator** in `import { StackNavigator } from 'react-navigation';`  I wrote **StackNavigation**. After this fix it worked fine.

**Comment by jbaxleyiii** [comment] 2017-05-03 04:57
This is most likely a network error or as @tudor2it noted, a bundler issue. Closing for now as we don't parse JSON in react-apollo at all

**Closed by jbaxleyiii** 2017-05-03 04:57 UTC
Labels: reproduction needed

**Comment by stantoncbradley** [comment] 2017-06-01 22:15
I get this error as well.  I am able to dismiss it and everything has loaded correctly

**Comment by reactionic127** [comment] 2018-03-02 19:57
@stantoncbradley 
did you fixed this error at all?

**Comment by stantoncbradley** [comment] 2018-03-16 17:45
@reactionic127 I forget why this was happening. I do know we get this error when we receive html back, which we get from our server when we aren't authenticated

**Comment by HamidReazaNikoonia** [comment] 2018-06-24 08:33
**### is it any News about This ISSUE ??**

i have same Error , to 

|| ReactNative  =>  0.55.4 ||
|| Platform => Android ||

this error happen when i want get Query 
my error details is =>

       Error: Network error: Unexpected end of JSON input
        at  new ApolloError (blob:file:///66ddafa5-4bf7-4771-ba1a-78873fb07bc5:78643)
        at ObservableQuery.currentResult (blob:file:///66ddafa5-4bf7-4771-ba1a-78873fb07bc5:78779)
        at Query._this.getQueryResult (blob:file:///66ddafa5-4bf7-4771-ba1a-78873fb07bc5:89669)
        at Query.render (blob:file:///66ddafa5-4bf7-4771-ba1a-78873fb07bc5:89810)
        at finishClassComponent (blob:file:///66ddafa5-4bf7-4771-ba1a-78873fb07bc5:9687)
        at updateClassComponent (blob:file:///66ddafa5-4bf7-4771-ba1a-78873fb07bc5:9663)
        at beginWork (blob:file:///66ddafa5-4bf7-4771-ba1a-78873fb07bc5:10169)
        at performUnitOfWork (blob:file:///66ddafa5-4bf7-4771-ba1a-78873fb07bc5:12839)
        at workLoop (blob:file:///66ddafa5-4bf7-4771-ba1a-78873fb07bc5:12863)
        at renderRoot (blob:file:///66ddafa5-4bf7-4771-ba1a-78873fb07bc5:12889)

can any body help me !? plz

**Comment by HamidReazaNikoonia** [comment] 2018-06-24 08:50
i also have this ISSUE in Mutation 

    Error: Network error: Unexpected end of JSON input
     at new ApolloError (blob:file:///0ecdb516-c61a-41fa-bc73-8755d17552df:78643)
     at Object.error (blob:file:///0ecdb516-c61a-41fa-bc73-8755d17552df:79565)
     at notifySubscription (blob:file:///0ecdb516-c61a-41fa-bc73-8755d17552df:82269)
     at onNotify (blob:file:///0ecdb516-c61a-41fa-bc73-8755d17552df:82308)
     at SubscriptionObserver.error (blob:file:///0ecdb516-c61a-41fa-bc73-8755d17552df:82363)
     at notifySubscription (blob:file:///0ecdb516-c61a-41fa-bc73-8755d17552df:82269)
     at onNotify (blob:file:///0ecdb516-c61a-41fa-bc73-8755d17552df:82308)
     at SubscriptionObserver.error (blob:file:///0ecdb516-c61a-41fa-bc73-8755d17552df:82363)
     at blob:file:///0ecdb516-c61a-41fa-bc73-8755d17552df:86168
     at tryCallOne (blob:file:///0ecdb516-c61a-41fa-bc73-8755d17552df:16058)


and

  error.graphQLErrors == [ ]    ( return empty Array )

**Comment by HamidReazaNikoonia** [comment] 2018-06-24 08:53
@helfer  hi my friend , i am follow you in Medium and i know you are Perfect 👍 👍 🥇 , please HELP ME , tomorrow  i must release my APP , and i am relay and trust APOLLO

**Comment by stantoncbradley** [comment] 2018-08-27 21:56
running to this issue again on android after upgrading to react-native 0.56.  Everything was working fine before, and no other related changes were made:

"apollo-cache-inmemory": "1.1.10",
"apollo-client": "2.2.6",
"apollo-link-error": "1.0.7",
"apollo-link-http": "1.5.3",
"react-native": "0.56.0",
"react": "16.4.1",

still digging...

**Comment by peterschriever** [comment] 2018-12-11 17:08
I had this issue. I was using apollo-link-http to create a HttpLink, and because I also had a CORS issue, I set `fetchOptions: { mode: 'no-cors' }`. However, no-cors causes javascript to be inable to read the response data. See: https://stackoverflow.com/a/43319482. Eventually I fixed it by configuring my backend to include a `Access-Control-Allow-Origin: *` header.

So check your fetchOptions and fetch library maybe

**Comment by konradZawodnik** [comment] 2019-06-30 13:37
I try to implement apollo client by using graphql
const GET_WP_NEWS = gql`
query GET_WP_NEWS{
  articles(t: Gallery) {
      id
      url
      title
    }
  }
`;
What is wrong in this query. I' ve got error Unexpected end of the input

**Comment by konradZawodnik** [comment] 2019-06-30 13:39
I try to implement apollo client by using graphql

client.query({
  query: gql`
  {
    articles(t: Gallery) {
        id
        url
        title
      }
    }
  `,
})
  .then(data => console.log(data))
  .catch(error => console.error(error));

What is wrong in this query. I' ve got error Unexpected end of JSON input.
