### ISSUE TITLE
Error leads to frozen screen

### ISSUE THREAD

**Issue by eskimoblood** [apollographql/react-apollo#440] opened 2017-01-27 15:54 UTC
## Steps to Reproduce

Make a request with that results with `errors` in the response

### Buggy Behavior

This leads to an infinite rerendering of the components.

### Version
- apollo-client@<0.8.1>
- react-apollo@<0.8.3>

Not sure if this is  bug in react-apollo or just a misconfiguration of our app, so has anyone ever seen this behavoir before?

**Comment by eskimoblood** [comment] 2017-01-27 16:08
After letting the screen stay for some time I actually get an error in the console:

```
apollo.umd.js?cf7b:2188 Error in observer.error 
RangeError: Maximum call stack size exceeded
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at camelize (eval at <anonymous> (http://localhost:8080/bundle/bundle.js:7091:2), <anonymous>:116:14)
    at l (eval at <anonymous> (http://localhost:8080/bundle/bundle.js:10931:2), <anonymous>:6:443)
    at eu (eval at <anonymous> (http://localhost:8080/bundle/bundle.js:10931:2), <anonymous>:67:186)
    at l (eval at <anonymous> (http://localhost:8080/bundle/bundle.js:10931:2), <anonymous>:50:176)
    at pickNestedStyles (eval at <anonymous> (http://localhost:8080/bundle/bundle.js:7091:2), <anonymous>:80:41)
    at hoistModifierStylesRecursive (eval at <anonymous> (http://localhost:8080/bundle/bundle.js:7091:2), <anonymous>:96:140)
    at substyle (eval at <anonymous> (http://localhost:8080/bundle/bundle.js:7091:2), <anonymous>:60:97)
    at eval (eval at <anonymous> (http://localhost:8080/bundle/bundle.js:3581:2), <anonymous>:1:1169)
(anonymous) @ apollo.umd.js?cf7b:2188
(anonymous) @ apollo.umd.js?cf7b:2647
(anonymous) @ apollo.umd.js?cf7b:2644
QueryManager.broadcastQueries @ apollo.umd.js?cf7b:2641
QueryManager.broadcastNewStore @ apollo.umd.js?cf7b:2078
(anonymous) @ apollo.umd.js?cf7b:2687
dispatch @ applyMiddleware.js?ee15:45
(anonymous) @ apollo.umd.js?cf7b:2571
```

**Comment by eskimoblood** [comment] 2017-01-30 13:57
In the end it was a nested component were parent and child made the same request, still unclear why this leads to loop.

**Comment by helfer** [comment] 2017-02-04 00:34
@eskimoblood interesting. I wonder if for some reason the parent component rerenders when the child component's (identical) query returns with an error. If you could provide a minimal reproduction that would really help us solve this issue!

**Comment by eskimoblood** [comment] 2017-02-21 20:20
We had this issue again and it seems my first guess was wrong. So we have a lot of composed request like this:

    compose(request1, request2)(Component)

If I remove the non failing request everything is fine but with one failing one succeed we end up with the eternal rerendering.

**Comment by calebmer** [comment] 2017-02-22 16:25
Could you please create a small test case reproducing the error with [`react-apollo-error-template`](http://github.com/apollographql/react-apollo-error-template)? It would go a long way in helping us debug the error 😊

**Comment by wizardzloy** [comment] 2017-03-09 14:03
We have the same issue in our `Search` component connected to the GraphQL. Cannot find the exact conditions but looks like it also happens when we issue a lot of requests and some of them are failing

**Comment by helfer** [comment] 2017-03-21 07:31
@eskimoblood a reproduction would be much appreciated.

**Comment by jbaxleyiii** [comment] 2017-05-03 04:36
closing as this is older than two weeks without a reproduction. Feel free to reopen if you still have this issue and can create a reproduction

**Closed by jbaxleyiii** 2017-05-03 04:36 UTC
Labels: reproduction needed
