### ISSUE TITLE
no error in mutate function when onError prop provided in Mutation

### ISSUE THREAD

**Issue by zangrafx** [apollographql/react-apollo#2571] opened 2018-11-06 20:42 UTC
**Intended outcome:**
Either mutate function resulting in error or information in docs that you don't get an error in mutate function if you provide `onError` prop.

**Actual outcome:**
Mutate function is not returning error if you provide `onError` prop to `<Mutation>` component.

**How to reproduce the issue:**
```jsx
<Mutation onError={error => console.log('this will trigger', error)} mutation={ADD_TODO}>
      {(addTodo, { data }) => (
        <div>
          <form
            onSubmit={e => {
              e.preventDefault();
              addTodo({ variables: { type: input.value } })
              .then(result => console.log(result)
              .catch(e => console.log('this won't trigger', e);
              input.value = "";
            }}
          >
            <input
              ref={node => {
                input = node;
              }}
            />
            <button type="submit">Add Todo</button>
          </form>
        </div>
      )}
    </Mutation>
```

**Version**

- apollo-client@ (apollo-boost@0.1.20)
- react-apollo@2.2.4

**Comment by OllieJennings** [comment] 2018-11-14 09:06
@zangrafx is this still an issue?

Can you try using error prop in the mutation callback along side data, e.g.

```js
{(addTodo, { data, error }) => ()}
```

**Comment by OllieJennings** [comment] 2019-01-04 16:33
@Kanakala sure, can you post the entire component code etc?

**Comment by Kanakala** [comment] 2019-01-06 11:38
@OllieJennings , here's my component code :
`import React, { Component } from 'react';
import { Form, Input, Select, Row, Col, Button } from 'antd';
import gql from 'graphql-tag';
import { Mutation } from 'react-apollo';

const { Option } = Select;

const CollectionEditForm = Form.create()(
  // eslint-disable-next-line
  class extends React.Component {
    render() {
      const { onCancel, onEdit, form } = this.props;
      const { getFieldDecorator } = form;

      const { username, email, age, department } = this.props.employee;

      return (
        <Form layout="vertical">
          <Row>
            <Col span={12}>
              <Form.Item label="Username">
                {getFieldDecorator('username', {
                  rules: [
                    {
                      required: true,
                      message: 'Please input your Username'
                    }
                  ],
                  initialValue: username
                })(<Input />)}
              </Form.Item>
            </Col>
            <Col span={3} />
            <Col span={6}>
              <Form.Item label="Age">
                {getFieldDecorator('age', {
                  rules: [
                    {
                      required: true,
                      message: 'Please input your Age'
                    }
                  ],
                  initialValue: age
                })(<Input type="number" />)}
              </Form.Item>
            </Col>
            <Col span={3} />
          </Row>
          <Form.Item label="Email">
            {getFieldDecorator('email', {
              rules: [
                {
                  type: 'email',
                  message: 'The input is not valid E-mail!'
                },
                {
                  required: true,
                  message: 'Please input your E-mail!'
                }
              ],
              initialValue: email
            })(<Input />)}
          </Form.Item>
          <Form.Item
            label="Department"
            className="collection-create-form_last-form-item"
          >
            {getFieldDecorator('department', {
              initialValue: department
            })(
              <Select>
                <Option value="OPS">Operations</Option>
                <Option value="FIN">Finance</Option>
                <Option value="TECH">Technology</Option>
              </Select>
            )}
          </Form.Item>
          <Row>
            <Col span={8} />
            <Col span={2}>
              <Button onClick={onCancel} type="primary">
                Cancel
              </Button>
            </Col>
            <Col span={2}>
              <Button onClick={onEdit} type="primary">
                Update
              </Button>
            </Col>
          </Row>
        </Form>
      );
    }
  }
);

const EDIT_EMPLOYEE = gql`
  mutation EditEmployee(
    $_id: ID!
    $username: String
    $email: String
    $age: Int
    $department: AllowedDepartment
  ) {
    editEmployee(
      _id: $_id
      username: $username
      email: $email
      age: $age
      department: $department
    ) {
      username
      email
      age
      department
      _id
    }
  }
`;

export class EditEmployee extends Component {
  handleCancel = () => {
    this.props.showList();
  };

  handleEdit = (e, editEmployee) => {
    const form = this.formRef.props.form;
    form.validateFields((err, values) => {
      if (err) {
        return err;
      }
      const _id = this.props.data.data.getEmployee._id;

      const { username, email, age, department } = values;

      editEmployee({
        variables: { _id, username, email, age, department }
      });

      form.resetFields();
      this.props.showList();
    });
  };

  saveFormRef = formRef => {
    this.formRef = formRef;
  };

  render() {
    return (
      <div>
        <Mutation
          mutation={EDIT_EMPLOYEE}
          errorPolicy="all"
          update={() => {
            console.log('editEmployeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee');
          }}
          notifyOnNetworkStatusChange={true}
          onError={error => {
            console.log(
              'errorrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr',
              error
            );
          }}
        >
          {(editEmployee, { loading, error }) => {
            // if (loading) return <h4>Loading...</h4>;

            return (
              <div>
                <CollectionEditForm
                  wrappedComponentRef={this.saveFormRef}
                  onCancel={this.handleCancel}
                  employee={this.props.data.data.getEmployee}
                  onEdit={e => {
                    this.handleEdit(e, editEmployee);
                  }}
                />
              </div>
            );
          }}
        </Mutation>
      </div>
    );
  }
}

export default EditEmployee;
`

**Comment by kaikun213** [comment] 2019-03-21 13:33
Ran into the same issue. Should be better documented or resolved.

**Comment by geocool** [comment] 2019-03-27 13:30
onError prop is not being called if the error pollicy is set to 'all' as stated in this issue #2590 
A temporary fix is setting the error pollicy to 'none.

**Comment by ferasAbdulazem** [comment] 2019-05-14 06:30
is there any update / workaround for this..
the error object is always undefined in {(mutate, { data, error }) => ()}
and the callback in onError is never called

**Comment by steelx** [comment] 2019-05-27 06:22
im having same issue. Network response has Error object, but `onError` the error is just a flat string message.

**Comment by hwillson** [comment] 2019-09-06 11:47
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!

**Closed by hwillson** 2019-09-06 11:47 UTC

**Comment by geocool** [comment] 2019-09-11 13:50
Hello, I've updated to 3.1 but onError still doesn't work.

**Comment by hwillson** [comment] 2019-09-11 14:39
@geocool Would you mind opening a new issue and including a small runnable reproduction?
