### ISSUE TITLE
MockedProvider doesn't return provided data

### ISSUE THREAD

**Issue by TidyIQ** [apollographql/react-apollo#3012] opened 2019-05-04 10:07 UTC
**Intended outcome:**

I'm following the guide here - https://www.apollographql.com/docs/react/recipes/testing

I'm trying to test the following query:

```
export const QUERY_USERS = gql`
  query users {
    users {
      id
      orgId
      name
      email
      password
      role
    }
  }
`;

export const getUsers = graphql(QUERY_USERS, {});
```

By using this as my test:

```
import React, { Fragment } from "react";
import { render, cleanup } from "react-testing-library";
import { MockedProvider } from "react-apollo/test-utils";

import { getUsers, QUERY_USERS } from "./api";

afterEach(cleanup);

const TestUsersWrapped = ({ data }) => {
  console.log(data);
  return (
    <Fragment>
      {data.users.map(user => {
        return user !== undefined ? (
          <div key={user.id}>
            <p>id: {user.id}</p>
            <p>orgId: {user.orgId}</p>
            <p>name: {user.name}</p>
            <p>email: {user.email}</p>
            <p>password: {user.password}</p>
            <p>role: {user.role}</p>
          </div>
        ) : (
          <div>Error</div>
        );
      })}
    </Fragment>
  );
};
const TestUsersComponent = getUsers(TestUsersWrapped);

const usersMock = [
  {
    request: {
      query: QUERY_USERS
    },
    result: {
      data: {
        users: [
          {
            id: 1,
            orgId: 1,
            name: "Test User",
            email: "test@example.com",
            password: "hashedpassword",
            role: "user"
          }
        ]
      }
    }
  }
];

describe("API: 'users' query", () => {
  it("renders as snapshot", () => {
    const { asFragment } = render(
      <MockedProvider mocks={usersMock} addTypename={false}>
        <TestUsersComponent />
      </MockedProvider>
    );
    expect(asFragment()).toMatchSnapshot();
  });
});
```
This is exactly how the documentation says to do it. It should return an array of all users. **It works fine in production when actually fetching from the server**.

Here's the console.log from when it's used in production:
```
error: undefined
fetchMore: ƒ ()
loading: false
networkStatus: 7
refetch: ƒ ()
startPolling: ƒ ()
stopPolling: ƒ ()
subscribeToMore: ƒ ()
updateQuery: ƒ ()
users: []
variables: {}
__proto__: Object
```
As you can see, it returns the `users` like it's supposed to (which is empty at this stage in production as there are no users stored in our db as yet).

**Actual outcome:**

The test fails as `data` does not return `users` that is clearly provided in the mock within `MockedProvider`.

This is the console.log output from the code above:

```
    console.log api/api.test.tsx:10
      { variables: {},
        refetch: [Function],
        fetchMore: [Function: bound ],
        updateQuery: [Function: bound ],
        startPolling: [Function: bound ],
        stopPolling: [Function: bound ],
        subscribeToMore: [Function: bound ],
        loading: true,
        networkStatus: 1,
        error: undefined }

Error: Uncaught [TypeError: Cannot read property 'map' of undefined]
```

**How to reproduce the issue:**

Use the code provided above.

**Version**

- apollo-client@2.5.1
- react-apollo@2.5.5

**Comment by steelx** [comment] 2019-05-09 04:50
Im also facing same issue

**Comment by steelx** [comment] 2019-05-09 04:55
```
describe('CouponDefinitions', () => {
  const mocks = [
    {
      request: {
        query: getDiscountsColumn,
        variables : {
          queryString: {count: 1}
        }
      },
      result: {
        data: {
          result : {
            items: [{label: 'discount label 1', id: 1}]
          }
        },
        loading: false
      },
    }
  ];

//PASS
  it('should render loading state initially', () => {
    const component = renderer.create(
      <MockedProvider mocks={[]} addTypename={false}>
        <CouponDefinitions />
      </MockedProvider>,
    );

    const tree = component.toJSON();
    expect(tree.children).toContain('Loading...');
  });


//FAIL `result` of undefined error. data = undefined
  it('should link to Coupon definitions details page in Label column', async () => {
    const component = renderer.create(
      <MockedProvider mocks={mocks} addTypename={false}>
        <CouponDefinitions />
      </MockedProvider>
    );
    await wait(0);
    // component.update();

    console.log(component.html()) // 0 nodes error
  });

});
```

The component :

```
export default () => (
    <Query query={getDiscountsColumn} variables={{ queryString: {count: 500} }}>
      {
        ({loading, data}) => {
          if (loading) {return (<div>Loading...</div>);}

          const items = data.result.items;// data is undefined
          return (<CouponDefinitionsDumbComponent items={items} />)
        }
      }
    </Query>
);
```

**Comment by byronicone** [comment] 2019-05-29 14:40
I have the same issue for a mutation.  My queries work fine, but my mutations are never called as expected.

**Comment by colinlmcdonald** [comment] 2019-06-04 23:37
@TidyIQ I'm not sure why that is working in production, but `data` is set to undefined when in a loading state.

**Comment by tylervanbrocklin** [comment] 2019-07-18 17:33
Also facing this issue.

**Comment by erikeide** [comment] 2019-07-25 05:12
@TidyIQ - have you tried waiting for the final state, in the docs, if you scroll down a bit, you'll see you need to wait for the MockedProvider to return data:

https://www.apollographql.com/docs/react/recipes/testing/#testing-final-state

**Comment by chrisbchrist** [comment] 2019-07-31 19:36
I'm facing this issue even after trying several methods to wait, both waait and wait-for-expect still either return a component that's stuck on loading or with errors.  We're having a hard time figuring out what the issue is, as everything works fine with an actual API and we're using the exact response the server was returning as our mock.

**Comment by erikeide** [comment] 2019-07-31 22:28
@chrisbchrist - if you're getting an error from the query, then it seems it's tried to run it - what is the error message?

The usual one seems to be the query that executes during the test, doesn't quite match any of those configured in mocks array given to the MockedProvider, such as one of the variables passed to the query

**Comment by chrisbchrist** [comment] 2019-07-31 23:32
It was the 'No more mocked responses for the query' error.  We were able to sort it out, one of our parameters was being coerced into a string, so the problem was on our end.  Although I would humbly suggest some more verbose error warnings when the data result is not matching up with the query/schema, it was a lot of trial and error to track down the source of the problem.  Keep up the good work!

**Comment by developer239** [comment] 2019-08-13 14:11
I believe it is fixed now. A working example is here: https://github.com/developer239/react-apollo-graphql

**Comment by hwillson** [comment] 2019-09-06 12:04
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!

**Closed by hwillson** 2019-09-06 12:04 UTC
