### ISSUE TITLE
Typescript: ChildProps.data should not be optional

### ISSUE THREAD

**Issue by choffmeister** [apollographql/react-apollo#1083] opened 2017-09-10 16:07 UTC
**Intended outcome:**

The typescript definition of `ChildProps.data` should be non-optional, since according to the documentation (http://dev.apollodata.com/react/api-queries.html#graphql-query-data) the `data` property has a `loading`/`error` subproperty to check for completion/errors.

**Actual outcome:**

The actual type definition is

```js
export declare type ChildProps<P, R> = P & {
    data?: QueryProps & R;
    mutate?: MutationFunc<R>;
};
```

forcing users to always check if `data` is defined before being able to access `data.loading` or other properties.

One example from the documentation

```js
render() {
  const { data: { loading, error, todos } } = this.props;
  if (loading) {
    return <p>Loading...</p>;
  } else if (error) {
    return <p>Error!</p>;
  } else {
    return (
      <ul>
        {todos.map(({ id, text }) => (
          <li key={id}>{text}</li>
        ))}
      </ul>
    );
  }
}
```

would fail if using typescript because of `data?`.

**Version**
- apollo-client@1.4.0
- react-apollo@1.4.15

**Comment by leoasis** [comment] 2017-09-25 20:09
I'd like to add to this one that instead of data being optional, it is the results that should be optional, in the `ChildProps` case, `P` should have all nullable fields (for the case where they are loading).

**Comment by choffmeister** [comment] 2017-09-25 20:33
What you call `Nullable<T>` should be typescripts `Partial<T>` I guess.

**Comment by leoasis** [comment] 2017-09-25 20:35
Yeah, duh, good call! haha

**Comment by choffmeister** [comment] 2017-09-25 20:53
Did look up here https://www.typescriptlang.org/docs/handbook/advanced-types.html. Actually both `Nullable` and `Partial` exist (did only know about `Partial`). Still if I recall correctly the unloaded props are `undefined`, so `Partial` should be the correct one. If there are now objections I would create a PR tomorrow for that.

**Comment by Jontem** [comment] 2017-10-02 08:25
Looks as this was merged and included in version 1.4.16 but `data` is still optional but now with `Partial<R> ?

```typescript
export type ChildProps<P, R> = P & {
  data?: QueryProps & Partial<R>;
  mutate?: MutationFunc<R>;
};
```
https://github.com/apollographql/react-apollo/blame/3e245205097d427daaac7cb89c0f97eea78032ae/src/types.ts#L70

**Comment by leoasis** [comment] 2017-10-11 21:46
Yeah, I think the reason it was set back to optional is that since the HOC is used for both queries and mutations, and since currently there's no way to tell Typescript how the HOC will act like, the type definitions need to allow both to be optional, since for queries you'll get `data`, and for mutations you'll get `mutate`.

**Comment by jurosh** [comment] 2017-11-04 16:53
@leoasis Maybe would be good to create another type for props with queries only Eg. `ChildQueryProps<ResponseType>` where types would be stronger, but not optional. Otherwise it's really complicated to work with those types in components.

Also this official example doesn't work now because of optional typings https://www.apollographql.com/docs/react/features/static-typing.html#classes-vs-functions

**Comment by leoasis** [comment] 2017-11-06 17:56
@jurosh yeah the problem with that is that by design the `graphql` HoC works for both queries and mutations, and the decision to act as one of those is determined dynamically by inspecting the graphql document being passed in. If it has a mutation operation, then it acts as a mutation container, otherwise as a query container. This is not possible for Typescript to know in advance, which leads to these types that have everything optional. I think maybe the types could be improved a bit more so that at least the developer can specify if the types for the container should be for querying or for mutating, with a type parameter for example.

**Comment by rosskevin** [comment] 2017-12-13 15:22
#1369 offers a refined test case that should be considered, though it is a duplicate of this issue.  Actually, perhaps since it is succinctly stated perhaps we should close this one and keep that one open?

**Comment by rosskevin** [comment] 2017-12-18 17:00
I'm closing this in favor of #1369 - it has a succinct test case.  2.1 roadmap looks like we'll have discrete components so this won't be a problem.  Please follow #1369.

**Closed by rosskevin** 2017-12-18 17:00 UTC
Labels: no-recent-activity
