### ISSUE TITLE
use compose catch errors when props errors is not working?

### ISSUE THREAD

**Issue by webmobiles** [apollographql/react-apollo#1363] opened 2017-11-29 09:41 UTC
I'm using apollo 1.9.3

I have a form that loads a lot of apollo client query, if there are errors at the start loading this query,I can "catch" them from props and show the error. but it's not working,   when the user click on 'save button' and the server call the mutation, I have for purpose produce the errors to see the behavoiur the app.

 the code for mutations, another code for query they get ok the error:
 
```
     if (this.props.mutationData) { 
        const { mutationData: { loading, error } } = this.props;
```

on the browser I get:

```
Uncaught (in promise) Error: GraphQL error: SequelizeDatabaseError: invalid input syntax for uuid: ""
    at new ApolloError (ApolloError.js:34)
    at QueryManager.js:129
    at <anonymous>

```

my server give:

`Error: SequelizeDatabaseError: invalid input syntax for uuid: ""\n    ....`

I ask myself if I must to add the catch here on the compose ?? where exactly ?

future: must I already to migrato to apollo 2 to get a better errors management or less bugs?

```

const withCrudFormContainer  = withCrud(FormContainer,tableCrud,action);

const ComponentWithMutations = compose(
graphql(defQls.registration.View, {
    name: 'queryData',
    options: props => ({
      variables: { id: props.match.params.id },
      fetchPolicy: 'network-only',
    }),
  }),graphql(defQls.registration.Update, {
    name: 'mutationData',
    options: props => ({
      variables: { id: props.match.params.id },
      fetchPolicy: 'network-only',
    }),
  }),graphql(defQls.registration.Delete, {
    name: 'mutationDelete',
    options: props => ({
      variables: { id: props.match.params.id },
      fetchPolicy: 'network-only',
    }),
  }),
  graphql(defQls.customer.List, {
    name: 'list_customer',
    options: props => ({
      fetchPolicy: 'network-only',
    }),
  }),
  graphql(defQls.tour.List, {
    name: 'list_tour',
    options: props => ({
      fetchPolicy: 'network-only',
    }),
  }),
  graphql(defQls.tourroom.List, {
    name: 'list_tourroom',
    options: props => ({
      fetchPolicy: 'network-only',
    }),
  }),
  graphql(defQls.paymentstatus.List, {
    name: 'list_paymentstatus',
    options: props => ({
      fetchPolicy: 'network-only',
    }),
  }),
  graphql(defQls.registrationstatus.List, {
    name: 'list_registrationstatus',
    options: props => ({
      fetchPolicy: 'network-only',
    }),
  }),
  graphql(defQls.confirmationstatus.List, {
    name: 'list_confirmationstatus',
    options: props => ({
      fetchPolicy: 'network-only',
    }),
  }),
  graphql(defQls.user.List, {
    name: 'list_user',
    options: props => ({
      fetchPolicy: 'network-only',
    }),
  }),
  graphql(defQls.user.List, {
    name: 'list_user',
    options: props => ({
      fetchPolicy: 'network-only',
    }),
  }),
)(withRouter(withCrudFormContainer));


const mapStateToProps = (state) => {
  return {
    myState: state,
  };
};

const ComponentWithDataAndState = connect(
  mapStateToProps ,
  {
    appSubmitStart,
    appSubmitStop
  },
)(ComponentWithMutations);

export default ComponentWithDataAndState;

```

**Comment by hwillson** [comment] 2018-09-18 02:01
React Apollo has changed quite a bit since this issue was posted. If you're still encountering this issue with a modern version of React Apollo, please post back with a small runnable reproduction demonstrating this issue. Closing for now - thanks!

**Closed by hwillson** 2018-09-18 02:01 UTC
