### ISSUE TITLE
Query doesn't re-render after local state mutation

### ISSUE THREAD

**Issue by nilshartmann** [apollographql/react-apollo#2099] opened 2018-06-12 20:10 UTC
**Intended outcome:**

My local (`@directive`) mutation adds a new element to the cache. The query that selects those items should be re-run to display the new value.

**Actual outcome:**

After the mutation is run, the cache is updated correctly. I can observe this in both Cache view and GraphiQL in apollo dev tool. But the `Query` component doesn't rerender.
If instead of *adding* an object to the cache during the mutation, I *update* an existing object in the cache, using the same resolver, Mutation and Query, everything works as expected. (The resolver insert-or-update behavior)

**How to reproduce the issue:**

Example Mutation resolver:
```js
const updatePerson = (_, { personId, name }, { cache }) => {
  const query = gql`
    query GetPersons {
      persons @client {
        id
        name
      }
    }
  `;
  const previous = cache.readQuery({ query });

  // the object we want to add to the cache (or update if already in there)
  const newPerson = {
    __typename: "Person",
    id: personId,
    name
  };

  // check if we have already that person, then update otherwise add it later
  let found = false;

  const newPersons = previous.persons.map(prevPerson => {
    if (prevPerson.id === personId) {
      found = true;
      return newPerson;
    }

    return prevPerson;
  });

  if (!found) {
    newPerson.push(newPerson);
  }

  cache.writeData({
    data: {
      persons: newPersons
    }
  });
  return newPerson;
};

```

Component:
```js
const GET_PERSON_QUERY = gql`
  query GetPersonQuery($personId: ID!) {
    person: person(personId: $personId) @client {
      name
    }
  }
`;

const UPDATE_PERSON_MUTATION = gql`
  mutation UpdatePersonMutation($personId: ID!, $name: String!) {
    updatePerson(personId: $personId, name: $name) @client {
      name
    }
  }
`;
export default class PersonFormController extends React.Component {
  render() {
    const { personId } = this.props;
    return (
      <Query query={GET_PERSON_QUERY} variables={{ personId }}>
        {({ loading, error, data, client }) => {

          // This code is executed, when an existing object in the Cache
          // is modified using the mutation below
          // It is NOT executed, when the mutations ADDS a new object to
          // the cache

          if (loading) {
            return <h1>Loading></h1>;
          }
          if (error) {
            return <h1>Error</h1>;
          }

          return (
            <PersonForm
              onPersonChange={(author, comment) => {
                client.mutate({
                  mutation: UPDATE_PERSON_MUTATION,
                  variables: {
                    personId,
                    name
                  }
                });
              }}
            />
          );
        }}
      </Query>
    );
  }
}

```

**Version**

* react-apollo@2.1.4

**Comment by wmarino13** [comment] 2018-09-26 16:14
Hey i have the same issue, nothing yet? it's been 3 months since this, any update or another solution to it? Thanks

**Comment by DiederikvandenB** [comment] 2018-10-03 10:54
Same issue here!

**Comment by JeremyGreaux** [comment] 2018-10-09 12:40
Same issue here !

**Comment by Adzz** [comment] 2018-10-12 11:46
Same issue here!

**Comment by rosskevin** [comment] 2018-10-18 16:47
I can confirm this issue.  It would be excellent if we can get a PR with a breaking test.  I'm not sure if this is in react-apollo or cache/apollo-client, but we are seeing it now.  

Strangely enough, this just cropped up in a failing feature test, and it was working previously.  It is in an area untouched by our code so I tend to theorize that an update to react-apollo, apollo-client etc may have exposed it.  I'll see what I can find, but I have limited time and may have to workaround it by manually triggering an update to my component.

If someone else can PR a test case, please ping me and I'll try to help.

**Comment by rosskevin** [comment] 2018-10-18 17:41
I have confirmed that the react-apollo `Query` subscription doesn't receive a callback.  This subscription is created from the `ObservableQuery` provided by `this.client.watchQuery(opts)`.  Therefore this is not a react-apollo issue, just manifesting here.

Is there a matching issue in apollo-client?

**Comment by rosskevin** [comment] 2018-10-18 18:06
/related https://github.com/apollographql/apollo-client/issues/2415 with reproduction https://github.com/apollographql/apollo-client/issues/2415#issuecomment-420356987

Looks like @dajust is using the `updateQuery` provided by `Query`.  I am not sure yet if this is the intent or if the issue is still a bug.

**Comment by rosskevin** [comment] 2018-10-18 19:18
I tried both using `updateQuery` and the workaround listed in https://github.com/apollographql/apollo-client/issues/2415`client.queryManager.broadcastQueries()` and neither made the `Query` re-render.

**Comment by Dajust** [comment] 2018-10-18 20:36
I'm not sure why `updateQuery` shouldn't work for you. Can you share your code?

**Comment by rosskevin** [comment] 2018-10-18 20:55
@Dajust 

```typescript
        await client.mutate<RemoveContactMutation>({
          mutation: GQL.RemoveContactMutation,
          update: (proxy, fetchResult) => {
            if (!fetchResult.data) {
              throw new Error(`Expected data but received ${fetchResult}`)
            }

            updateQuery(previousResult => {
              const { currentUser } = previousResult
              currentUser!.contacts = currentUser!.contacts.filter(c => c.id !== contact.id)
              return previousResult
            })
          },
          variables: { id: contact.contactBook.id, contactId: contact.id },
        }),
```
I also tried  to alter the `return { ...previousResult }` to avoid object equality issues but it did not work.

**Comment by Dajust** [comment] 2018-10-18 22:17
@rosskevin I'm not entirely sure how `client.mutate` works. But I think the `update` function _should_ return the actual mutation, the **update**. Anyways, `updateQuery` shouldn't be used inside the `update` function as both `client.mutate` and `updateQuery` are targeting the same results with different approach.

Try replacing the entire `client.mutate` aproach with `updateQuery` since both are doing the same thing and are not dependent on each other. :crossed_fingers:

**Comment by rosskevin** [comment] 2018-10-19 02:14
@dajust `client.mutate` makes a change on the server. The `update` provided to `mutate` is specifically intended for situations where you need to update the cache after mutating data on the server.  https://github.com/apollographql/apollo-client/blob/master/docs/source/basics/mutations.md#updating-the-cache-after-a-mutation

**Comment by mthomasuk** [comment] 2018-10-30 10:00
I think I'm having a similar issue - it's only just appeared after reinstalling from npm, previous cache updates would cause react to re-render, but now, although apollo-cache IS being updated, these changes are not being flushed to react for whatever reason

apologies for not being more descriptive, here's my package.json in case it helps:
```
    "dependencies": {
        "apollo-cache-inmemory": "1.3.7",
        "apollo-client": "2.4.4",
        "apollo-fetch": "0.7.0",
        "apollo-link": "1.2.3",
        "apollo-link-core": "0.5.4",
        "apollo-link-error": "1.1.1",
        "apollo-link-http": "1.5.5",
        "apollo-link-state": "0.4.2",
        "apollo-link-ws": "1.0.9",
        "apollo-upload-client": "8.1.0",
        "date-fns": "1.29.0",
        "graphql": "14.0.2",
        "graphql-tag": "2.5.0",
        "graphql-tools": "2.5.1",
        "lodash.isequal": "4.5.0",
        "mobile-drag-drop": "2.2.0",
        "qrcode.react": "0.7.2",
        "react": "16.4.2",
        "react-apollo": "2.2.4",
        "react-calendar": "2.16.1",
        "react-dnd": "2.5.4",
        "react-dnd-html5-backend": "2.5.4",
        "react-dom": "16.4.2",
        "react-inlinesvg": "0.7.4",
        "react-router": "4.2.0",
        "react-router-dom": "4.2.2",
        "react-virtualized": "9.20.1",
        "react-waypoint": "8.0.0",
        "subscriptions-transport-ws": "0.9.14",
        "uuid": "3.1.0",
        "whatwg-fetch": "2.0.3"
    },
```

**Comment by SMJ93** [comment] 2018-10-30 14:12
We ran a fresh install from `npm` (we have no lock file) and are getting the same issue. It was working fine yesterday.

We have several mutations updating the cache in our project which all used to re-render as expected, but now one of them don't re-render 🤦‍♂️ .

Here are our versions:

```
    "apollo-boost": "0.1.18",
    "apollo-link-context": "1.0.9",
    "apollo-cache-inmemory":"1.3.7",
```

**Comment by rosskevin** [comment] 2018-10-30 14:21
This is an upstream bug: https://github.com/apollographql/apollo-client/issues/2415  

Please comment there unless you have a workaround to post here.

**Comment by SMJ93** [comment] 2018-10-30 14:24
Thanks @rosskevin

**Comment by booboothefool** [comment] 2018-11-14 22:39
I needed the functionality: filters are stored in local client state `FILTER_QUERY`-> user updates filters `UPDATE_FILTER_MUTATION` -> a different query should refetch with the new filters `LIST_QUERY`

I was able to get the functionality I wanted by nesting <Query>, however it seems to slow my app down until it crashes: https://github.com/apollographql/react-apollo/issues/2589

```
    return (
      <Query query={FILTER_QUERY}>  // when this is updated
        {({ data, client }) => {
          if (!data.filter) {
            return <Text>Loading...</Text>;
          }

          return (
            <Query
              query={LIST_QUERY}  // this appears to properly re-render, then continuously slow down my app
              variables={{
                filter: omit(data.filter, '__typename'),
              }}
            >
            ...
```

As a workaround, I tried implementing the functionality without nested <Query>, similar to you guys have, where I manually use updateQuery/writeQuery/refetchQueries to update the dependent query after filter update mutation, but it also had no effect on the list query.

Just wanting to confirm that I am also seeing this issue.

**Comment by rosskevin** [comment] 2018-12-26 19:47
I believe I have written a reproduction test in PR referenced from https://github.com/apollographql/apollo-client/issues/2415#issuecomment-450012858 which tests explicit use of `writeQuery`.  I'll look into adding tests for payload responses from `mutate` as well.

**Comment by rosskevin** [comment] 2018-12-27 21:02
@nilshartmann after much effort, on something that I should have known better, @danilobuerger pointed out that my error was failing (on a standard `mutate` without using the `update` option), that I had failed to request the `id` in the payload.  Therefore the standard `mutate` update payload would never normalize and update my person.  I had previously had an issue with `writeQuery` and will have to try and uncover it again to see if I can reproduce there.  I think all of these are closely related to your case.

I don't know if you have an error in the code above, but I noticed a few things, both of which would cause you a problem:

1. You show an _Example Mutation resolver_ called `updatePerson` and you don't show where you wire that up. Perhaps I am missing something but I usually see this code passed as the `update` option to `mutate` instead of as a global resolver.  This may not be right or wrong but I am unfamiliar with the way you are doing it.

2. Since you don't add an `id` to the payload of the mutation, it will never update your store with the `person`'s `name` (which perhaps you don't want it to and you want to control via the `update` option alone)

What I can say is that I have added tests to apollo-client that prove that observers are notified of updates when using `writeFragment`, `writeQuery`, `mutate`, and presumably `writeData` though I did not add a specific one for it.

This may not be an answer, but I hope it contains some useful information.

**Comment by nilshartmann** [comment] 2018-12-27 21:11
Thanks for your answer, @rosskevin! I'll check your hints and let you know if it works!

**Comment by danilobuerger** [comment] 2018-12-27 21:40
@nilshartmann query `id` in `GetPersonQuery` and `UpdatePersonMutation`.

**Comment by rosskevin** [comment] 2018-12-27 21:44
I'm going to close this.  @nilshartmann please ping me to reopen if it isn't working for you.

**Closed by rosskevin** 2018-12-27 21:44 UTC

**Comment by Natansab** [comment] 2019-01-24 16:55
@nilshartmann how did you solve this issue? I have the exact same issue and still no way how to fix it. Thanks

**Comment by wenisy** [comment] 2019-03-06 05:43
> @nilshartmann how did you solve this issue? I have the exact same issue and still no way how to fix it. Thanks

same here

**Comment by nshoes** [comment] 2019-03-07 04:53
Was having the same issue described here (and in many other issues). I got things working for me by using `client.watchQuery` (simplified from actual implementation):

```js
const MenuWrap = ({ client, children }) => {
  const [showMenu, setShowMenu] = useState(false)
  client
    .watchQuery({ query: clientShowMenu })
    .subscribe(({ data: { showMenu } }) => setShowMenu(showMenu))

  return <div style={{ marginLeft: showMenu ? 300 : 0 }}>
    { children }
  </div>
}

// somewhereElse.js

const toggleMenu = client => {
  const { showMenu } = client.readQuery({ query: clientShowMenu })
  client.writeQuery({ query: clientShowMenu, data: { showMenu: !showMenu } })
}

```



I had to do this because my `<Query />` implementation only got updated whenever the value I was changing (toggling a `Boolean`) switch back to the initial value 😞. The above snippet sucks though, I'm having to keep track of changes and update local component state 👎

@rosskevin I have seen your comments around a lot of issues dealing with `<Query />` not updating properly. Maybe a dumb question... but is it supposed to be used as a container for hydrating other components with data from local state? Sure does seem like it should.

**Comment by wenisy** [comment] 2019-03-08 10:34
I think you guys maybe want to try `fetchMore`
https://www.apollographql.com/docs/angular/features/cache-updates.html#fetchMore

**Comment by ankitsinghaniyaz** [comment] 2020-05-13 14:00
I'm getting this to work using `refetch`
https://www.apollographql.com/docs/react/data/queries/#refetching
