### ISSUE TITLE
Menu component doesn't re-render() itself after login (query).

### ISSUE THREAD

**Issue by ghost** [apollographql/react-apollo#1396] opened 2017-12-09 17:44 UTC
**Intended outcome:**
`Menu` component re-render() itself.

**Actual outcome:**
`Menu` component **doesn't** re-render() itself after
```
this.props.client.query({
    query: CURRENT_USER_QUERY,
    fetchPolicy: "network-only"
  });
```

At 99% the problem is me.
But maybe I can improve guides and docs with PR if I understand what not is going on...

**How to reproduce the issue:**
- Codesandbox: https://codesandbox.io/s/507w9qxrrl
- Stackoverflow: https://stackoverflow.com/questions/47655399/react-apollo-2-graphql-authentication-how-to-re-render-component-after-login

**Version**
- apollo-client-preset@1.0.5
- react-apollo@2.0.4

**Comment by johnunclesam** [comment] 2017-12-09 21:58
I think the problem is connected to this: https://stackoverflow.com/questions/47733633/react-apollo-2-with-react-router-graphql-hoc-loading-true-forever-if-i-navigat

**Comment by hwillson** [comment] 2018-09-18 01:41
Tracking in https://github.com/apollographql/react-apollo/issues/1385; closing here. Thanks!

**Closed by hwillson** 2018-09-18 01:41 UTC
