### ISSUE TITLE
useQuery types mismatch

### ISSUE THREAD

**Issue by ekfn** [apollographql/react-apollo#3354] opened 2019-08-12 15:29 UTC
Hello! I'm trying to use Query hook with typescript and found mismatch in interfaces.

```
interface QueryResult<TData = any, TVariables = OperationVariables> extends ObservableQueryFields<TData, TVariables> {
    data: TData | undefined;
    error?: ApolloError;
    loading: boolean;
    networkStatus: NetworkStatus;
    called: boolean;
}
```

`data` should be type `TData | undefined`, but while query is loading data is empty object and not undefined.

sandbox to reproduce:
https://codesandbox.io/s/apollo-client-error-template-kt7r4

**Comment by hwillson** [comment] 2019-08-12 19:56
Duplicate of #3323 - thanks!

**Closed by hwillson** 2019-08-12 19:56 UTC
