### ISSUE TITLE
Store does not set after query error

### ISSUE THREAD

**Issue by erencay** [apollographql/react-apollo#704] opened 2017-05-11 10:46 UTC
### Buggy Behavior

When I throw an error in a query resolver on the server side, -if the query was successfully fetched before- Apollo Client serves that data from cache.

### Expected Behavior

As far as I can say, query response clearly says returning data is null. Apollo Client saying that there was an error occurred on the server side for the query. But data in the store does not set to null.
```
{
  "data": {
    "room": null
  },
  "errors": [
    {
      "message": "No active room",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "room"
      ]
    }
  ]
}
```

### Version
- apollo-client@1.2.2
- react-apollo@1.2.0

**Comment by helfer** [comment] 2017-05-12 02:59
@erencay this is something that Apollo Client currently does intentionally and by design, because most of the time users do not want the cached data to be removed just because a temporary error happens. I think the recommendation for your use-case would be not to throw an error, but simply return `null` when there is no active room. In general, errors should be thrown for unexpected conditions on the backend. No room being active seems to be something that's expected in the application, so your schema should have a way of dealing with it that doesn't require throwing an error.

I'll close the issue, but I'm happy to discuss further. I'm curious to know what your use-case is and how important supporting this in Apollo Client would be for you.

**Closed by helfer** 2017-05-12 02:59 UTC

**Comment by erencay** [comment] 2017-05-12 09:08
@helfer I see your point and I think I should redesign my schema and replace `Room` with something like `RoomQuery`.

But I think `graphql-tools` can optionally offer some special kind of `Error` type, flagging that was an expected error -maybe an user error / validation error- and informs the client to remove the cached data if that type of errors were to thrown, which might reduce the boilerplate both on the server and client in such cases. If both server and client identify this error type it might provide a fine control over errors and decouple schema from errors.

**Comment by erencay** [comment] 2017-05-12 11:29
I threw a custom `TestError` on queries, caught it on `formatResponse` and replacing the original response errors with my errors did the trick. Now I can handle errors on client with afterware and mask unexpected errors. Though, it would be nice to able to pass custom errors to HOC.

Still, altering my schema and queries might be a better idea depending on edge cases. I'll see how it turns out.
