### ISSUE TITLE
getDataFromTree fails on 2.5.5

### ISSUE THREAD

**Issue by mschipperheyn** [apollographql/react-apollo#3071] opened 2019-05-26 13:39 UTC
I tried upgrading to react-apollo 2.5.5. I use server side rendering and a monorepo. Works ok on 2.5.4

```
import { ChunkExtractor } from '@loadable/server';
import { ApolloProvider, getDataFromTree } from 'react-apollo';
[...]
const extractor = new ChunkExtractor({
    statsFile: webStatsFile,
    entrypoints: ['client'],
});
await getDataFromTree(
    extractor.collectChunks(
        <App />,
    ),
);
```

```
Error while running `getDataFromTree` { Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at invariant (/Users/project/social-front/packages/server/Users/project/social-front/node_modules/react/cjs/react.development.js:88:1)
    at resolveDispatcher (/Users/project/social-front/packages/server/build/webpack:/Users/project/social-front/node_modules/react/cjs/react.development.js:1436:1)
    at Object.useContext (/Users/project/social-front/packages/server/build/webpack:/Users/project/social-front/node_modules/react/cjs/react.development.js:1441:1)
    at useTheme (/Users/project/social-front/packages/server/build/webpack:/Users/project/social-front/node_modules/@material-ui/styles/esm/useTheme/useTheme.js:4:1)
    at ThemeProvider (/Users/project/social-front/packages/server/build/webpack:/Users/project/social-front/node_modules/@material-ui/styles/esm/ThemeProvider/ThemeProvider.js:29:1)
```

**Comment by jasonpaulos** [comment] 2019-06-06 21:50
Hi @mschipperheyn, can you provide a small runnable reproduction (either as a github repo or in codesandbox.io) that demonstrates this issue? Thanks

**Comment by mschipperheyn** [comment] 2019-06-07 13:54
Let me see if I still have this issue. Made a lot of changes since then.

Hmm, no. Seems ok now.

**Comment by wmertens** [comment] 2019-06-25 14:58
I'm having a very similar issue. `getDataFromTree` throws. My backtrace looks like this:

```
Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at invariant (./node_modules/.registry.npmjs.org/react/16.8.6/node_modules/react/cjs/react.development.js:88:15)
    at resolveDispatcher (./node_modules/.registry.npmjs.org/react/16.8.6/node_modules/react/cjs/react.development.js:1436:28)
    at Object.useState (./node_modules/.registry.npmjs.org/react/16.8.6/node_modules/react/cjs/react.development.js:1461:20)
    at StyleSheetManager (./node_modules/.registry.npmjs.org/styled-components/5.0.0-beta.5-ej2_d45a7bae7410cb27b5b1aa1d71ed26d2/node_modules/styled-components/dist/styled-components.cjs.js:1276:25)
    at processChild (webpack-internal:///./node_modules/.registry.npmjs.org/react-dom/16.8.6_react@16.8.6/node_modules/react-dom/cjs/react-dom-server.node.development.js:2888:14)
    at resolve (webpack-internal:///./node_modules/.registry.npmjs.org/react-dom/16.8.6_react@16.8.6/node_modules/react-dom/cjs/react-dom-server.node.development.js:2812:5)
    at ReactDOMServerRenderer.render (webpack-internal:///./node_modules/.registry.npmjs.org/react-dom/16.8.6_react@16.8.6/node_modules/react-dom/cjs/react-dom-server.node.development.js:3202:22)
    at ReactDOMServerRenderer.read (webpack-internal:///./node_modules/.registry.npmjs.org/react-dom/16.8.6_react@16.8.6/node_modules/react-dom/cjs/react-dom-server.node.development.js:3161:29)
    at renderToStaticMarkup (webpack-internal:///./node_modules/.registry.npmjs.org/react-dom/16.8.6_react@16.8.6/node_modules/react-dom/cjs/react-dom-server.node.development.js:3661:27)
    at process (webpack-internal:///./node_modules/.registry.npmjs.org/react-apollo/2.5.4_c01c21c190c9724cfd8aca5c41e6e881/node_modules/react-apollo/react-apollo.esm.js:1063:20)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'Invariant Violation'
```

downgrading to 2.5.4 does not help.

The code it is failing on is https://github.com/styled-components/styled-components/blob/v5.0.0-beta.5/packages/styled-components/src/models/StyleSheetManager.js#L30 - this is a function component that executes `useState` during render, entirely according to the hook rules.

**Comment by wmertens** [comment] 2019-06-25 15:23
With react-apollo@3, the problem still exists

```
Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at invariant (./node_modules/.registry.npmjs.org/react/16.8.6/node_modules/react/cjs/react.development.js:88:15)
    at resolveDispatcher (./node_modules/.registry.npmjs.org/react/16.8.6/node_modules/react/cjs/react.development.js:1436:28)
    at Object.useState (./node_modules/.registry.npmjs.org/react/16.8.6/node_modules/react/cjs/react.development.js:1461:20)
    at StyleSheetManager (./node_modules/.registry.npmjs.org/styled-components/5.0.0-beta.5-ej2_d45a7bae7410cb27b5b1aa1d71ed26d2/node_modules/styled-components/dist/styled-components.cjs.js:1276:25)
    at processChild (webpack-internal:///./node_modules/.registry.npmjs.org/react-dom/16.8.6_react@16.8.6/node_modules/react-dom/cjs/react-dom-server.node.development.js:2888:14)
    at resolve (webpack-internal:///./node_modules/.registry.npmjs.org/react-dom/16.8.6_react@16.8.6/node_modules/react-dom/cjs/react-dom-server.node.development.js:2812:5)
    at ReactDOMServerRenderer.render (webpack-internal:///./node_modules/.registry.npmjs.org/react-dom/16.8.6_react@16.8.6/node_modules/react-dom/cjs/react-dom-server.node.development.js:3202:22)
    at ReactDOMServerRenderer.read (webpack-internal:///./node_modules/.registry.npmjs.org/react-dom/16.8.6_react@16.8.6/node_modules/react-dom/cjs/react-dom-server.node.development.js:3161:29)
    at renderToStaticMarkup (webpack-internal:///./node_modules/.registry.npmjs.org/react-dom/16.8.6_react@16.8.6/node_modules/react-dom/cjs/react-dom-server.node.development.js:3661:27)
    at process (webpack-internal:///./node_modules/.registry.npmjs.org/@apollo/react-hooks/0.1.0-beta.10_c01c21c190c9724cfd8aca5c41e6e881/node_modules/@apollo/react-hooks/lib/react-hooks.esm.js:658:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

can this issue be reopened @jasonpaulos?

**Comment by jasonpaulos** [comment] 2019-06-25 20:47
@wmertens Are you using `npm link` or relative file dependencies in your packages? If so, the steps here may help: https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react

Otherwise I'd be happy to reopen.

**Comment by wmertens** [comment] 2019-06-26 06:25
@jasonpaulos no, no linking and for sure no duplicate react package

**Comment by jasonpaulos** [comment] 2019-06-26 17:26
@wmertens any chance you could provide a minimal github repo that produces this issue? Thanks.

**Comment by mschipperheyn** [comment] 2019-06-26 19:30
@wmertens Not sure if this helps, but in my case, this occurred in a number of scenarios. conflicting versions of dependencies after switching branch (doing a `yarn install` fixed this for me). Async loading providers not working correctly (react-async-component). I switch to `loadable/components` and run the collectChunks extractor both inside and after getDataFromTree.

```
try {
			await getDataFromTree(
				extractor.collectChunks(
					<TheApp
					/>,
				),
			);
		} catch (err) {
			console.error('Error while running `getDataFromTree`', err);
		}
		if (reactRouterContext.url) {
			res.redirect(301, reactRouterContext.url);
			return;
		}
		const initialApolloState = client.extract();
		const jsx = extractor.collectChunks(
			sheets.collect(
				<TheApp />,
			),
		);
```

**Comment by mschipperheyn** [comment] 2019-08-16 13:58
@jasonpaulos I think the issue occurs when you use `getDataFromTree` for SSR and use a hook inside a React component and then apply `export default React.useMemo(MyComponent)` to that component. I'm also using @loadable/components. So it might be related to that as well.

**Comment by mschipperheyn** [comment] 2019-08-16 23:21
@jasonpaulos Ok, made a repo for you https://github.com/mschipperheyn/loadable-hooks-bug

**Comment by wmertens** [comment] 2019-08-19 12:23
@mschipperheyn 	your theory could be correct, styled-components is also using useMemo https://github.com/styled-components/styled-components/blob/f92f157f289ba6f92b1a0d0d243ce2fde22c4dda/packages/styled-components/src/models/StyleSheetManager.js#L51

@jasonpaulos any chance of this getting looked at by the core team? v3 is now out and it definitely breaks styled-components.

**Comment by mschipperheyn** [comment] 2019-08-19 13:35
Yeah, but useMemo is a hook, to be used inside the component itself. I confused it with React.memo to be used on the component.

**Comment by wmertens** [comment] 2019-08-19 15:05
@mschipperheyn 	what is the stack trace for your repro?

**Comment by mschipperheyn** [comment] 2019-08-19 17:14
@wmertens None. For now, it just works.

**Comment by hwillson** [comment] 2019-09-06 12:27
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!

**Closed by hwillson** 2019-09-06 12:27 UTC
Labels: reproduction-needed

**Comment by wmertens** [comment] 2019-10-02 08:20
FYI the reason it broke for me is that my server build inlined react but not styled-components, so the latter was using a separate instance of react. argh. Nothing to do with apollo, sorry for the noise.
