### ISSUE TITLE
Query component type definitions are incorrect

### ISSUE THREAD

**Issue by Madumo** [apollographql/react-apollo#2552] opened 2018-10-29 18:34 UTC
**Intended outcome:**
The `Query` component should respect it's own type definitions.

**Actual outcome:**
The `data` property from the result parameter of the children function might be defined as an empty object. This goes against the type definitions.

**How to reproduce the issue:**
The children functions is called with `QueryResults<TData, TVariables>` as it's first param. According to the `QueryResults` typings, the result object contain a `data` property which is typed as `TData | undefined`.

According to that typing, if `data` is **not undefined**, it can only be of `TData` type. This is not the case. When the children function is called `data` might be an empty object which doesn't respect it's own typing.

[Here is an example of the bug on codesandbox](https://codesandbox.io/s/z0zz9q6p).
Note: to properly see the type checking within codesandbox, you must go to "preferences", and then under "experiments" toggle on the "Use VSCode in the browser" option.

**Version**

- apollo-boot@0.1.18
- react-apollo@2.2.4

**Comment by elessarperm** [comment] 2018-11-05 07:59
Same thing. It even changes every week or so. Last month the Query behaviour was like you said, then it was changed to never return an {} so I had to fix all Query usages to just check for undefined, and here we go again

**Comment by rosskevin** [comment] 2018-12-26 23:49
Closing as duplicate of #1917

**Closed by rosskevin** 2018-12-26 23:49 UTC
