### ISSUE TITLE
Errors not displayed

### ISSUE THREAD

**Issue by nicolo-paganin** [apollographql/react-apollo#444] opened 2017-01-31 09:58 UTC
## Steps to Reproduce

In case of malformed query / mutation (e.g. query that has the return fields that not corresponds to the relative type, or the return type is wrong) the error is not shown, instead a 404 error is raised. 
Using Apollo-Client@0.7.0 and React-Apollo@0.8.3 the errors are correctly visualized.

### Buggy Behavior

The errors are not visualized

### Expected Behavior

The error shall be visualized

### Version
- apollo-client@0.8.1
- react-apollo@0.9.0

**Comment by imthehell** [comment] 2017-03-12 15:00
any news?

**Comment by calebmer** [comment] 2017-03-13 14:57
Could you show the exact error you are seeing? A 404 sounds like it is coming from your server.

**Comment by helfer** [comment] 2017-03-21 07:38
@imthehell could you provide a better description of the issue you're seeing? Is it that an error in your GraphQL query gets raised as a NetworkError?

**Comment by imthehell** [comment] 2017-03-21 17:41
thank you for the response. I have realized now that the problem is related to apollo-client and not to react-apollo.

Using apollo-client@0.7.0 is a query is malformed (in this example the name of a return field is wrong), the complete error with a description is returned to the client.

**Example**

 query QuotationList($page: Int, $size: Int, $status: String, $awarded: String, $filters: String) {
    getInsurancesByAgency(page: $page, size: $size, status: $status, awarded: $awarded, filters: $filters){
      docs {
        ... on CarInsuranceResponseSingleQuoteType {
              _id
              carPlateNumberIsKnown1 _(this field is wrong, the right field is carPlateNumberIsKnown, so without the final 1)_
              carPlateNumber 
              _....other fields_

**Apollo@0.7.0 returns this error**

GraphQL error: Cannot query field "carPlateNumberIsKnown1" on type "CarInsuranceResponseSingleQuoteType". Did you mean "carPlateNumberIsKnown" or "carPlateNumber"?

**Apollo@1.0.0-rc.5  returns this error**
error: Error: Network error: Network request failed with status 400 - "Bad Request"
  Error: Network error: Network request failed with status 400 - "Bad Request"


You may understand that with complex query Apollo@1.0.0-rc.5 doen't permit to debug the query like Apollo@0.7.0.

**Comment by cesarsolorzano** [comment] 2017-04-27 03:51
This was fixed in apollographql/apollo-client#1491, closing.

**Closed by cesarsolorzano** 2017-04-27 03:51 UTC
