### ISSUE TITLE
Network error: failed to fetch react apollo

### ISSUE THREAD

**Issue by CarlFMateus** [apollographql/react-apollo#3191] opened 2019-06-27 12:50 UTC
Good morning I do not speak English well. 
We are getting these Network error: Failed to fetch errors from Apollo randomly. We don't have any related errors in the API. It seems to be when the user leaves the app open for a while; does Apollo have any bugs related to this when the user leaves an app open for a while?

Error: Network error: Failed to fetch
    at new ApolloError (bundle.esm.js:76)
    at bundle.esm.js:1556
    at bundle.esm.js:1977
    at Set.forEach (<anonymous>)
    at bundle.esm.js:1975
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (bundle.esm.js:1973)
    at bundle.esm.js:1451

If anyone knows about this solution, I would appreciate it very much

**Comment by jasonpaulos** [comment] 2019-06-27 18:55
Hi @CarlFMateus, can you please provide a small runnable reproduction of the issue, either as a github repo or in codesandbox.io? Thanks.

**Comment by CarlFMateus** [comment] 2019-07-03 13:53
The problem with this situation is that I have two projects that are using apollo client if and is already being presented very often.
In my projects I am connecting apollo client with postgraphile and I can not show an example because they are private projects.

**Comment by hwillson** [comment] 2019-09-06 11:53
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!

**Closed by hwillson** 2019-09-06 11:53 UTC
Labels: reproduction-needed

**Comment by tdeekens** [comment] 2019-09-18 08:30
We are actually still seeing the same issue. We saw it in v2 and now in v3.1.0 too. It's super hard to reproduce or find the root cause. We see it being logged for our users through Sentry as well as when running E2E tests through Cypress.

**Comment by kltdwrds** [comment] 2020-02-26 21:42
@CarlFMateus
> It seems to be when the user leaves the app open for a while

It sounds like the client lost its network connection while apollo was polling / refetching.  I've experienced this error and a momentarily dropped connection was the root cause.

**Comment by CarlFMateus** [comment] 2020-03-06 14:08
That error continues
