### ISSUE TITLE
Binding components to `cache-only` state [Imperative store API]

### ISSUE THREAD

**Issue by gurdasnijor** [apollographql/react-apollo#586] opened 2017-03-30 06:46 UTC
`version: 1.0.0-rc.6`

I was experimenting with using the imperative store API to treat a subset of the apollo store cache as a local state source for state that doesn't need to sync with a server (in the same way i've done traditionally with redux stores.)  It looks like `graphql()` doesn't seem to provide any `data` when configured to read in a  `cache-only` configuration:

```javascript

const TODO_QUERY = gql`
  {
    todo(id: 1) {
      name
    }
  }
`;

// Prime the cache with some state
client.writeQuery({
  query: TODO_QUERY,
  data: {
    todo: {
      name: "Todo item",
    }
  }
});


// Get component to read state strictly from local cache with `fetchPolicy: 'cache-only'`
const TodoComponent = graphql(TODO_QUERY, {
  options: {fetchPolicy: 'cache-only'}
})(props => <div>{JSON.stringify(props)}</div>);


// `props` doesn't contain the `todo` item
// (rather the following:  {"data":{"variables":{},"loading":false,"networkStatus":7}}

```

Didn't see documentation around the use of the [imperative API](https://dev-blog.apollodata.com/apollo-clients-new-imperative-store-api-6cb69318a1e3) in this way with react-apollo, so this could be a case of me using a screwdriver as a hammer.  Are there any plans on the apollo roadmap to support these strictly local-cache use cases?

Maybe related to https://github.com/apollographql/react-apollo/issues/568#issuecomment-289978388?

Thanks in advance!

**Comment by helfer** [comment] 2017-04-04 23:01
Hi @gurdasnijor. Thanks for filing an issue! This is odd, because I think it should work. Would you be able to provide us with a small reproduction using [react-apollo-error-template](https://github.com/apollographql/react-apollo-error-template)? That would help me find and fix the issue quickly. Thanks!

**Comment by jbaxleyiii** [comment] 2017-05-03 04:52
Closing since this is more than two weeks old without a reproduction / response. If it is still an issue feel free to reopen!

**Closed by jbaxleyiii** 2017-05-03 04:52 UTC
