### ISSUE TITLE
Component won´t rerender with new data after client.resetStore()

### ISSUE THREAD

**Issue by piotrblasiak** [apollographql/react-apollo#807] opened 2017-06-29 20:23 UTC
Love apollo, but I have this problem...

## Steps to Reproduce

1. Render component:

```
@graphql(gql`
  {
    me {
      id
      name
    }
  }
`)
class MyComponent extends PureComponent { ... }
```
2. Call apolloClient.resetStore()

### Buggy Behavior

The component is not rerendered with a clared store. In this case I had logged out the user so the query should give me {me: null} but it still gives me the old object.

### Expected Behavior

It should give me a null object for "me" since I´ve logged out and cleared the store like the docs say.

### Version
- react-apollo@1.4.2

**Comment by jbaxleyiii** [comment] 2017-07-17 15:00
Bringing in an issue from AC to see if we can improve this:


**Intended outcome:**

resetStore clears the Apollo data

**Actual outcome:**
resetStore only refetches, there is no point where data in components is cleared


**How to reproduce the issue:**

error repo: https://github.com/stantoncbradley/apollo-reset-store
1. Run the app :)
2. Clicking resetStore button triggers Apollo resetStore
3. App logs nextProps as the come in through componentWillReceiveProps
4. At no point in the logs is the data cleared

Our actual use case is a user signing out of our app.  We noticed if another user logs in and one of the queries fails, data from the last user displays!  It was never cleared!!!!

**Comment by stantoncbradley** [comment] 2017-07-20 23:11
really like to see this get fixed!  it's imperative that we completely clear our user data after the user logs out!!! 🙏

**Comment by stantoncbradley** [comment] 2017-08-14 22:09
this is still a big issue.  We are locked into `react-apollo "1.1.3"` so we don't accidentally leak private data until this issue is resovled

**Comment by stantoncbradley** [comment] 2017-09-05 17:24
@jbaxleyiii this is still an issue as far as I'm aware.  related to #858 and #890 too

**Comment by mitjade** [comment] 2017-09-22 05:35
Still and issue also in apollo-client 2.0 beta.

**Comment by mitjade** [comment] 2017-09-22 05:36
Please add this to https://github.com/apollographql/apollo-client/milestone/9.

**Comment by tsnieman** [comment] 2017-10-27 15:17
I believe this is still a problem in 2.0 and should be re-opened.

**Comment by stantoncbradley** [comment] 2017-10-27 23:10
this is a really big issue and I'm afraid it's not well known, nor getting the attention it deserves. To be clear, react-apollo isn't properly clearing user data and there are scenarios where react-apollo can leak (sensitive) data after the store has been "cleared".  If more people realized they have this known issue in production, I don't think they would be happy with Apollo

**Comment by jbaxleyiii** [comment] 2017-10-28 12:53
@stantoncbradley this is on my radar for my next focus on cleaning up react-apollo 👍

**Comment by stantoncbradley** [comment] 2017-10-28 16:15
Thanks @jbaxleyiii looking forward to it 😄

**Comment by tcasey** [comment] 2017-11-18 17:42
Pretty sure this is still an issue

**Comment by gpoitch** [comment] 2017-12-04 15:20
Any workarounds for this? I tried manually recreating the client cache to no avail.

**Comment by stantoncbradley** [comment] 2018-01-05 07:07
@jbaxleyiii hopefully this is still on your radar? Major security concern for us. We can't upgrade til this is fixed

**Comment by n1ru4l** [comment] 2018-01-09 11:17
@gpoitch Currently you can use `writeQuery` to overwrite the existing query with null.

**Comment by n1ru4l** [comment] 2018-01-09 13:42
I created a failing test for this here: https://github.com/n1ru4l/react-apollo/commit/e358061c6883e4795cc3943bd4ee8517c28bc629

**Comment by idris** [comment] 2018-04-05 23:37
Does `client.cache.reset()` fix this?  I _think_ that should clear out the cache?

**Comment by lorensr** [comment] 2018-08-22 07:09
Here's a current repro of a `cache-only` `<Query>` not updating after `resetStore()`

https://codesandbox.io/s/72x4okp5m1

**Versions**
`react-apollo@2.1.11`

**Comment by hwillson** [comment] 2019-09-06 11:41
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!

**Closed by hwillson** 2019-09-06 11:41 UTC
Labels: bug
