### ISSUE TITLE
loading is false, but no data is present (and no error)

### ISSUE THREAD

**Issue by FezVrasta** [apollographql/react-apollo#2158] opened 2018-07-03 11:34 UTC
I'm opening this issue as follow up of #1314 since the original issue has been closed but several people are still reproducing the problem.

------

Just upgraded to Apollo 2.0, using react-apollo 2.0.0 -- it now appears that the graphql props option for a query is passed a data argument that can have loading set to false but no data.

That is, given a query, say:

```
query X($id: ID!) {
  myItem(id: $id) {
    id
    field
  }
}
```

and a `graphql` call:

```
graphql(query, {
  props({ data: { loading, error, myItem } }) {
    console.log('loading =', loading);
    console.log('error =', error);
    console.log('myItem =', myItem);
    return { ... }
 }
})(MyComponent)
```

We're seeing the output:

```
loading = true
error = undefined
myItem = undefined
loading = false
error = undefined
myItem = undefined
loading = false
error = undefined
myItem = {<data>}
```

That is, there is an interim state between `loading` having been set to false but `myItem` yet available on the `data` argument.

Is this expected, as it appears to differ from the behavior of Apollo 1.0. And if so, what is the reliable way to check that data was loaded and is ready for use in the component?

We're now using `(loading || !myItem)` to check whether something is loading.

**Comment by rosskevin** [comment] 2018-07-05 20:59
Hey Federico, just checking, are you using 2.0.0 exactly or the latest react-apollo@2.1.9?

**Comment by FezVrasta** [comment] 2018-07-06 17:50
We are on the latest stable

**Comment by llibdude** [comment] 2018-07-10 21:33
@FezVrasta I am running into this same exact issue.

My theory is that the request you are making is a CORS request.  The first instance of `loading = false` with no data is actually the preflight OPTIONS request resolving.  In my case i have:

`
loading = true
loading = false (no data)
loading = true
loading = false (with data)
`
It seems you are missing the state change back to `loading = true`.  I know my request is CORS.  I am still checking the issues to see if there are any other related issues opened to confirm the theory.  As it stands now I will be doing something similar to you to get by this.

Hoping there is a way to ignore preflight requests from being sent down as props.

**Comment by FezVrasta** [comment] 2018-07-10 21:34
No my request is not CORS, it's on the same domain

**Comment by conatus** [comment] 2018-07-14 08:59
Thanks for this but sadly CORS is a red herring. The rough problem is known - see the end of https://github.com/apollographql/react-apollo/issues/1314

It is to do with how Apollo handles its caching.

**Comment by stevehv** [comment] 2018-07-21 20:01
I'm also suffering from the same problem. I encountered it when I had forgotten to define a resolver for a local field.
```javascript
const client = new ApolloClient({ clientState: { defaults: {}, resolvers: {} } });
```
My `Query` was calling the following query which has a local field:
```graphql
{
    viewer {
       id
       someField @client
    }
}
```
I'd expect there to be some kind of an error message for a missing resolver, but instead there is no error and the Query just returns a completely empty data object, which makes it impossible to know where the problem is.

**Comment by FezVrasta** [comment] 2018-07-21 20:18
@stevehv yours it's a different problem. My queries work most of the times

**Comment by zach-is-my-name** [comment] 2018-11-20 19:45
This behavior has suddenly become a MAJOR problem with my app running:
   ```
     "react": "^15.5.4",
    "react-apollo": "^2.2.4",
    "apollo-cache-inmemory": "^1.3.10",
    "apollo-client": "^2.4.6",
    "apollo-link-context": "^1.0.9",
    "apollo-link-http": "^1.5.5",
```
I am querying the id type on every type.  What else can be done to work-around this??
Currently I'm trying to refetch the query in render() when` networkStatus === 7 && !this.props.data.myTypeName `
to no avail

**Comment by talk2rajeev** [comment] 2018-12-11 13:32
This issue arise In my project when I load 3 components with the same query but with different input variables. Tried all sort of solution provided on net, also refactored my code.. but No luck 🙁

**Comment by rosskevin** [comment] 2018-12-27 15:19
Closing in favor of reopening #1314, the majority of the conversation is there, please add to it as needed.

**Closed by rosskevin** 2018-12-27 15:19 UTC
