### ISSUE TITLE
import { gql } from "react-apollo" is failing

### ISSUE THREAD

**Issue by tnrich** [apollographql/react-apollo#1273] opened 2017-10-24 20:45 UTC
Hey there. I have an npm module `teselagen-react-components` that I share between repos. After upgrading my dependencies in TRC, my other projects depending on TRC started getting the following error: 

![image](https://user-images.githubusercontent.com/2730609/31966978-153ec8f6-b8d2-11e7-8980-b6ed0d61c726.png)

It appears this line of compiled es6 code is failing: 
```
import { gql } from "react-apollo";

export default gql(_templateObject);
```

When diving into my node_modules, I do indeed see that the gql export appears to be missing: 

![image](https://user-images.githubusercontent.com/2730609/31966889-c79ac1fe-b8d1-11e7-8bd0-b2cdf9213deb.png)

Any thoughts as to why this is happening? 

Thanks!

**Comment by tnrich** [comment] 2017-10-24 20:54
Hmm it appears that this was due to me installing a 2.0 version of react-apollo. Is the 2.0 not ready to go yet?

Thanks!

**Comment by joshbalfour** [comment] 2017-10-25 03:35
seeing similar in react-native, also fixed by downgrading to 1.4.15

![image](https://user-images.githubusercontent.com/1060378/31979271-c8083b2a-b913-11e7-8482-54dbfdd686af.png)
![image](https://user-images.githubusercontent.com/1060378/31979251-b28807e4-b913-11e7-8107-f00916f92154.png)

**Comment by Tav0** [comment] 2017-10-25 06:12
Install graphql-tag, idk why this hasn't been a big noticed unless it is hidden somewhere

**Comment by wesbos** [comment] 2017-10-25 19:32
I'm getting this issue to with react-apollo@2.0.0

This code errors: 

```js
import { gql } from 'react-apollo';

console.log(gql); // undefined

export const itemDetails = gql`
  fragment itemDetails on Item {
    id
    title
    price
    fullPrice
    description
    image {
      id
      url
      secret
    }
  }
`;
```

**Comment by pungggi** [comment] 2017-10-25 19:34
Like tav said you need to import gql from another package called graphql-tag

**Comment by pungggi** [comment] 2017-10-25 19:36
See https://www.npmjs.com/package/graphql-tag

**Comment by wesbos** [comment] 2017-10-25 19:45
Ah - I thought 2.0 had no breaking changes. I guess this needs to come externally?

The same thing goes for `createNetworkInterface` not being importable. 

I think maybe 2.0.0 on npm got botched because both of these things should be importable...

**Comment by wesbos** [comment] 2017-10-25 20:17
So createNetworkInterface is deprecated in favor of apollo-link and apollo-link-http

I think we need to wait for some more migration docs :)

**Comment by nickyhajal** [comment] 2017-10-27 20:42
I also hit up against this as all the documentation still includes: 

`import { gql, graphql } from 'react-apollo';`

**Comment by jupl** [comment] 2017-10-29 21:21
https://www.apollographql.com/docs/react/2.0-migration.html

**Comment by shahzeb1** [comment] 2017-10-30 03:51
Does anyone know about how to use gql (using graphgql-tag) with **variables and options**. The [documentation is here](https://www.apollographql.com/docs/react/basics/queries.html#graphql-options) which I have been following.
My code:

```js
const currentUserEnv = gql`
query{
  environments($identityId: String!){
    uuid
    imageLink
    title
  }
}`;
const envWithData = graphql(currentUserEnv, {
  options: { variables: { identityId: 'user-id' } }
})(Dashboard);
export default envWithData;
```
Error:
![image](https://user-images.githubusercontent.com/1383831/32153994-e2c66614-bcea-11e7-818b-ac76c5513730.png)

**Comment by n1ru4l** [comment] 2017-10-30 09:21
@shahzeb1 that is not a valid graphql query. You can learn about the GraphQL query syntax here: http://graphql.org/learn/queries/

I think you want to do the following:

```graphql
query environments($identityId: String!) {
  environments(identityId: $identityId){
    uuid
    imageLink
    title
  }
}
```

**Comment by shahzeb1** [comment] 2017-10-31 05:48
@n1ru4l thank you. That was my problem, I wasn't setting the variables after the `query`.

**Comment by ddrabik** [comment] 2017-11-03 22:36
Here's a [codemod](https://github.com/ddrabik/js-transforms/blob/master/transforms/gql-from-graphql-tag.js) help migrate over

**Comment by francisngo** [comment] 2017-11-09 18:05
README.md needs update to mention using graphql-tag instead of importing gql from 'react-apollo'.

**Comment by marcelodeveloper** [comment] 2017-11-10 01:14
Yeahh, it's the best way @francisngo. =)

**Comment by deadcoder0904** [comment] 2018-05-12 23:36
Yo bot I still have the same issue. Idk what I'm doing wrong. I have the same todo example just with 1 additional network request. 

Reproducible demo can be found at http://github.com/deadcoder0904/apollo-coinbase & the same demo (with some tweaks) written by Apollo team is at https://codesandbox.io/s/github/apollographql/apollo-link-state/tree/master/examples/todo

But Idk why mine isn't working❓

**Closed** 2018-08-16 23:16 UTC
Labels: no-recent-activity
