### ISSUE TITLE
Loading = true, when it should be false

### ISSUE THREAD

**Issue by jacargentina** [apollographql/react-apollo#2575] opened 2018-11-08 18:33 UTC
**Intended outcome:**
Query `Loading = false`

**Actual outcome:**
Query `Loading = true`

**How to reproduce the issue:**
My simple app gets stuck with the "loading indicator" event when data is already there
Reproduction repo here https://github.com/jacargentina/react-apollo-error-template
Simply run `npm start`
Then play searching with terms Smith, Deey... clear some letters... wait... After some tries the bug would be visible. **Loading never quits**

**Version**

- apollo-client@2.3.1
- react-apollo@2.1.4

**Comment by strongpauly** [comment] 2018-11-14 12:55
I am seeing this too with react-apollo@2.2.4

**Comment by anied** [comment] 2019-02-20 22:01
I think this is probably a duplicate of https://github.com/apollographql/react-apollo/issues/1931 , which I am also encountering.

**Comment by hwillson** [comment] 2019-06-15 11:26
Closing as a duplicate of https://github.com/apollographql/react-apollo/issues/1931. Thanks!

**Closed by hwillson** 2019-06-15 11:26 UTC
