### ISSUE TITLE
onComplete being called on every render

### ISSUE THREAD

**Issue by vititu** [apollographql/react-apollo#2522] opened 2018-10-21 19:02 UTC
The changes made related to issue #2177 causes `onCompleted` to be called on every render. Before it was called once.

That might break the app causing a `Maximum update depth exceeded error` if trying to setSate with the data provided.

**Comment by JoviDeCroock** [comment] 2018-10-22 08:59
Why would you use `setState` with provided data, just wondering.

**Comment by geekplux** [comment] 2018-11-08 14:14
same problem.

**Comment by riccoski** [comment] 2018-11-26 18:37
`I think the best way is to use the skip prop.
onCompleted() {

setState({
    skip: true
});
<Query skip={this.state.skip>
`

**Comment by asgeirfri** [comment] 2019-01-16 14:00
Does anyone know the propper way to only setState after server call? Thanks.

**Comment by charlex** [comment] 2019-02-14 19:55
This is happening to me as well. 

This seems to be functioning differently from what I understand the intended behavior of `onCompleted` to be.

Any hints as to why this is happening?

**Comment by JaosnHsieh** [comment] 2019-03-22 08:56
you can add an if else condition in completed function in order to prevent what will change state again and again.

```javascript
       <Query
            query={XXXXX}
            onCompleted={(data) => {
              if (!initValue) {
                   ...do something
              }
            }}
          >
```

**Comment by hwillson** [comment] 2019-06-15 11:43
This has been fixed in current day versions of `react-apollo`. Thanks!

**Closed by hwillson** 2019-06-15 11:43 UTC

**Comment by charlex** [comment] 2019-06-15 11:45
That's great! @hwillson Thank you for updating this ticket!

**Comment by kcvin94** [comment] 2019-09-06 08:08
still happening actually...

**Comment by dylanwulf** [comment] 2019-09-06 13:23
@kcvin94 Should be fixed in the newly released v3.1.0. See #3353 for more details.
