### ISSUE TITLE
Unit test failed

### ISSUE THREAD

**Issue by jayhuang75** [apollographql/react-apollo#499] opened 2017-03-02 21:30 UTC
## Steps to Reproduce

Describe how to reproduce this issue.

> code samples are greatly appreciated!

```js
import { SubscriptionClient, addGraphQLSubscriptions } from 'subscriptions-transport-ws';
import ApolloClient, { createNetworkInterface } from 'apollo-client';
import Configs from '../../configs';

// console.log(Configs.API.ENDPOINT.GRAPHQL.URL);
// console.log(getJWTToken());

// Global.Apollo
// For the unit test, the Configs is not loaded for uri so we hard code the local graphql endpoint
// Create regular NetworkInterface by using apollo-client's API:
const networkInterface = createNetworkInterface({
  uri: Configs.API.ENDPOINT.GRAPHQL.URL,
});

// Create WebSocket client
const wsClient = new SubscriptionClient('ws://localhost:8090', {
  reconnect: true,
  connectionParams: {
    // Pass any arguments you want for initialization
  },
});

// Create the header for http request with apollo Graph!
const MiddleWare = {
  applyMiddleware(req, next) {
    if (!req.options.headers) {
      req.options.headers = {};  // Create the header object if needed.
    }
    // set JWT token in header
    req.options.headers.Authorization = Configs.AUTH.HEADER_BEARER + Configs.AUTH.DEBUG_JWT_TOKEN;
    next();
  },
};

// Use the header
networkInterface.use([MiddleWare]);

// Extend the network interface with the WebSocket
const networkInterfaceWithSubscriptions = addGraphQLSubscriptions(
    networkInterface,
    wsClient,
);

// Init finial apolloClient
const apolloClient = new ApolloClient({
  networkInterface: networkInterfaceWithSubscriptions,
});

export default apolloClient;

```

### Buggy Behavior

Unit test failed with this message
`   
 TypeError: _subscriptionsTransportWs.SubscriptionClient is not a constructor
`

### Expected Behavior

should be pass

### Version
- apollo-client@0.8.7

**Comment by calebmer** [comment] 2017-03-03 14:37
What version of `subscriptions-transport-ws` are you using? This looks like a `subscriptions-transport-ws` error and not a `react-apollo` error.

cc @Urigo

**Comment by Urigo** [comment] 2017-03-08 15:53
duplicate of https://github.com/apollographql/subscriptions-transport-ws/issues/87

Will be discussed there

**Closed by Urigo** 2017-03-08 15:53 UTC
