### ISSUE TITLE
Int not recognized as such but as a String

### ISSUE THREAD

**Issue by NitroBAY** [apollographql/react-apollo#621] opened 2017-04-12 18:11 UTC
Hello,

## The error

My schema contains : 
```
  type Query {
    drugs(name: String, category_id: Int): [Drug]
  }
```
My `drugs` resolver : 
```
  Query: {
    drugs(root, data) {
      if (data.name) {
        Object.assign(data, {
          name: {
            $like: `%${data.name}%`,
          },
        });
      }
      return Drug.findAll({ where: omitBy(data, isEmpty) });
    },
  },
```
I have this error `Error: GraphQL error: Variable "$category_id" of type "String" used in position expecting type "Int".` even though my `category_id` variable is an integer (3).

```
const allDrugs = gql`
query DrugsList($name: String, $category_id: String) {
  drugs(name: $name, category_id: $category_id) {
    id,
    name
  }
}
`;

export default graphql(allDrugs, {
  options(ownProps) {
    console.log(ownProps.categoryId, typeof ownProps.categoryId);
    return ({
      variables: {
        name: ownProps.searchRequest,
        category_id: 3,
      },
    });
  },
})(DrugsList);
```

### Version
- apollo-client@1.0.2
- react-apollo@1.0.1

**Comment by helfer** [comment] 2017-04-12 18:45
Hi @NitroBAY! That's very strange, but it could be a bug. Could you build a quick reproduction of this with the [error template](https://github.com/apollographql/react-apollo-error-template)?

**Comment by NitroBAY** [comment] 2017-04-12 20:24
Oh, well, yes. Great idea BTW.

**Comment by jbaxleyiii** [comment] 2017-05-03 05:02
I'm going to close this since its been longer than 2 weeks without a reproduction. Feel free to reopen if its still an issue!

**Closed by jbaxleyiii** 2017-05-03 05:02 UTC
Labels: reproduction needed
