### ISSUE TITLE
react-test-renderer failure on Query when fetchPolicy is 'no-cache'

### ISSUE THREAD

**Issue by rasmusprentow** [apollographql/react-apollo#2603] opened 2018-11-20 10:08 UTC
When doing a query on only a subset of the data and using the fetchPolicy 'no-cache' all data is returned. 
When using 'network-only' for example it works fine. 

Lets say we have a query and a type: 

```
query Root { 
   getData: Data
}

type Data {
  foo: String!
  bar: String!
}
```

We then attempt to query using the following query: 
```
query GetData() { 
  getData
  {
     foo
  }
}

```

In our test we setup the `MockedProvider` such that it returns result: 

```
{ 
   foo: 'foo', 
   bar: 'bar
}
```

The data outputed from our component in this test will be the entire result set. 

**Version**

- apollo-client@2.4.6
- react-apollo@2.2.4

**Comment by rosskevin** [comment] 2018-12-26 20:50
I don't understand the problem. A `MockedProvider` is a test mock and it is going to return what you give it.

**Comment by rasmusprentow** [comment] 2018-12-26 22:10
No, it returns what you query. Unless you set the fetch policy to 'no-cache'. Changing the fetch policy shouldn't affect the mocked provider, but somehow it does.

**Comment by rosskevin** [comment] 2018-12-26 22:55
Please provide a code reproduction.  Even better, a PR that proves your issue is most likely to get attention.  As-is I still cannot understand your problem.

**Comment by rasmusprentow** [comment] 2018-12-27 08:33
Okay, I will make a small working example.

**Comment by rasmusprentow** [comment] 2018-12-27 08:42
Trying to reproduce using the sandbox examples from apollo. It seemed that I encountered a different but related problem. 

The example contains two components one called Currency and one called CurrencyNewFetch. The former works fine and the tests pass. The new fetch edition fails. The only code wise difference is the addition of `fetchPolicy="no-cache"` on the Query component. The test and everything else is the same, but the tests fails with the new fetch policy. 

Code can be found here: https://codesandbox.io/s/yvrk9ko2qv

**Comment by rosskevin** [comment] 2018-12-27 16:00
This seems to be erroring on a react-test-renderer failure - though I am not sure why, perhaps the async wait is not the proper setup?

```
Can't access .root on unmounted test renderer

Error: Can't access .root on unmounted test renderer
    at Object.get [as root] (https://p9lo49mz50.codesandbox.io/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9281:17)
    at _callee2$ (https://p9lo49mz50.codesandbox.io/src/currency.test.js:94:25)
    at tryCatch (https://p9lo49mz50.codesandbox.io/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (https://p9lo49mz50.codesandbox.io/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (https://p9lo49mz50.codesandbox.io/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (https://p9lo49mz50.codesandbox.io/src/currency.test.js:27:191)
    at eval (https://p9lo49mz50.codesandbox.io/src/currency.test.js:27:361)
```

I have created a reduced test case with the minimal amount of code.  
https://codesandbox.io/s/p9lo49mz50

At this point I cannot declare this is a bug with `MockedProvider`, `MockLink` or react-apollo in general, because the error points to a failure in the test code, but I am curious.

If anyone else has a solution to what looks like a react-test-renderer setup problem please comment.  If there is something to be changed to accommodate, would be also good to know.

**Comment by hwillson** [comment] 2019-09-06 11:42
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!

**Closed by hwillson** 2019-09-06 11:42 UTC
Labels: has-reproduction

**Comment by HugoLiconV** [comment] 2020-03-24 22:31
I'm getting an error while testing when adding `fetchPolicy: "network-only"` I'm using v3.1.3. Here is the code: 
```javascript
  const {
    error: getSupervisorsError,
    loading: getSupervisorsLoading,
    data: getSupervisorsData
  } = useQuery(GET_SUPERVISORS, {
    fetchPolicy: "network-only"
  });

// Test

const supervisor1 = {
    id: 1,
    type: "COURIER_SUPERVISOR",
    name: "Daren",
    lastName: "Kuhic",
    surname: "Corkery"
  };

  const supervisor2 = {
    id: 2,
    type: "COURIER_SUPERVISOR",
    name: "Antoinette",
    lastName: "Mitchell",
    surname: "Marvin"
  };

  const supervisor3 = {
    id: 3,
    type: "COURIER_SUPERVISOR",
    name: "Serena",
    lastName: "Ratke",
    surname: "Gislason"
  };

  const courier1 = {
    id: 4,
    type: "COURIER",
    name: "Bernhard",
    lastName: "McGlynn",
    surname: "Kuphal"
  };
  const courier2 = {
    id: 5,
    type: "COURIER",
    name: "Jeromy",
    lastName: "Jones",
    surname: "Carter"
  };
  const courier3 = {
    id: 6,
    type: "COURIER",
    name: "Parker",
    lastName: "Bergnaum",
    surname: "Herzog"
  };

  const branchOffice1 = {
    id: 1,
    name: "Stracke"
  };
  const branchOffice2 = {
    id: 2,
    name: "Vandervort Group"
  };
  const branchOffice3 = {
    id: 3,
    name: "Jast - Kessler"
  };

  const getSupervisorsData = {
    getUsers: {
      users: [supervisor1, supervisor2, supervisor3]
    }
  };

  const getSupervisorsQueryMock = {
    request: {
      query: GET_SUPERVISORS
    },
    result: {
      data: getSupervisorsData
    }
  };

  const getCouriersData = {
    getUsers: {
      users: [courier1, courier2, courier3]
    }
  };

  const getCouriersQueryMock = {
    request: {
      query: GET_COURIERS
    },
    result: {
      data: getCouriersData
    }
  };

  const getBranchOfficesData = {
    getBranchOffices: {
      branchOffices: [branchOffice1, branchOffice2, branchOffice3]
    }
  };

  const getBranchOfficesQueryMock = {
    request: {
      query: GET_BRANCHES
    },
    result: {
      data: getBranchOfficesData
    }
  };
const { getByText, ...wrapper } = renderWithRouter(
      <ScheduleForm onSubmit={onSubmit} />,
      [getBranchOfficesQueryMock, getSupervisorsQueryMock, getCouriersQueryMock]
    );
    act(() => {
      jest.runAllTimers();
    });
    const courierInput = wrapper.getByLabelText(/Selecciona al repartidor/gi);
    fireEvent.click(courierInput);
    const selectedCourier = getByText(getUserFullName(courier1)); // this fails when I add `fetchPolicy: "network-only"`
```
