### ISSUE TITLE
Strongly Typing grapqhl HoC - Type 'DataValue<Response, Variables> | undefined' has no property 'loading' 

### ISSUE THREAD

**Issue by arteforme** [apollographql/react-apollo#2396] opened 2018-09-19 04:30 UTC
**Intended outcome:**

I'm trying to strongly type the higher order components I'm creating and am using [Typing the Higher Order Components](https://www.apollographql.com/docs/react/recipes/static-typing.html#operation-result) as a guide.

**Actual outcome:**

Using the previously linked code as a base, I'm getting the following TypeScript errors:

```
Type 'DataValue<Response, Variables> | undefined' has no property 'loading' and no string index signature.
Type 'DataValue<Response, Variables> | undefined' has no property 'hero' and no string index signature.
Type 'DataValue<Response, Variables> | undefined' has no property 'error' and no string index signature.
```

**How to reproduce the issue:**

Below is the code I'm using with a minor change (`return <div>{hero.name}</div>)` in the `default export`:

```
import React from "react";
import gql from "graphql-tag";
import { graphql } from "react-apollo";

const HERO_QUERY = gql`
  query GetCharacter($episode: Episode!) {
    hero(episode: $episode) {
      name
      id
      friends {
        name
        id
        appearsIn
      }
    }
  }
`;

type Hero = {
  name: string;
  id: string;
  appearsIn: string[];
  friends: Hero[];
};

type Response = {
  hero: Hero;
};

type Variables = {
  episode: string;
};

// Note that the first parameter here is an empty Object, which means we're
// not checking incoming props for type safety in this example. The next
// example (in the "Options" section) shows how the type safety of incoming
// props can be ensured.
const withCharacter = graphql<{}, Response, Variables>(HERO_QUERY, {
  options: () => ({
    variables: { episode: "JEDI" }
  })
});

export default withCharacter(({ data: { loading, hero, error } }) => {
  if (loading) return <div>Loading</div>;
  if (error) return <h1>ERROR</h1>;
  return <div>{hero.name}</div>
});
```

**Versions of related packages**

* "apollo-cache-inmemory": "^1.2.10",
* "apollo-client": "^2.4.2",
* "apollo-link": "^1.2.3",
* "apollo-link-http": "^1.5.5",
* "apollo-link-state": "^0.4.2",
* "react": "^16.5.2"
* "react-apollo": "^2.1.11"
* "typescript": "^3.0.3"
* "@types/graphql": "^14.0.0",

**Additional information**

I experienced the same issue on older versions of the packages listed above.  I updated to see if the latest versions would resolve the issue.

I also looked through the typings files from what I can see, the `loading`, `hero`, and `error` props should exist.  What am I missing?

**Comment by sunnyvempati** [comment] 2018-09-22 21:37
+1

**Comment by DanilaLeontyev** [comment] 2018-11-21 04:43
Yes) question is actual)

**Comment by DanilaLeontyev** [comment] 2018-11-21 04:53
You can see https://github.com/apollographql/react-apollo/issues/2215

**Comment by rosskevin** [comment] 2018-12-27 17:55
Closing as duplicate of #2215

**Closed by rosskevin** 2018-12-27 17:55 UTC
Labels: docs, has-reproduction
