### ISSUE TITLE
No error in mutationState if errorPolicy: 'all'

### ISSUE THREAD

**Issue by fenok** [apollographql/react-apollo#1854] opened 2018-03-27 13:46 UTC
**Intended outcome:**
Let's say I'm using [Mutation](https://github.com/apollographql/react-apollo/blob/e5f47f886bff79a10d18d414a8e3561f3754166e/src/Mutation.tsx#L84) and setting errorPolicy globally. I want to access error in mutationState regardless of errorPolicy being 'none' or 'all'.

**Actual outcome:**
In case of errorPolicy: 'none' everything works as expected.
In case of errorPolicy: 'all' there is no error in [mutationState (result)](https://github.com/apollographql/react-apollo/blob/e5f47f886bff79a10d18d414a8e3561f3754166e/src/Mutation.tsx#L162), but other data is there.

**How to reproduce the issue:**
It's a private project and simple case.

**Version**

* apollo-client@2.2.0
* react-apollo@2.1.0

**Comment by cooperka** [comment] 2018-04-12 21:04
See duplicate issue: https://github.com/apollographql/react-apollo/issues/1389

**Comment by hwillson** [comment] 2018-05-30 19:41
Closing as a duplicate of https://github.com/apollographql/react-apollo/issues/1389. Thanks!

**Closed by hwillson** 2018-05-30 19:41 UTC
