### ISSUE TITLE
querying local data server side returns loading true for first render causing errors 

### ISSUE THREAD

**Issue by kedarguy** [apollographql/react-apollo#3390] opened 2019-08-19 14:59 UTC
**Intended outcome:**

upgrade an existing Next.js application that has local state to use react-apollo 3.0 

I created a repo using nextjs with-apollo example (which was updated to use app/react-hooks and ssr, see below.

I expected that as in previous version of react-apollo, when querying only local data, the loading will always return false and I will get the data synchronously 

**Actual outcome:**
When querying only local data for the first render useQuery returns loading true and no data

![scrnli_8_19_2019_5-46-18 PM](https://user-images.githubusercontent.com/23150397/63274910-4be3e980-c2a9-11e9-85ae-91231bad9924.png)

this is not consistent with the apollo [docs](https://www.apollographql.com/docs/react/essentials/local-state/#querying-local-state) :
```
import React from "react";
import { useQuery } from "@apollo/react-hooks";
import gql from "graphql-tag";

import Todo from "./Todo";

const GET_TODOS = gql`
  {
    todos @client {
      id
      completed
      text
    }
    visibilityFilter @client
  }
`;

function TodoList() {
  const { data: { todos, visibilityFilter } } = useQuery(GET_TODOS);
  return (
    <ul>
      {getVisibleTodos(todos, visibilityFilter).map(todo => (
        <Todo key={todo.id} {...todo} />
      ))}
    </ul>
  );
}
```

**How to reproduce the issue:**

https://codesandbox.io/embed/github/kedarguy/apollo-3.0-next-local-state-server-side-bug-reproduction/tree/master/?fontsize=14

**Versions**
  System:
    OS: Linux 5.0 Ubuntu 18.04.3 LTS (Bionic Beaver)
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.16.0 - ~/.nvm/versions/node/v10.15.3/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 68.0.2
  npmPackages:
    apollo-boost: 0.4.4 => 0.4.4 

Looking forward to be able to upgrade to the awesome apollo-hooks :)

**Comment by youfoundron** [comment] 2019-08-21 01:32
This may be related to #3338

**Comment by hwillson** [comment] 2019-09-06 12:31
Duplicate of https://github.com/apollographql/react-apollo/issues/3338. Let's continue the discussion over there. Thanks!

**Closed by hwillson** 2019-09-06 12:31 UTC
