### ISSUE TITLE
awaitRefetchQueries not working?

### ISSUE THREAD

**Issue by nikgraf** [apollographql/react-apollo#2267] opened 2018-08-08 19:01 UTC
**Intended outcome:**

I'm setting awaitRefetchQueries to true and I expected that the refetch queries would be loaded before I'm navigating to the overview page.

```jsx
          <Mutation
            mutation={addRecipeMutation}
            refetchQueries={[
              {
                query: recipesQuery,
                variables: { vegetarian: false }
              },
              {
                query: recipesQuery,
                variables: { vegetarian: true }
              }
            ]}
            awaitRefetchQueries={true}
          >
            {(addRecipe, { loading, error, client }) => (
              <form
                onSubmit={async evt => {
                  evt.preventDefault();
                  await addRecipe({
                    variables: {
                      recipe: {
                        title: data.title,
                        vegetarian: data.vegetarian
                      }
                    }
                  });
                  navigate("/");
                }}
              >
```

**Actual outcome:**

As you can see in the GIF the refetchQueries actually load afterwards.

![awaitrefetchqueries2](https://user-images.githubusercontent.com/223045/43858097-73967dbe-9b4d-11e8-8df5-66005b94c6f1.gif)

**How to reproduce the issue:**

I possibly can add a codesandbox in the future.

**Version**

From yarn.lock
* apollo-boost@0.1.12
* react-apollo@2.1.9:
* apollo-client@2.3.7

**Comment by hwillson** [comment] 2018-08-09 10:55
Hmm - interesting @nikgraf. I'll take a look at this today. If you're able to put together a quick runnable reproduction for this, that would definitely help get this resolved faster. Thanks!

**Comment by hwillson** [comment] 2018-08-09 11:51
Don't worry about the repro @nikgraf - I'm able to reproduce the issue. More details shortly.

**Comment by hwillson** [comment] 2018-08-09 12:02
Wait - the `awaitRefetchQueries` changes haven't been published yet. See: https://github.com/apollographql/react-apollo/blob/master/Changelog.md#vnext

The documentation updates were published beforehand because they're handled automatically, but the actual code changes aren't in place yet. The good news is that I've verified your scenario is fixed in `master`. I'll get a new `react-apollo` version published today. Thanks!

**Comment by hwillson** [comment] 2018-08-09 12:25
`awaitRefetchQueries` functionality should now be available in `react-apollo` 2.1.11. Thanks!

**Closed by hwillson** 2018-08-09 12:25 UTC
Labels: bug, confirmed

**Comment by nikgraf** [comment] 2018-08-09 20:48
thanks @hwillson 🙌

**Comment by s-r-jones** [comment] 2019-02-04 22:46
Im still seeing this in V 2.4 @hwillson

**Comment by mutefiRe** [comment] 2019-02-12 19:24
@s-r-jones same here

**Comment by MMayla** [comment] 2019-03-11 17:51
Same here

**Comment by nik-lampe** [comment] 2019-05-11 13:23
Same here

**Comment by nikgraf** [comment] 2019-05-12 12:04
seems to be broken again in the latest version

**Comment by Simba14** [comment] 2019-05-27 15:25
Experiencing the same issue on the latest release. Can this be reopened?

**Comment by imekachi** [comment] 2020-01-15 08:38
I'm on `@apollo/react-hooks": "^3.1.3`, and still having this issue.
