### ISSUE TITLE
Query becomes empty when omitting a field during cache update

### ISSUE THREAD

**Issue by cvle** [apollographql/react-apollo#658] opened 2017-04-26 15:31 UTC
## Steps to Reproduce

Here is a repo with the reproduced issue:
https://github.com/cvle/apollo-empty-query-error

It basically creates a new object in the cache, but omits a field that was previously
requested by a query.

### Buggy Behavior

After the update, the query data becomes empty without logging any errors.

### Expected Behavior

This is debatable. Several ideas are:
1. Log an error and fail
2. No error and omit missing fields from query.
3. Log error when field is required `!` and fail
4. Log error/warning when field is required `!` and omit missing fields from query

I personally tend to 4.

### Version
- apollo-client@1.0.4
- react-apollo@1.0.0

**Comment by helfer** [comment] 2017-04-26 16:03
If I understand the issue correctly, you're doing an `update`, but the shape of the object you're inserting into the list does not have all the fields that another query is expecting. Is that correct?

Because Apollo Client won't read partial data, you get no result.

I don't think this should work, but I believe that this used to throw an error, so we should find out why errors are no longer thrown when this happens.

@cesarsolorzano would you like to run the reproduction and find out what's going on?

**Comment by cesarsolorzano** [comment] 2017-04-26 23:06
@helfer sure thing, I'll check it out soon!

**Comment by cesarsolorzano** [comment] 2017-04-27 01:08
@helfer so the reproduction isn't using `readQuery` to read the the data after it's updated (which would have thrown the error).

Therefore, the problem here is the same as discussed before: when reading from the store an error is [thrown](https://github.com/apollographql/apollo-client/blob/48d8b1200c7581e2afb6d253dc8a2f7894ee7df4/src/data/readFromStore.ts#L154-L156) but since it's being catched [here](https://github.com/apollographql/apollo-client/blob/2ee7971938eba4c19f7de93ff182a6d55d145b44/src/core/QueryManager.ts#L923-L930) there's not warning or error message.

**Comment by cvle** [comment] 2017-04-28 06:10
> If I understand the issue correctly, you're doing an update, but the shape of the object you're inserting into the list does not have all the fields that another query is expecting. Is that correct?

> Because Apollo Client won't read partial data, you get no result.

> I don't think this should work

But the schema clearly allows that that field is optional, so I kinda expect that when I update the cache and don't include the field, it should be ok, as it is optional.

Just checked `Modern Relay` and they allow this kind of cache update, no matter if the field is required or optional.

**Comment by cesarsolorzano** [comment] 2017-05-06 23:15
@cvle if you don't want to provide a field when updating the cache, you must provide a null-like value instead of omitting it!

fixed in apollographql/apollo-client#1638

**Closed by cesarsolorzano** 2017-05-06 23:15 UTC
