### ISSUE TITLE
data typings discussion, is nullable data the right behaviour?

### ISSUE THREAD

**Issue by kandros** [apollographql/react-apollo#1584] opened 2018-01-27 11:26 UTC
In this commit 
https://github.com/apollographql/react-apollo/commit/12821cfd93f1d1d55449b1380d39e0e7cd8b1c69?diff=unified#diff-45a733ae4e94396f8fa0947302418680R49

data became nullable, which makes usage with typescript more complicated because I have to check it all the time.

considering that I already handle a case when loading is true if there's an error is it possible to type it such that if loading is false and there's no error, data will be present?

**Comment by bbqbaron** [comment] 2018-01-31 21:20
If we're typing with a language that's capable of unions, why not provide a typedef that acknowledges the mutually exclusive possibilities? If I were typing it from the ground up I might make a union (I'm trying to preserve the existing structures that GQL uses and not make them change their actual props types to use `kind` and other TS orthodoxy):

```
interface Error {
  error: ApolloError
}

interface Loading {
  loading: true
}

interface Ok<T> {
  error: undefined
  loading: false
  data: T
}

type GQLQuery<T> = Error |Loading|Ok<T>|undefined
```

or something. Just a driveby suggestion, but I think it makes case handling in a typed language more correct/true.

**Comment by rosskevin** [comment] 2018-12-27 03:46
Closing as duplicate of  #1917

**Closed by rosskevin** 2018-12-27 03:46 UTC
