### ISSUE TITLE
Cannot recover from errors via `refetch` or `resetStore`

### ISSUE THREAD

**Issue by tmeasday** [apollographql/react-apollo#2070] opened 2018-06-04 06:11 UTC
**Intended outcome:**

If a query throws an error, recover, either by `refetch`-ing (if intermittent, this could work) or `resetStore`-ing and changing something (in my case logging in / thus changing an auth header).

**Actual outcome:**

`react-apollo` will not process the successful result of the re-run query (gory details below).

**How to reproduce the issue:**

Here is a reproduction: https://codesandbox.io/s/qv1q541v2j

Note this points at: https://launchpad.graphql.com/vm3qvkz743 a really simple launch pad that throws an error 50% of the time.

To reproduce the problem in its pure form:

1. Load https://qv1q541v2j.codesandbox.io/ , ensuring it gets the error the first time (ie refresh the page until it does)
2. Hit the refresh button. Notice that even if the graphql network request returns actual data (it will 50% of the time), it never updates the component.

I can make a less random reproduction, this just seemed an easy way to show what's going on.

**Version**

* apollo-client@2.3.2
* react-apollo@2.1.4 [NOTE this doesn't happen with older versions, see gory details below)

**Gory details**

Why does this happen?

The reason is the confluence of two things:

1. [This PR](https://github.com/apollographql/react-apollo/pull/1849) which added an optimization to ignore query results if the previous query result was complete

2. If an query is in the store as an error, a refetch will *not* inform listeners when it begins, due to this line:

https://github.com/apollographql/apollo-client/blob/09b26bd8d14abcc9f3f7c4648d56b66df83ef658/packages/apollo-client/src/core/QueryManager.ts#L469-L472

So what happens is:
a) first query returns, error. Picked up by RA, renders.
b) refetch happens (either directly or via `resetStore`). Due to (a) being an error and 2. above, RA is never informed.
c) refetch query returns. In 1. above, RA compares it to the first query, which has `networkStatus === 7`, so it throws it away.

I'm happy to submit a PR with a fix, if someone can give me some guidance on where to fix it. @jbaxleyiii do you think the optimization (1.) is perhaps broken in other places and should be removed? I won't pretend to fully understand all the code paths that lead to `next()` being called, but I suspect other similar ones could have been missed.

**Comment by tmeasday** [comment] 2018-06-05 04:36
Note: You can work around the issue above by using `fetchPolicy: 'cache-and-network'` on your query.

**Comment by bryandowning** [comment] 2018-06-11 23:35
I ran into a similar issue, but setting `fetchPolicy: 'cache-and-network'` did not work. However, passing `variables={{ v: Math.random() }}` to the `<Query>` component did work.

**Comment by moritzmorgenroth** [comment] 2018-06-15 11:00
Thanks @bryandowning  for the workaround, I can confirm that it temporarily solves the issue.

**Comment by kkotwal94** [comment] 2018-06-29 23:22
@tmeasday the hero i needed after hours, thanks!

**Comment by tmeasday** [comment] 2018-07-03 04:29
I reproduced the issue in a test here: https://github.com/tmeasday/apollo-client/commit/7d69c486b76186bc8a2dda70ebcea38a30c66882

I had a plan to try and solve the problem by modifying the behaviour of `apollo-client` (not sure if that was a good plan or not), but this doesn't seem possible, given that `react-apollo` does this other hacky thing which ultimately means AC doesn't know about the previous error on the query: https://github.com/apollographql/react-apollo/pull/1580/files

I guess changing the behaviour here in RA is the right approach. I am going to seek guidance.

**Comment by tmeasday** [comment] 2018-07-03 09:39
Actually, that's not right, apologies to the code above. Actually the `lastError` gets cleared by the `resetStore()` also, so essentially the query is "new" and so the behaviour of AC is to not notify on loading.

**Comment by tmeasday** [comment] 2018-07-03 09:43
I think a better solution is to just get rid of or at least improve the optimization [here](https://github.com/apollographql/react-apollo/pull/1849)

**Comment by tmeasday** [comment] 2018-07-03 11:33
Fixed by https://github.com/apollographql/react-apollo/pull/2157

**Comment by tinchoz49** [comment] 2018-07-03 12:43
great work @tmeasday !

**Comment by zachrip** [comment] 2018-08-06 22:09
Is this going to be merged soon?

**Comment by iamrommel** [comment] 2018-08-19 13:45
Are there any updates on this?

**Comment by suciuvlad** [comment] 2018-10-08 13:40
I'm experiencing the same issue.

**Comment by csharad** [comment] 2018-10-30 05:34
This is a high priority issue and needs to be fixed ASAP. Any pointers on how I could help to fix it would be awesome.

**Comment by leogoesger** [comment] 2018-11-26 16:40
I am running into the same issue, how do you recover from error? I have a `getCurrentUser` from `auth-token` hook in react, but if there is no `auth-token`, it simply returns the error that there is no auth-token. But then if user login again, he/she cannot recover. I guess I could check for my cookies, but it is not ideal.

**Comment by leogoesger** [comment] 2018-11-27 16:55
I am solving this problem by using `error-policy` right now, not sure if it is the best solution. But setting `error-policy` on the certain query to `ignore` will ignore the error message.

**Comment by frankfaustino** [comment] 2018-12-31 05:42
This did the trick for me:
```jsx
<Query query={QUERY} fetchPolicy="cache-and-network" errorPolicy="ignore">
```

**Comment by maxguzenski** [comment] 2019-02-08 16:01
Is there any update on this? errorPolicy='ignore' look like to not work anymore...

**Comment by sami616** [comment] 2019-03-02 19:15
I am also experiencing this, refetch successfully makes a network request but doesn't update the state of my component

**Comment by alanbo** [comment] 2019-03-18 23:39
I have similar problem. I have a user query that is returning a user if the session is established or returns an error if the user is not logged in. If there is an error person is redirected to login screen. I also have a login mutation that returns a user. Unfortunately, non of the <Query /> elements that were rendered with an error (even though I'm handling it) update after successful login. I'm checking the store with apollo dev tools and everything is fine. Just react elements do not update anymore after error. 
Any updates on this? - this is kind of bug that forces me to switch to traditional redux approach.

**Comment by MrSaints** [comment] 2019-03-19 09:24
> I have a user query that is returning a user if the session is established or returns an error if the user is not logged in

Not entirely related to this specific problem, but one thing we started doing was to move away from returning errors to explicitly setting them in the response. For example, rather than indicating that a session is not established through an error, you can model that using a response state using a union type:

```
union User = LoggedInResponse | NotLoggedInResponse
```

```
{
    __typename
    ... on LoggedInResponse {
        username
    }
    ... on NotLoggedInResponse {
        message
    }
}
```

The naming can obviously be better here. 

Now you can switch on `__typename` in the `data`.

**Comment by kYann** [comment] 2019-03-31 09:18
Hello. Same error here, if there is an error, after refetch the render is not called.

**Comment by n-kolodziej** [comment] 2019-04-03 12:21
Yup, same issue here. @bryandowning's workaround (adding an random variable to the query) is working just fine, although this is not an acceptable solution for me.

**Comment by lukasluecke** [comment] 2019-04-24 17:50
I think I'm running into the same issue. I set `error-policy: 'ignore'` for now, but would really appreciate a proper solution.

**Comment by MrLoh** [comment] 2019-05-04 15:53
How is this an unfixed issue for nearly a year now? I guess I'm just gonna just build my own react-apollo solution, the client is just so buggy for anything that goes beyond the basics.

**Comment by hwillson** [comment] 2019-05-04 16:03
@MrLoh Any chance you can provide a small runnable reproduction? In theory, building a repro will take a lot less time to put together than building your own `react-apollo` 🙂. As for RA being buggy for anything beyond the basics, I respectfully disagree, but please feel free to help out with any issues that are running your day - we love PR's!

P.S. > We're also hiring - if you or anyone else wants to help work on Apollo OSS projects full-time, [please apply](https://www.apollographql.com/careers/positions)!

**Comment by MrLoh** [comment] 2019-05-04 19:28
Unfortunately I don't have time to create a reproduction right now, I'm really sorry for that but my startup has enough on it's plate as it is. I can share my current workaround, which has been building my own graphql HOC implementation.

```js
const GraphQL = (query, config) => (Component) => {
	const GraphQLWrapper = (props) => {
		const propsTransform = (config && config.props) || ((props) => props);
		const options = typeof config.options === 'function' ? config.options(props) : config.options;
		const [refetchError, setRefetchError] = React.useState(undefined);
		return (
			<Query query={query} {...options}>
				{({ data, error: queryError, refetch: executeRefetch, ...other }) => {
					// refetch doesn't update the query error, see react-apollo#2070
					const error = refetchError === undefined ? queryError : refetchError;
					const refetch = async () => {
						try {
							await executeRefetch();
							setRefetchError(null);
						} catch (e) {
							setRefetchError(e);
						}
					};
					const offline = Boolean(error?.networkError);
					return (
						<Component
							{...propsTransform({
								...props,
								[config.name || 'data']: {
									...(data ? data : {}),
									offline,
									error,
									refetch,
									...other,
								},
							})}
						/>
					);
				}}
			</Query>
		);
	};

	return GraphQLWrapper;
};
```

Obviously this one issue would not justify building our own react-apollo solution. However react-apollos just doesn't work anymore for us. Supporting offline use cases with reac-apollo is really hard, as offline support means strong coordination between all the different queries in the app and the main architectural decision behind react apollo to tightly couple fetching and cache subscriptions makes this really hard. We need to prefetch all the core data but don't want to trigger updates everywhere due to over fetching. I think relay is just much smarter in many regards for this usecase, but has terrible open source management. Luckily it seems that the implementation of react-apollo has been dramatically simplified with hooks, so I think it's a more feasible option for us to replace react-apollo with a solution that separates fetching and cache subscriptions than trying to work around it for the special offline use cases in our app.

**Comment by kbighorse** [comment] 2019-05-06 21:06
Does this mean that @tmeasday's repro steps are obsolete now? Want to help if we can, we're also anxious to arrive at a solution.

**Comment by BrunoQuaresma** [comment] 2019-05-14 23:55
Use ` fetchPolicy="cache-and-network" errorPolicy="ignore"`works for me. Thanks @frankfaustino

**Comment by Apollo725** [comment] 2019-05-17 18:09
export default compose(
  graphql(sendMessageFromAgentMutation, {name: 'sendMessageFromAgent',  options: {fetchPolicy: "cache-and-network", errorPolicy: "ignore"}}),
  // graphql(getChatroomByTokenQuery, {name: 'getChatroomByToken'}),
  graphql(getAllChatroomsQuery, { name: 'getAllChatrooms', options: {fetchPolicy: "cache-and-network"}})
  
)(MessagingChat)

I used mutation and query inside of compose, but I can not render whole component.
Please help me.

**Comment by dylanwulf** [comment] 2019-05-31 03:53
I was able to make two slightly different reproductions:
1. Calling `replace` from react-router-dom: https://codesandbox.io/s/l94zh
2. Wrapping Query component in Fade from material-ui: https://codesandbox.io/s/8zn26

Both reproductions work with react-apollo v2.5.2 but are broken with react-apollo v2.5.3+.

**Comment by jasonpaulos** [comment] 2019-06-18 20:53
I have confirmed that #3107 also solves this issue. This change will be included in the next react-apollo release, so I'm going to close this issue. Feel free to reply if the issue still remains.

Note: even with this fix, the @dylanwulf's material-ui reproduction does not work perfectly. It shows the error message, then the error disappears after the component finishes fading in. This is a completely separate issue caused by material-ui's `Fade` component forcing the `Query` component to refresh after it fades in. I'm looking into a solution for it now, but it's best discussed in a separate thread.

**Closed by jasonpaulos** 2019-06-18 20:53 UTC
Labels: has-reproduction

**Comment by dylanwulf** [comment] 2019-06-18 21:35
@jasonpaulos Awesome, thank you! Did you want me to create a new issue for discussing the problem with material-ui's `Fade`?

**Comment by jasonpaulos** [comment] 2019-06-18 22:24
@dylanwulf Let's wait until the next version of react-apollo is released to see if it's still a problem. I'm having trouble creating a reproduction of just that issue at the moment, so it'll be a lot easier to tell if it's still a problem once the error recovery bug is fixed.
