### ISSUE TITLE
previousResult is empty object in fetchMore updateQuery

### ISSUE THREAD

**Issue by wukong1995** [apollographql/react-apollo#2386] opened 2018-09-14 03:15 UTC
I try to upgrade apollo in my applications. but an error occurred in pagination.
previousResult is empty object in fetchMore. but there has data in previousResult.

current version:
>"react-apollo": "2.0.4",
>"apollo-cache-inmemory": "^1.2.1",
>"apollo-client": "2.0.2",
>"apollo-link-error": "1.0.0",
>"apollo-link-http": "1.1.0",

 version after upgrade:
>"react-apollo": "^2.1.11",
>"apollo-cache-inmemory": "^1.2.10",
>"apollo-client": "^2.4.2",
>"apollo-link-error": "^1.1.0",
>"apollo-link-http": "^1.5.4",

my code:
```
// client
createClient = () => {
  const httpLink = new HttpLink({
    uri: '/graphql',
    credentials: 'include',
  });

  const fragmentMatcher = new IntrospectionFragmentMatcher({
    introspectionQueryResultData: PARTIAL_SCHEMA,
  });

  const errorLink = onError(({ networkError }) => {
    console.log('networkError:', networkError);
  });

  const link = errorLink.concat(httpLink);
  const client = new ApolloClient({
    link,
    cache: new InMemoryCache({ fragmentMatcher })
  });

  return client;
}


// provider: ApolloWrapper
<ApolloProvider client={this.client}>
  <Component {...this.props} />
</ApolloProvider>
 

// consumer: ApolloWrapper(Component)
@graphql(CQUERY, {
  options: (props) => ({
    variables: {
      cursor: '',
    }
  })
})
@FetchDataWrapper
class CategoryShow extends React.Component {
  render() {
    return (
      <div>.....</div>
    );
  }
}


// use fetchMore in FetchDataWrapper
const { fetchMore, variables } = this.props.data;
// ....
fetchMore({
  variables,
  updateQuery: (previousResult, { fetchMoreResult }) => {
    console.log('previousResult', previousResult);  // will print {}
    
    // ....
  }
})
```

**Comment by townmulti** [comment] 2018-09-27 00:01
@wukong1995 Did you figure this one out?

**Comment by KabirKang** [comment] 2018-11-20 01:54
I've encountered this as well

**Comment by WaldoJeffers** [comment] 2018-12-27 18:07
I can confirm encountering this bug, it seems to be quite random :/
I'm using react apollo v2.1.11

**Comment by popcornAC** [comment] 2019-03-07 02:06
Encountering this as well btw

**Comment by developdeez** [comment] 2019-03-30 21:18
Same. Started when I refactored my code to use PureComponent. Any fix?

**Comment by hwillson** [comment] 2019-09-06 11:44
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!

**Closed by hwillson** 2019-09-06 11:44 UTC

**Comment by willtrking** [comment] 2019-09-19 02:55
Started running into this issue when I upgraded from 2.x to 3.1.1

```
    "@apollo/react-components": "^3.1.1",
    "@apollo/react-hoc": "^3.1.1",
    "@apollo/react-hooks": "^3.1.1",
    "@apollo/react-ssr": "^3.1.1",
```

Are my current deps.

**Comment by sangdth** [comment] 2020-01-02 13:49
I'm using 3.1.3 in React Native and have this problem also.
