### ISSUE TITLE
Calling writeQuery does not update the props

### ISSUE THREAD

**Issue by scottmcpherson** [apollographql/react-apollo#2209] opened 2018-07-25 01:13 UTC
**Intended outcome:**
`writeQuery` should refresh the props data. You can see [here](https://github.com/scottmcpherson/react-graphql-apollo-semanticui-starter/blob/3be17f74071dc347164d1ac825c8503bc075ee8b/client/src/components/AuthWrapper/index.js#L19) that when a user logs in, this function gets called with the user. I'm trying to call `writeQuery()` to update the currentUser. 

I've also tried calling `writeQuery` directly on the `client` and `store`, but no luck.

**Actual outcome:**
`writeQuery` does not refresh the props data

**How to reproduce the issue:**
You can clone this repo to see the issue: https://github.com/scottmcpherson/react-graphql-apollo-semanticui-starter and checking out commit `3be17f74071dc347164d1ac825c8503bc075ee8b`

**Version**
"apollo-boost": "0.1.10",
"react-apollo": "2.1.9",

**Comment by scottmcpherson** [comment] 2018-07-25 03:34
I got around this for the time being by calling refetch on the query

**Comment by captDaylight** [comment] 2018-10-04 15:44
@scottmcpherson I've been struggling with the same issue.

I have a query `GET_USER` on page load to see if the user is logged in. If not, the header show log in/sign up... if so it shows log out. If the user is not logged in, then goes to the login page I tried doing something like this:

``` jsx
<Mutation
  mutation={LOGIN}
  variables={{ email, password }}
  update={(cache, { data }) => {
    cache.writeQuery({
      query: GET_USER,
      data: { user: data.login }
    });
  }}
> 
  // ... form
```

here are the queries that correspond:

``` js
import gql from 'graphql-tag';

export const GET_USER = gql`
  {
    user {
      id
      name
      email
      __typename
    }
  }
`;

export const LOGIN = gql`
  mutation LoginMutation($email: String!, $password: String!) {
    login(email: $email, password: $password) {
      id
      name
      email
      __typename
    }
  }
`;
```

However, when I log in successfully, that update does not update the query (as far as I can tell, assuming that the header should switch over to the logged out state as it's referencing the same query). The data that I have coming back after login in `data.login` is exactly the same format as my `GET_USER` query.

I'm going to try to refetch from the server for now too but this feels redundant as you said...

**Comment by captDaylight** [comment] 2018-10-04 15:45
[This thread](https://github.com/apollographql/apollo-client/issues/1900) is about refetching the user after log in, but fundamentally that feels like a redundant call.

**Comment by rosskevin** [comment] 2018-12-26 21:18
Duplicate of #2099

**Comment by rosskevin** [comment] 2018-12-27 20:42
I proved the bug upstream is not a bug, so back to looking at other cases to find it.

**Comment by danilobuerger** [comment] 2018-12-27 21:34
The only thing you have to do to get it working is:
```
diff --git a/server/data/resolvers.js b/server/data/resolvers.js
index b349a89..066f137 100644
--- a/server/data/resolvers.js
+++ b/server/data/resolvers.js
@@ -9,7 +9,7 @@ const resolvers = {
   Query: {
     currentUser: async (root, {}, { user }) => {
       if (!user) {
-        throw new AuthenticationError('Invalid token')
+        return null
       }
       const loginInUser = await User.findOne({ where: { id: user.id } })
       return loginInUser
```

**Comment by rosskevin** [comment] 2018-12-27 21:42
Thanks for digging in @danilobuerger.  I'm closing given that solution/information.

**Closed by rosskevin** 2018-12-27 21:42 UTC
Labels: has-reproduction

**Comment by shuzootani** [comment] 2019-09-03 04:53
@scottmcpherson I still can't make it work although server returns `null` instead of error.
https://github.com/apollographql/react-apollo/issues/2209#issuecomment-450233682

I'd appreciate if anyone could tell me what I'm missing.

my code looks like this

in Parent component that fetches a cart

```
  const { data: { cart } } = useQuery(cartQuery, { variables: { id: cartId } })
  .
  .
  .
  return ( <Child /> )
```

in the Child component that add items to cart
```
  const [addToCart] = useMutation(addToCartMutation, {
    update(cache, { data: { addToCart: cart } }) {
      const updated = cache.readQuery({ query: cartQuery, data: cart, variables: { id: cart.id } })
      cache.writeQuery({ query: cartQuery, data: updated, variables: { id: cart.id } })
      console.log({ client }) // cache in client is updated.
      return cart
    },
  })
```
