### ISSUE TITLE
Query from cache makes component render twice

### ISSUE THREAD

**Issue by vladshcherbin** [apollographql/react-apollo#1069] opened 2017-09-06 13:23 UTC
**Intended outcome:**

Example app has a `TopComponent`, which executes query. This component has a nested `BottomComponent`, which also executes the same query.

I expect `BottomComponent` to render only once since data is fetched from cache or at least to have some kind of `loading` / `complete` state.

**Actual outcome:**

`TopComponent` executes query. When `loading` prop is false, `BottomComponent` is rendered. It takes query from cache and renders the same component **twice** with the same props.

**How to reproduce the issue:**

The app is as simple as that:

```jsx
// App
const App = () => {
  const networkInterface = createNetworkInterface({
    uri: 'http://admin.localhost:3000/graphql'
  })
  const apolloClient = new ApolloClient({ networkInterface })
  const store = configureStore(apolloClient)

  console.log('render app')

  return (
    <ApolloProvider store={store} client={apolloClient}>
      <TopComponent />
    </ApolloProvider>
  )
}

// TopComponent
const TopComponent = ({ data: { loading, error } }) => {
  console.log('render top component', loading, error)
  if (loading) {
    return <p>loading</p>
  }

  if (!loading && error) {
    return <p>error</p>
  }

  console.log('before render bottom component')
  return (
    <BottomComponent />
  )
}

export default graphql(query)(TopComponent)

// BottomComponent
const BottomComponent = ({ data: { loading, error } }) => {
  console.log('render bottom component', loading, error)

  return (
    <p>bottom component</p>
  )
}

export default graphql(query)(BottomComponent)
```

The result output:

![screen shot 2017-09-06 at 4 07 01 pm](https://user-images.githubusercontent.com/6711845/30113488-8eb08cae-931d-11e7-9bab-5e7b9e5fc8f8.png)

As you can see, `BottomComponent` renders twice with the same props.

**Version**
- apollo-client@1.9.2
- react-apollo@1.4.15

**Comment by lostpebble** [comment] 2017-09-08 09:40
Yep running into this issue as well it seems. Causing havok trying to get CSS-in-JS styles working with fela - as the style renderer creates different stylesheets on each render now which collide with each other and the styles get all muddled.

I'm pretty sure this is also related to the previous issue I created #996 , where I noticed two renders being enacted on both server and client.

I uploaded an example project that shows it happening, here: https://github.com/lostpebble/apollo-two-render

**Comment by VladShcherbin** [comment] 2017-09-29 10:08
What a useless bot, wow. What activity do you expect, it's an issue tracker, not a chat room.

**Comment by VladShcherbin** [comment] 2017-10-27 07:21
+

**Comment by ducarroz** [comment] 2017-11-07 22:17
I am experiencing the same issue!

Looks like GraphQL subscribes to the query on `GraphQL.componentDidMount` which will force a render once the subscription returns data (via `next`). This despite it already got the query result when calling `GraphQL.dataForChild` during the initial `GraphQL.render`.

**Comment by VladShcherbin** [comment] 2017-11-28 22:43
🤦‍♂️

**Comment by ex3ndr** [comment] 2017-12-07 20:48
Any news?

**Comment by garethbradley** [comment] 2018-01-17 16:26
Same issue - I'm getting two calls to every Mutation and Query

**Comment by janzheng** [comment] 2018-02-09 23:40
same, no idea how to solve. No idea if a Vue problem or not, but it's hard to track down

**Comment by jameskennethrobinson** [comment] 2018-02-23 21:07
Would love some news on this issue!

**Comment by johnunclesam** [comment] 2018-02-25 21:08
+1

**Comment by johnunclesam** [comment] 2018-02-26 10:54
Maybe something like this? https://github.com/apollographql/react-apollo/issues/1718

**Comment by Kisepro** [comment] 2018-04-05 05:33
No news ?

**Comment by kcouliba** [comment] 2018-06-27 14:02
I kind of encountered that issue recently using the [Query Component](https://www.apollographql.com/docs/react/api/react-apollo.html#query) and reading the documentation I noticed I was using the fetchPolicy: 'cache-and-network'.
That configuration make the component render with cached data, then trigger the loading, then renders again with fresh data from the server.
Going with fetchPolicy: 'network-only' did the trick in my case.
I hope this could help.

**Comment by GarretRCorbett** [comment] 2018-07-25 17:01
I found this thread because I had a similar issue where I had 3 components on a view where the top component would conditionally render which of my bottom two components were displayed. Within those 2 bottom components though, I had a `componentWillMount()` function that fetched the data I needed :

``` 
componentWillMount() {
    this.props.dispatch(fetchAllObjectiveDataWithRedux())
    this.props.dispatch(fetchAllNotesDataWithRedux())
}
```


After reading the comment by @kcouliba I realized my mistake and removed my `componentWillMount() `functions from within the bottom two components to a new wrapper component that wrapped all 3 of my components. It was a simple fix that solved this issue for me. Hopefully this will help anyone else who stumbles across this thread having the same issue.

**Comment by hebuliang** [comment] 2018-07-26 06:00
Did not get this issue with `apollo-client "^2.3.5"` and `react-apollo@^2.1.8`

**Comment by zenVentzi** [comment] 2018-11-12 04:03
Getting the issue with apollo-client "^2.3.5" and react-apollo@^2.1.9

**Comment by takticcode** [comment] 2018-12-05 09:38
Any news?

**Comment by zxfred** [comment] 2019-03-12 07:03
same

**Comment by llezhava** [comment] 2019-03-21 14:14
Any news?

**Comment by mixed** [comment] 2019-03-28 11:32
meet same issue.

**Comment by dipta007** [comment] 2019-03-28 19:54
Any news on this?

**Comment by indieocean** [comment] 2019-04-04 20:35
1+

**Comment by hjaltiunnar** [comment] 2019-04-12 16:47
+1

**Comment by danielbischoff** [comment] 2019-04-23 11:53
+1

**Comment by carlosalvarez91** [comment] 2019-04-30 00:16
+1

**Comment by maabed** [comment] 2019-04-30 23:06
+1

**Comment by laurenmayers** [comment] 2019-05-03 16:06
+1

**Comment by djemeljanovs** [comment] 2019-05-08 11:30
+1

**Comment by austincondiff** [comment] 2019-05-08 15:47
+1

**Comment by bke-daniel** [comment] 2019-05-24 07:13
+1

**Comment by praisegeek** [comment] 2019-05-26 16:47
+1

**Comment by creadoit** [comment] 2019-05-27 16:27
+1

**Comment by mpgon** [comment] 2019-06-11 16:52
Same. When migrating from "apollo-client": "2.4.2" to "2.5.1"

**Comment by jasonpaulos** [comment] 2019-06-19 20:37
It would be very helpful if someone could provide an up-to-date reproduction of this issue, either as a github repo or in codesandbox.io. Thanks!

**Comment by vladshcherbin** [comment] 2019-06-19 22:49
Here is a reproduction of a very similar example I had when opened this issue:

- react-apollo 2.1.0, issue exists (original test was on 1.4.15)
https://codesandbox.io/s/react-apollo-issue-reproduction-210-s0y2d

- react-apollo 2.1.1, issue doesn't exist in this example
https://codesandbox.io/s/react-apollo-issue-reproduction-211-rbis9

- react-apollo 2.5.6, issue doesn't exist in this example
https://codesandbox.io/s/react-apollo-issue-reproduction-256-j7p85

So, the initial example doesn't have this issue, seems to be fixed.

Maybe someone else can use this reproductions and add an example where it's not working as expected.

**Comment by bke-daniel** [comment] 2019-06-21 08:02
I made a fork of @vladshcherbin last example. Added cache and used HOCs so that we're having a setup as in our app (updated everything to latest).
For me / us the issue seems to be solved too  – double checked it with our app.
See: https://codesandbox.io/s/react-apollo-issue-reproduction-256-mch43

Thank you!

**Comment by mpgon** [comment] 2019-07-09 07:50
@jasonpaulos here's an isolated example. https://codesandbox.io/embed/mocked-apollo-pl90t 
My problem specifically occurs under a MockedProvider with no mocked responses for a query, using apollo-client `2.6.3` If you open the console you'll see the output
```
loading: true, error: false, data: {} 
loading: false, error: true, data: undefined 
loading: false, error: true, data: undefined 
```
showcasing the extra `loading: false, error: true` render. However, if you go to the dependencies on the left and change the apollo-client version to, for example, `2.4.2`, you can see the component logs the expected output
```
loading: true, error: false, data: {} 
loading: false, error: true, data: undefined 
```

**Comment by hwillson** [comment] 2019-09-06 11:54
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!

**Closed by hwillson** 2019-09-06 11:54 UTC
Labels: reproduction-needed

**Comment by bantingGamer** [comment] 2020-05-21 08:32
> React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!


This is still an issue. i have upgraded to all the latest packages. 
I dont understand why it just doesn't work like expected. HOC cache-and-network causes my component to mount twice and then my subscriptions subscribe twice which is not the behavior im looking for. please can anyone give me a work around?

**Comment by bantingGamer** [comment] 2020-05-21 10:33
if anyone is still struggling with the issue i found a work around by using a hook instead of a HOC. The hook has a callback executed once your query successfully completes. onCompleted. Ive provided my code example. good luck!
```
import {
  useQuery,
  useApolloClient
} from '@apollo/react-hooks';

  const { loading, error, data } = useQuery(meQuery, {
    fetchPolicy: 'cache-and-network',
    onCompleted: () => subscribeToSubscriptions()
  });
```

**Comment by Sergio16T** [comment] 2020-07-10 22:42
Working Next.js 9.3.3 and React Apollo 3.1.3 I'm also experiencing this

**Comment by collegewap** [comment] 2020-07-11 10:03
Even I am experiencing the same with apollo-client 2.6.10 and next 9.4.4

Here is an example: https://github.com/collegewap/next.js/tree/canary/examples/with-apollo

This is forked from the official example of Nextjs and added just the logs

Demo: https://nextjs-apollo-issue.vercel.app/ 

When you click on load more, the component renders thrice. Whereas it should render only twice, once while loading and once after loading.

![image](https://user-images.githubusercontent.com/9767383/87221675-76d89f80-c38b-11ea-9bf0-b92dd0f1d88c.png)
