### ISSUE TITLE
TypeScript - props function of graphql HOC fail type checking

### ISSUE THREAD

**Issue by lirbank** [apollographql/react-apollo#2083] opened 2018-06-08 18:05 UTC
The example in the docs does not work, and I have not found a way around it either:

https://www.apollographql.com/docs/react/recipes/static-typing.html#props

Reproduction:

https://stackblitz.com/edit/react-ts-rpb3ex

TS Error:
```
Argument of type '{ options: ({ episode }: InputProps) => { variables: { episode: string; }; }; props: ({ data }: O...' is not assignable to parameter of type 'OperationOption<InputProps, Response, Variables, ChildDataProps<InputProps, Response, Variables>>'.
  Types of property 'props' are incompatible.
    Type '({ data }: OptionProps<InputProps, Response, OperationVariables>) => { error?: ApolloError; netwo...' is not assignable to type '(props: OptionProps<InputProps, Response, OperationVariables>, lastProps?: void | ChildDataProps<...'.
      Type '{ error?: ApolloError; networkStatus: number; loading: boolean; variables: OperationVariables; fe...' is not assignable to type 'ChildDataProps<InputProps, Response, Variables>'.
        Object literal may only specify known properties, and 'error' does not exist in type 'ChildDataProps<InputProps, Response, Variables>'.
```

**Version**

* apollo-client@2.3.2
* react-apollo@2.1.4

**Comment by Skovy** [comment] 2018-06-12 04:08
@lirbank hopefully this PR will resolve this issue: https://github.com/apollographql/react-apollo/pull/2094

A bit of a sledgehammer 🔨 approach you could take in the short term would be to use `any`:

```typescript
graphql<InputProps, Response, Variables, ChildProps>(HERO_QUERY, {
  options: ({ episode }) => ({
    variables: { episode }
  }),
  props: ({ data }) => ({ ...data } as any)
});
```

Based off that example, it looks like a slightly more correct type cast might look something like this:

```typescript
type Props = ChildDataProps<InputProps, Response, Variables>;

graphql<InputProps, Response, Variables, Props>(HERO_QUERY, {
  options: ({ episode }) => ({
    variables: { episode }
  }),
  props: ({ data, ownProps }) => ({ data, ...ownProps} as Props)
});
```

**Comment by skovy** [comment] 2018-07-16 00:21
@lirbank FYI the above PR was merged recently. Hopefully, it resolves the issue for you! Is this issue good to close?

**Comment by jameslaneconkling** [comment] 2018-07-17 15:23
I just forked @lirbank 's example and bumped `react-apollo` to `2.1.9` and it's still an issue.

https://stackblitz.com/edit/react-ts-f276th?file=index.tsx

**Comment by jameslaneconkling** [comment] 2018-07-18 13:20
👍 good to know.  What's the best way to track releases?

**Comment by brian-lives-outdoors** [comment] 2018-07-22 02:52
I just bumped into this as well and confirmed that #2094 fixes the issue for me.

Looking forward to this being released, thanks @skovy!

**Comment by jameslaneconkling** [comment] 2018-07-22 19:47
@brian-lives-outdoors how are you testing against the latest snapshot?  It looks like the build artifacts aren't checked in to github, and I haven't seen instructions for local builds.  Thanks for the help!

**Comment by brian-lives-outdoors** [comment] 2018-07-23 04:56
@jameslaneconkling I'm not running a local build, I just tracked down the typing issue and fixed it in my local package, and then saw that @skovy's pull request made the same changes on master.

There's no actual code changes with the fix, just type definitions, so doing the type assertion on the object you return from the props function works fine until the new release.

If you want to preview the fix you can change the props type of OperationOption in your local react-apollo/types.d.ts from this:
```typescript
props?: (props: OptionProps<TProps, TData>, lastProps?: TChildProps | void) => TChildProps;
```
to this:
```typescript
props?: (props: OptionProps<TProps, TData, TGraphQLVariables>, lastProps?: TChildProps | void) => TChildProps;
```
If I'm not mistaken, that is the only change from this fix that will show up in the release.

**Comment by lirbank** [comment] 2018-07-23 15:53
@skovy thanks for fixing this! I am moving from HOCs to the render props pattern so I don't really have the issue anumore, but I tried to upgrade react-apollo on the Stackblitz example - which, as @jameslaneconkling already has pointed out does, not work yet since the new release has not been published yet. It should be easy to confirm the fix once the new version has been published.

Thanks a lot for fixing the issue!

**Comment by amwill04** [comment] 2018-09-07 14:58
Dont know if I am missing something but the example found 
[https://www.apollographql.com/docs/react/recipes/static-typing.html#props](https://www.apollographql.com/docs/react/recipes/static-typing.html#props) still fails type checking with the following:
```
TS2345: Argument of type '{ options: ({ episode }: InputProps) => { variables: { episode: string; }; }; props: ({ data }: OptionProps<InputProps, Response, Variables>) => {}; }' is not assignable to parameter of type 'OperationOption<InputProps, Response, Variables, ChildDataProps<InputProps, Response, Variables>>'.
[app]   Types of property 'props' are incompatible.
[app]     Type '({ data }: OptionProps<InputProps, Response, Variables>) => {}' is not assignable to type '(props: OptionProps<InputProps, Response, Variables>, lastProps?: void | ChildDataProps<InputProps, Response, Variables> | undefined) => ChildDataProps<InputProps, Response, Variables>'.
[app]       Type '{}' is not assignable to type 'ChildDataProps<InputProps, Response, Variables>'.
[app]         Type '{}' is not assignable to type 'InputProps'.
[app]           Property 'episode' is missing in type '{}'.
```

checked the `types.d.ts` file to make sure that it was updated with @brian-lives-outdoors fix.

The only way I "fixed" it was using `ChildProps` as opposed to `ChildDataProps`

```
const withCharacter = graphql<InputProps, Response, Variables, ChildProps<InputProps, Response>>(HERO_QUERY, {
    options: ({ episode }) => ({
        variables: { episode },
    }),
    props: ({ data, ownProps }) => ({ ...data, episode: ownProps.episode }),
});
```

**Comment by reverie** [comment] 2018-10-04 00:30
@lirbank What's an example of the render props pattern? I'm trying to move away from the `graphql` HOC.

**Comment by lirbank** [comment] 2018-10-09 17:05
@reverie check out these links for the general concept of render props:

https://reactjs.org/docs/render-props.html
https://cdb.reacttraining.com/use-a-render-prop-50de598f11ce

Apollo specific:
https://www.apollographql.com/docs/react/essentials/queries.html#basic
https://www.apollographql.com/docs/react/essentials/mutations.html#basic

**Comment by rosskevin** [comment] 2018-12-26 21:49
Closing - housekeeping

**Comment by amwill04** [comment] 2019-02-21 22:42
I dont really understand why this is closed.

Either the `typings` are incorrect or the documentation is.

**Comment by joshycube** [comment] 2019-03-18 17:52
The documentation is utterly rubbish.

**Comment by MrToph** [comment] 2019-06-25 14:06
Not sure why @joshycube 's comment is marked as disruptive.

The example from the apollo-typescript documentation has type errors and there's no clear way how to resolve them anywhere.

It would be nice if we could open this issue again

**Comment by hwillson** [comment] 2019-06-25 15:02
@MrToph it was marked as disruptive because his original non-edited comment was:

> The documentation is utterly rubbish.

We're always looking for ways to improve the docs, but getting new features in and keeping the docs up to date is definitely a balancing act, and requires a significant amount of developer effort. We're open to working on suggestions to improve the docs, or better yet merging community PR's in that do that, but saying the docs are `utterly rubbish` is condescending to the countless developers who have taken time out of their day to help make the docs better. 

Please consider opening a new issue with specific details around the areas of the docs that are causing you grief, and we'll take a look. Thanks!

**Comment by amwill04** [comment] 2019-06-25 17:16
@hwillson 

If that was the original comment then yeah - that is disruptive and frankly insulting.

I would question why there needs to be another issue opened. As my comment above states a clear example of either the docs been wrong/unclear or the `types` being incorrect. My question was looking for guidance as to which it is. If I got direction then I’m more than happy to contribute.

**Comment by hwillson** [comment] 2019-06-25 18:57
Fair enough @amwill04 - re-opening. 

On a related note, we're working on new docs structure changes that will be launching when React Apollo 3 is published. We're going to include more TS examples across the board, alongside vanilla JS examples (we'll have a code sample language switcher in place). All code samples will be reviewed/updated and verified to be accurate.

**Comment by hwillson** [comment] 2019-09-06 11:49
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!

**Closed by hwillson** 2019-09-06 11:49 UTC
Labels: has-reproduction
