### ISSUE TITLE
Query component's render prop variables argument never changes after updating via fetchMore

### ISSUE THREAD

**Issue by jdmoody** [apollographql/react-apollo#2249] opened 2018-08-06 00:02 UTC
**Intended outcome:**
After updating the variables of a Query via `fetchMore`, I would expect the variables render prop argument to also update.

**Actual outcome:**
The variables render prop argument always matches the `Query` component's variables prop, even when the query's variables have been updated by `fetchMore`.

**How to reproduce the issue:**
https://codesandbox.io/s/x2q073m0kp
(This example is a bit contrived to keep it simple. My actual use-case requires the data to be an array)

As a workaround, I tried updating the `variables` in React state after the `fetchMore` `updateQuery` callback was fired, but this causes the data to be out of sync with the variables while `Query` is updating the Apollo store.

Is this a bug, or am I just using the wrong approach? Thank you!

**Version**

* apollo-client@2.3.7
* react-apollo@2.1.3

**Comment by Lepozepo** [comment] 2018-11-11 18:47
@jdmoody This seems to be the intended behavior but it's terrible. Sub-components could definitely require knowledge of how the query is being filtered/sorted or otherwise manipulated by input to render a visual representation of that change after a `fetchMore`. This seems especially true to anything that paginates with a `cursor`.

**Comment by myhendry** [comment] 2018-11-23 12:04
I used the rendered props approach and also encountered the component variables not updating. after i rewrite to hoc pattern, it worked. However, i thought the preferred approach going approach is using the rendered props approach? Apollo website's examples are using the rendered props way

**Comment by evans** [comment] 2018-12-27 23:04
I ran into this issue as well. https://codesandbox.io/s/9l8221k15o is another reproduction that might be a more typical case of load more. I might be able to take a look later next week. @hwilson if you get to it, that would be awesome

**Comment by hwillson** [comment] 2019-09-06 11:42
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!

**Closed by hwillson** 2019-09-06 11:42 UTC
Labels: has-reproduction
