### ISSUE TITLE
Query error in one component affects other components

### ISSUE THREAD

**Issue by mbrowne** [apollographql/react-apollo#2176] opened 2018-07-11 19:27 UTC
**Intended outcome:**

On some pages in our app, we have two components calling the same query with different fields, let's call them Component1 and Component2. If the query for Component2 returns an error, I expect that the `<Query>` in Component2 will receive that error. Peudocode:

    const GALLERY_QUERY1 = gql`
        query {
            gallery(id: "demo") {
                data {
                    id
                    name
                }
            }
        }
    `

    class Component1 extends React.PureComponent {
        render() {
            return (
                <Query query={GALLERY_QUERY1}>
                    {result => {
                        ...
                        if (!result.data.gallery) {
                            return <NotFound />
                        }
                        return <Component2 />
                    }}
                </Query>
            )
        }
    }
    
    const GALLERY_QUERY2 = gql`
        query {
            gallery(id: "demo") {
                data {
                    id
                    artworks {
                        id
                        title
                    }
                }
            }
        }
    `

    class Component2 extends React.PureComponent {
        render() {
            return (
                <Query query={GALLERY_QUERY2}>
                    // If this query returns an error, it should be available here...
                    ...
                </Query>
            )
        }
    }

**Actual outcome:**

When the query in Component2 returns an error, it causes Component1 to re-render because `gallery` is now null. Unfortunately this happens _before_ the query result is passed to Component2's Query. So in this example, `<NotFound>` is rendered instead of having an `error` object that can be handled by Component2.

**How to reproduce the issue:**

See above code example. I can create an example repo if this isn't clear enough.

**Notes:**

Here's a sequence of what's happening, as far as I can tell:

1. GALLERY_QUERY1 executes successfully and Component1 renders
2. GALLERY_QUERY2 is requested
3. Server returns an error in response to GALLERY_QUERY2
4. Response to GALLERY_QUERY2 causes the render prop in Component1 to re-render, because both queries are requesting `gallery`. (Query in Component2 is still in `loading` state at this time.)

This seems like a bug...re-rendering the GALLERY_QUERY1 query would make sense if there were a successful response from the server, but it seems like it should be ignored in this case since there was an error. Is there any way to work around this?

**Version**

* apollo-client@2.3.5
* react-apollo@2.1.9

**Comment by mbrowne** [comment] 2018-07-20 21:39
Update: I have discovered that this only happens when `errorPolicy` is set to `all` for `watchQuery`. I think this is probably still a bug, but disabling that option (going back to the default) will be our workaround for the time being. i.e. with the `watchQuery` part commented out, it works:

```
const client = new ApolloClient({
    cache,
    link,
    defaultOptions: {
        // watchQuery: {
        //     errorPolicy: 'all',
        // },
        query: {
            errorPolicy: 'all',
        },
        mutate: {
            errorPolicy: 'all',
        },
    },
})
```

**Comment by rosskevin** [comment] 2018-12-28 20:42
If one component has data and is observing the cache, it will update when the cache is updated.  The cache though is _not_ updated when there is an error.  You may manually update the cache with `writeQuery` or `writeData` directly on the `client` to suit your specific needs.

**Comment by mbrowne** [comment] 2018-12-28 20:53
@rosskevin Thanks. So why then does Component1 update in the case of an error (in my example) but not Component2, which contains the query that caused the error? If errors don't trigger cache updates, I would expect neither component to update. Also, in this case where should the manual cache updating code go, if we were to use that approach?

**Comment by rosskevin** [comment] 2018-12-28 21:03
@mbrowne I think I misunderstood and you are right.  My expectation is that C1 observing should not update when C2 errors on query.

@danilobuerger do you have thoughts on this scenario.

**Comment by danilobuerger** [comment] 2018-12-29 07:14
@mbrowne Could you provide a minimal working example please?

**Comment by mbrowne** [comment] 2019-01-02 16:05
Sure, here you go (be sure to check out this specific branch):
https://github.com/mbrowne/react-apollo-error-template/tree/cache-error

The `errorPolicy` option that triggers the issue is set in src/index.js

**Comment by danilobuerger** [comment] 2019-01-07 09:57
I can reproduce the issue.

**Comment by danilobuerger** [comment] 2019-01-07 10:02
Also reproducible with just apollo-client. So bug is in apollo-client not in react-apollo.

**Comment by danilobuerger** [comment] 2019-01-07 10:13
This might not be a bug but intended behavior.

The second graphql query returns:
```
{
	"errors": [{
		"message": "Demo server-side error",
		"locations": [{
			"line": 5,
			"column": 7
		}],
		"path": ["gallery", "data", "artworks"]
	}],
	"data": {
		"gallery": null
	}
}
```

https://www.apollographql.com/docs/react/features/error-handling.html
> all: Using the all policy is the best way to notify your users of potential issues while still showing as much data as possible from your server. It saves both data and errors into the Apollo Cache so your UI can use them.

So it saves the `data`. Since `data == { "gallery": null }`, this gets written into cache, thus triggering the observable for the outer component.

**Comment by danilobuerger** [comment] 2019-01-07 10:13
@hwillson @benjamn Could we get your input here, please?

**Comment by mbrowne** [comment] 2019-01-07 17:21
I think the correct behavior would be for it to return the data (triggering the cache update) but _also_ to return the error. Currently the error never makes it to either component in this case.

**Comment by danilobuerger** [comment] 2019-01-07 17:35
Right now it behaves as documented. If you were to return partial results on error, your provided repo would work. The question is, what to do if there are no partial results. That behavior should be changed in my opinion (but again, is behaving as documented right now).

**Comment by hwillson** [comment] 2019-01-31 17:47
Thanks for looking into this @mbrowne @danilobuerger. I'm going to label this as a bug. It's quite reasonable to expect that `Component1` should get access to the reported error.

**Comment by hwillson** [comment] 2019-09-06 11:42
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!

**Closed by hwillson** 2019-09-06 11:42 UTC
Labels: bug, confirmed, has-reproduction, help-wanted

**Comment by mbrowne** [comment] 2019-09-06 19:53
This is still an issue. The issue is in apollo-client, not react-apollo. I updated my demo repo to use the latest versions of apollo-client and react-apollo, and refactored to hooks:

https://github.com/mbrowne/react-apollo-error-template/tree/cache-error

**Comment by mbrowne** [comment] 2019-09-06 19:54
Updated my previous comment—I had said the issue was in apollo-client, but that wasn't correct (I was confused). As far as I can tell this is still an issue with the latest version of react-apollo.
