### ISSUE TITLE
Apollo doesn't support Date() in input variable

### ISSUE THREAD

**Issue by patrickml** [apollographql/react-apollo#654] opened 2017-04-25 04:36 UTC
So when double clicking/re-clicking a link that loads a gql query I am expirencing something really odd where the second load is missing the result from they query under `this.props.data` 

Here is a gif of this in action

https://cl.ly/0O3p0y0D1122

And the error is undefined so there isn't an error and i'm not seeing the data re-requested in the network tab

## Steps to Reproduce

```js
import { graphql } from 'react-apollo';
import gql from 'graphql-tag';
import EventList from 'components/Bots/Events';

const query = gql`
  query BotEventPagination($botId: ID!, $cursor: Date!, $page: Int!, $per: Int!, $config: TableConfig, $filter: JSON) {
    bot(botId: $botId) {
      id
      name
      properties {
        key
        type
        event
      }
      events(cursor: $cursor, page: $page, per: $per, config: $config, filter:$filter) {
        cursor
        count
        totalPages
        documents {
          id
          platform
          platformId
          silverId
          organizationId
          event
          createdAt
          values
          botId
          user {
            firstName
            lastName
            email
          }
        }
      }
    }
  }
`;

export default graphql(query, {
  options: ({ params: { botId } }) => ({
    variables: {
      botId,
      cursor: new Date(),
      page: 1,
      per: 10,
      config: {
        sort: {
          key: 'createdAt',
          dir: -1,
        },
      },
      filter: {},
    },
  }),
})(EventList);
```

### Expected Behavior

Existing cached data reused and available

### Version
- apollo-client@1.0.4
- react-apollo@1.1.0

**Comment by patrickml** [comment] 2017-04-25 14:10
So the issue is passing in the `new Date()` as a param. The client seems to have an issue when you pass date types through.

**Comment by cvle** [comment] 2017-04-25 16:34
We ran into a similar/same issue.

We got an empty query result after a certain mutation using either `updateQueries` or `update` with no errors. It used to work before we changed the fragment definition.

This fragment in our query caused the empty query result after applying our mutation:
```javascript
const commentViewFragment = gql`
  fragment commentView on Comment {
    id
    body
    created_at
    status
    tags {
      name
    }
    user {
        id
        name: username
    }
    action_summaries {
      __typename
      count
      current_user {
        id
        created_at
      }
    }
  }
`;
```

Meanwhile putting the `action_summaries` definition in a separate fragment works without issues:

```javascript

const actionSummaryViewFragment = gql`
  fragment actionSummaryView on ActionSummary {
    __typename
    count
    current_user {
      id
      created_at
    }
  }
`;

const commentViewFragment = gql`
  fragment commentView on Comment {
    id
    body
    created_at
    status
    tags {
      name
    }
    user {
        id
        name: username
    }
    action_summaries {
      ...actionSummaryView
    }
  }
```

Also removing `created_at` from `action_summaries` it resolved our issue.
This works for us now, because we are not using it atm.

https://github.com/coralproject/talk/pull/526/commits/15d410ba12932e21a28ebd92d1bef4dd1a2b2e9d

**Comment by patrickml** [comment] 2017-04-25 16:54
@cvle our fix was to do `new Date().toISOString()` when passing the variable

**Comment by cvle** [comment] 2017-04-25 17:22
@patrickml Thanks! Will try it out when we run into this again.

**Comment by helfer** [comment] 2017-04-25 19:08
@patrickml did you only start seeing this issue after the last update? What's the most recent version where this bug does **not** occur?

**Comment by patrickml** [comment] 2017-04-25 19:43
@helfer I wish I could be more useful here, but we had just implemented our own version of pagination so we didn't have this issue until then. I was able to widdle it down to passing in `Date` as a `Date` and not a string

**Comment by helfer** [comment] 2017-04-25 23:07
My guess is that the issue here is that Apollo Client can't magically know how to serialize things, which means it's up to the developer to make sure the variable is properly serialized before passing it to Apollo. I'm inclined to close this issue, but I do think we need a much better error message when things like that happen, so I'd love to have a simple reproduction that I can play around with to figure out where to intercept inputs like this. Could someone provide a really simple reproduction of this with [react-apollo-error-template](https://github.com/apollographql/react-apollo-error-template)? That would help a great deal!

**Comment by patrickml** [comment] 2017-04-25 23:17
Well that's just the thing the query works the first time it's when the
cache is being accessed that it became a problem. But I will try to get
together an example sometime this week

**Comment by helfer** [comment] 2017-04-25 23:21
Hm, that's interesting, but it makes perfect sense. Can you look at what the Date gets serialized to in the request? I assume it's something like `"Tue Apr 25 2017 16:18:57 GMT-0700 (PDT)"`. If it gets put in the store under that, the second query wouldn't be able to read it, unless it also serializes the date before checking (which I thought it did).

I now agree that this is most likely a bug that needs fixing, and a reproduction would really help a great deal to figure out what's really going on inside the client. Thanks @patrickml !

**Comment by thebigredgeek** [comment] 2017-04-26 01:53
@helfer The de-facto way of handling stuff like this is by calling `toJSON` on complex types like `Date` objects.  Almost every single complex type has a `toJSON` method.  In the case of `Date`, `toJSON` returns an ISO date.  A simple fix for this would be to call `JSON.parse(variables)` within `HTTPNetworkInterface`

**Comment by helfer** [comment] 2017-04-26 02:21
@thebigredgeek I'm a bit dubious whether this will fix the issue here (after all the problem is with loading from cache, not the network interface), but if you think it will work, go for it! Once we have a reproduction, you can try it out.

**Comment by thebigredgeek** [comment] 2017-04-26 02:25
Ah, I didn't read this properly then.  However, even with the cache, I think it makes sense to serialize into string form using the same method described above.  So the fix might need to be in two places?

**Comment by patrickml** [comment] 2017-04-26 02:28
@helfer, since I'm not able to create that example yet, here, is a photo of the cache.

Now this photo was taken from the Apollo Chrome Extention so I'm not sure if they do something fancy here 

![image](https://cloud.githubusercontent.com/assets/7581369/25415563/79258b9e-2a06-11e7-8982-c14c645c5437.png)

**Comment by cvle** [comment] 2017-04-26 13:21
The issue I encountered also only involves the cache and our custom Scalar type `Date`. I'm trying to reproduce with a simplified example.

**Comment by cvle** [comment] 2017-04-26 15:32
Not entirely sure if it is related. My issue turned out to be a bit different: https://github.com/apollographql/react-apollo/issues/658.

**Closed** 2017-09-05 14:55 UTC
Labels: bug, no-recent-activity

**Comment by schmeter** [comment] 2018-08-02 09:43
still broken

**Comment by the-simian** [comment] 2019-01-18 21:36
This issue has come back in the latest version you have to do ` .toISOString()` on your Date objects or it will only send a {}
