### ISSUE TITLE
Component is rendered a second time, graphql object is undefined, when accessing nested property of null property

### ISSUE THREAD

**Issue by vonwao** [apollographql/react-apollo#307] opened 2016-11-03 18:27 UTC
We have some code that looks like this:

```
eng (id) {
  x
  y {    // property y comes back as null
    z
}}

export default graphql(engQuery, {
  options: ({ params: { id } }) => ({ variables: { id } }),
  props: ({ ownProps, data: { loading, eng } }) => ({ loading, eng })
})(EngMain)

export const EngMain = (props) => {
  if (props.loading) return <div>Loading...</div>
  console.log('EngMain.js:41 ')
  const profile = props.eng.x
  ...
}

//later on in AnotherComponent.js that is called
{eng.y.z.map((item, index) => ...

```

### Buggy Behavior

in react-apollo@0.5.8 and above:
When rendering, we see something like this in console

```
EngMain.js:41 
EngMain.js:41   (NOTICE THIS GOT CALLED TWICE)
EngMain.js:42 Uncaught (in promise) TypeError: Cannot read property 'x' of undefined(…)EngMain @ EngMain.js:42StatelessComponent.render 

```
### Expected Behavior

in react-apollo@0.5.7 we see the correct/expected error:

`AnotherComponent.js:78Uncaught (in promise) TypeError: Cannot read property 'z' of null(…)
`
### Version
- broken in react-apollo@0.5.8 and above
- working as expected in react-apollo@0.5.7

**Comment by tmeasday** [comment] 2016-11-25 05:42
The second time it renders, is it possible that `props.errors` is defined?

I'm not sure exactly why but I think I've seen problems where you end up with a graphql error client-side caused by a component issue, somehow.

**Comment by tmeasday** [comment] 2016-11-25 05:44
I suspect this may be the same problem as https://github.com/apollostack/react-apollo/issues/303

**Comment by helfer** [comment] 2016-12-13 16:21
#303 should be fixed now, does that help with your issue @vonwao ?

**Comment by cesarsolorzano** [comment] 2017-04-15 01:18
Closing up old issues.

**Closed by cesarsolorzano** 2017-04-15 01:18 UTC
Labels: bug, waiting on contributor
