### ISSUE TITLE
Loading not set to true while setting new variables after an error

### ISSUE THREAD

**Issue by dallonf** [apollographql/react-apollo#1817] opened 2018-03-21 15:28 UTC
**Intended outcome:**

Refetch a query with new variables after receiving an error from the server. I would expect `loading` to be true while this is happening.

Example: https://codesandbox.io/s/n73jj3x70

**Actual outcome:**

Although `networkStatus` is `2` (`setVariables`), `loading` is `false`. This contradicts the [documentation for `networkStatus`](https://www.apollographql.com/docs/react/basics/queries.html#graphql-query-data-networkStatus):

>  If the network status is less then 7 then it is equivalent to `data.loading` being true. In fact you could replace all of your `data.loading` checks with `data.networkStatus < 7` and you would not see a difference. It is recommended that you use `data.loading`, however.

**How to reproduce the issue:**

Example: https://codesandbox.io/s/n73jj3x70

Write in the text box to update the query variables. A name that starts with "bob" will cause an error.

1. Write a valid name: "Susan"
2. Write a name with an error: "Bob"
3. Write another valid name: "Fred"

Notice that during Step 3, the "Loading..." state does not appear despite the network status being 2.

Note react-apollo is at `2.1.0-rc.5`; on the latest version (`2.0.4`), you will instead observe https://github.com/apollographql/react-apollo/issues/1336, and the state will switch to `loading: true` but never actually make a request.

**Version**

* apollo-client@2.0.1
* react-apollo@2.1.0-rc.5

**Comment by nlucero** [comment] 2018-04-19 15:57
Can reproduce with version `2.1.3`

**Comment by Gasperan** [comment] 2019-06-10 14:21
any update for this? :(

**Comment by jasonpaulos** [comment] 2019-06-13 23:57
I am unable to reproduce this issue, so it looks like it may have been fixed in a recent update. Feel free to re-open if the problem continues.

**Closed by jasonpaulos** 2019-06-13 23:57 UTC
Labels: has-reproduction
