### ISSUE TITLE
Stale props when changing variables

### ISSUE THREAD

**Issue by pljeskavica** [apollographql/react-apollo#2808] opened 2019-02-15 19:30 UTC
**Intended outcome:**
graqphl higher order component should update props like `loading` when api requests come back.

**Actual outcome:**
grapqhl higher order component will not update props after changing the variables multiple times and the request comes back with no data (null, or empty array).

**How to reproduce the issue:**
I created a small example here: https://codesandbox.io/embed/3k067v2711

Instructions on recreating issue in codesandbox:
 - Reload the sandbox
 - Type into the input at the top: `ca`
 - Change input text to: `cd`
 - Change input text to: `cr`

Now the loading status will be stuck on `true`

The problem does not happen if you type in `cr` first. 

If i pass in `notifyOnNetworkStatusChange` the problem will go away but that creates other problems with polling where the current data disappears when loading the next poll request.

I have tried this with the Query component as well and it does not resolve the issue.

**Version**
- apollo-client@2.4.13
- react-apollo@2.4.1
OR
- react-apollo@2.5.0-beta.1
 OR
- react-apollo@2.5.1

**Comment by clayne11** [comment] 2019-02-20 21:35
Is this the same issue as #2202?

**Comment by pljeskavica** [comment] 2019-02-20 22:02
@clayne11 I dont beleive so.  The issue described there is that the props are from a previous query while loading a new one.  
The issue I am describing is that the props change to reflect the loading state but do not resolve when the network request is completed.  So my loading prop is stuck true and data comes back.

**Comment by OurMajesty** [comment] 2019-03-01 13:19
Was having same issue, but never have been able to create reproducible example.
But the problem is with `skip`, if you delete / comment it (line 77), everything works fine.
So instead of query skipping, I just don't show results, until input is apt.

**Comment by pavanmehta91** [comment] 2019-03-05 11:45
Having the same issue. Query render prop won't re-render and the loading remains true despite the variable change.

**Comment by pavan-shipmnts** [comment] 2019-03-05 12:03
I worked for me in the render prop after upgrading react-apollo to 2.5.1. I also upgraded all the other apollo-client and apollo-link related packages.

**Comment by pljeskavica** [comment] 2019-03-05 17:19
@pavan-shipmnts I updated my example to use react-apollo@2.5.1 and the issue persists.

**Comment by pavanmehta91** [comment] 2019-03-06 10:35
I actually changed the fetchPolicy to network only. pavan-shipmnts and I are the same guy.

**Comment by OurMajesty** [comment] 2019-03-25 10:34
The error is still relevant in react-apollo@2.5.3 and "skip fix" is still helps. Maybe it is the same error as in #2899.

**Comment by hwillson** [comment] 2019-09-06 11:43
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!

**Closed by hwillson** 2019-09-06 11:43 UTC
